### ISSUE TITLE
0.6.0 fails installing on node 0.8

### ISSUE THREAD

**Issue by royaltm** [tapjs/tapjs#117]
```
$ nvm use 0.8
Now using node v0.8.28
$ npm install

npm http GET https://registry.npmjs.org/tap/0.6.0
npm http 200 https://registry.npmjs.org/tap/0.6.0
npm http GET https://registry.npmjs.org/tap/-/tap-0.6.0.tgz
npm http 200 https://registry.npmjs.org/tap/-/tap-0.6.0.tgz
npm http GET https://registry.npmjs.org/buffer-equal
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/difflet
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/runforcover
npm http GET https://registry.npmjs.org/yamlish
npm http 304 https://registry.npmjs.org/deep-equal
npm http 304 https://registry.npmjs.org/buffer-equal
npm http 304 https://registry.npmjs.org/difflet
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/glob
npm ERR! Error: No compatible version found: deep-equal@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","1.0.0"]
npm ERR!     at installTargetsError (/home/user/.nvm/v0.8.28/lib/node_modules/n
pm/lib/cache.js:719:10)
npm ERR!     at /home/user/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:1
0
npm ERR!     at saved (/home/user/.nvm/v0.8.28/lib/node_modules/npm/node_module
s/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.29.2.el6.x86_64
npm ERR! command "/home/user/.nvm/v0.8.28/bin/node" "/home/user/.nvm/v0.8.28/b
in/npm" "install"
npm ERR! cwd /home/user
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/slide
npm http 304 https://registry.npmjs.org/yamlish
npm http 304 https://registry.npmjs.org/runforcover
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/npm-debug.log
npm ERR! not ok code 0
```

node-tap v0.5.0 installs ok

**Comment by isaacs** [comment]
`sudo npm i -g npm`

**Comment by royaltm** [comment]
since node-tap 0.6 you started using new syntax for deps with carret "^"
node 0.8 (npm 1.2) doesn't understand this format, so can't use node-tap to test native extensions on 0.8 anymore
could you re-consider stepping back from using backward-incompatible syntax in deps?

**Comment by isaacs** [comment]
How long should we maintain compatibility for?  You are using a version of npm that is 2 years old.  It has many other problems, and I don't think it's a good idea for you to continue using it.

You have 2 options.
1. Upgrade the npm that you're using.  This also means that you'll have less problems publishing, fewer race conditions with the cache, and lots of other bugs that have been fixed and improvements that have been made.  We're up to version 2.5.1 now, and 2.6 will be out soon.
2. Pin your `tap` version to 0.5.x, so that you don't pull in 0.6.x.  This isn't as good, imo, but it would avoid the problem.

If your issue is that you want to use nvm, and it's installing an outdated version of npm, well, then you have a few options.  You could put pressure on TJ Fontaine and the folks at Joyent to release a version of Node v0.8 with a more modern npm.  You could use nvm to install node, and then have your process use a specific installation of npm that lives somewhere else (and isn't 2 years old).

> could you re-consider stepping back from using backward-incompatible syntax in deps?

No.  Time must move forward.

**Comment by royaltm** [comment]
1. travis-ci - npm 1.2 is stock nodejs 0.8 option, upgrading npm would be a pain there.
2. That's what I did. Not best solution imho too.

Please don't forget node-tap is not you average module, it's a test-suite. I hoped it should allow you to test in various environments including that with older and not backward compatible npm.

Sure, we have 0.12 now, so probably we should forget about 0.8 soon. But e.g. https://github.com/rvagg/nan still supports 0.8 and they had to pin tap too.
Time moves forward on its own, rushing things will often cause greater pain.

I see you won't change your mind, but at least it would be nice to note somewhere in README to pin tap in such cases.

**Comment by isaacs** [comment]
The problem here is that node 0.8 (and v0.10) has continued to release new versions of Node with known-broken unsupported versions of npm.
