### ISSUE TITLE
Tests fail on Windows if console.log is called

### ISSUE THREAD

**Issue by kkoopa** [tapjs/tapjs#133]
file.js:

``` js
console.log('this causes problems');
```

``` shell
> tap file.js
this causes problems
total ................................................. 0/2


  0 passing (289.623ms)
  1 pending
  1 failing
```

Removing the `console.log` call makes it work. 0.7 did not exhibit this problem.

**Comment by isaacs** [comment]
Yes.  `file.js` does not output tap, and is thus not a passing test.  This is by design.

I've had a few real-life cases in the past where simply loading a module caused the process to exit, skipping the tests.  This led to shipping broken code, because previously, this early exit would be read as a passing test.

If you really have nothing to do, you can have `file.js` do the following:

``` javascript
if (module === require.main) {
  require('tap').pass('nothing to see here')
  return
}
```

**Comment by kkoopa** [comment]
It was a scaled down example. The real problem comes from trying to use [bindings](https://github.com/TooTallNate/node-bindings) (which includes some `console.log` statements).

``` js
const tap     = require('tap')
    , testRoot = require('path').resolve(__dirname, '..')
    , bindings = require('bindings')({ module_root: testRoot, bindings: 'weak2' });
```

It works fine on Linux, but not on Windows. Should I take this up with Nate instead to get bindings not to emit to console.log? What about any other file I want to test that might include a log statement?

**Comment by isaacs** [comment]
Aha, the issue is that it should be reading as a 'skip' test rather than a failure, since even though it has output, it does not have _test_ output.

Yes, bindings should not write to stdout.  If anything, it should write to stderr via `console.error`, so as not to interfere with "actual" program output.

**Comment by kkoopa** [comment]
Yes, that is the problem. Of course bindings could be fixed not to output unnecessary output, but this breaks on testing anything that might do a `console.log` at some point. It would be difficult to disable that in an arbitrary file just to test it. This only manfiests on Windows.

**Comment by kkoopa** [comment]
Works. Thanks.
