### ISSUE TITLE
Issues found using against Fastify repo

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#14]
This is a continuation of the discussion started in https://github.com/tapjs/node-tap/issues/821#issuecomment-1682220242. I think it's better to move this out of the roadmap issue and into its own.

-----

Some things I am noticing that I find friction with:

1. Cannot disable `ts` or `jsx`. `tap@16` supports `ts: false`, `jsx: false`, and `flow: false` in the configuration file. We use these because we use `tsd` for testing types, and our tests are all under a single `test/` directory.
2. Cannot name the rc file `.taprc.yaml` or `.taprc.yml`.
3. The `node-arg` option no longer accepts a single string. I'd mainly just call out this, and others like it, in the breaking changes list.
4. The `exclude` option option does not accept a list of strings.
5. The `files` option does not accept a negation glob, i.e. in trying to work around point 1 I tried adding `- '!test/**/*.ts'` and it was ignored.

That's just what I'm seeing thus far that isn't as big of an issue as:

I'm seeing some weird failures -- https://github.com/fastify/fastify/pull/4978

<details>
<summary>Picking up wrong "class" name</summary>

```
 ✖ setDefaultRoute should emit a deprecation warning > should be equal
    --- expected
    +++ actual
    @@ -1,1 +1,1 @@
    -FastifyDeprecation
    +DeprecationWarning
    test/default-route.test.js
    18
    19   process.on('warning', onWarning)
    20   function onWarning (warning) {
    21     t.equal(warning.name, 'FastifyDeprecation')
    ━━━━━━━━━┛
    22     t.equal(warning.code, 'FSTDEP014')
    23   }
    24
    25   t.teardown(() => {
    process.onWarning (test/default-route.test.js:21:7)
    compare: ===
```

</details>

<details>
<summary>Many uncaught exceptions like:</summary>

```
 ✖ custom header in notFound handler > Cannot read properties of undefined (reading 'sub')
    test/404s.test.js
     214   fastify.listen({ port: 0 }, err => {
     215     t.error(err)
     216
     217     test('not found with custom header', t => {
     ━━━━━━━━┛
     218       t.plan(4)
     219       sget({
     220         method: 'GET',
     221         url: getUrl(fastify) + '/notSupported'
    test/404s.test.js:217:5
    lib/server.js:87:11
    Object.cb (lib/server.js:177:17)
    Server.wrap (lib/server.js:216:21)
    type: TypeError
    tapCaught: uncaughtException
```

</details>

<details>
<summary>Something in TS?</summary>

```
2> test/versioned-routes.test.js
/Users/jsumners/Projects/oss/fastify/fastify/node_modules/@tapjs/before/src/index.ts:31
    this.#t.currentAssert = this.before
         ^
TypeError: Cannot read properties of undefined (reading '#t')
    at before (/Users/jsumners/Projects/oss/fastify/fastify/node_modules/@tapjs/before/src/index.ts:31:10)
    at before (/Users/jsumners/Projects/oss/fastify/fastify/node_modules/@tapjs/test/test-built/src/index.ts:57:19)
    at Object.<anonymous> (/Users/jsumners/Projects/oss/fastify/fastify/test/versioned-routes.test.js:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._compile (/Users/jsumners/Projects/oss/fastify/fastify/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at require.extensions.<computed> (/Users/jsumners/Projects/oss/fastify/fastify/node_modules/ts-node/src/index.ts:1345:43)
    at Object.newLoader [as .js] (/Users/jsumners/Projects/oss/fastify/fastify/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
```

</details>

-----

Note: all of these issues are not shown on the parent tree https://github.com/fastify/fastify/tree/060c2e3ac423f90a4bb9337b3f1a655c0d318e89 when running `npm run unit`.

**Comment by isaacs** [comment]
Ah, that `property of undefined` seems to be an issue with the bound top level `test` method. Thanks, will investigate. 

The config stuff did shift around a bit, and configs were completely refactored. If you want to use `taprc.yml` (or any other filename) you can put this in package.json:

```
"tap": { "extends": "./taprc.yml" }
```

and it should do the right thing. You can also do the same in yaml in a .taprc file. (And extended configs can extend other configs, and so on. Or you can extend a config from a package.)

**Comment by isaacs** [comment]
> Many uncaught exceptions like:

Ah, yeah, [this](https://github.com/fastify/fastify/blob/ce216c1ddcf6be3df65d31d5e5ef8d6d9c1076ee/test/404s.test.js#L21-L24) isn't going to work. The methods on Test objects are no longer pre-bound, because it's just not feasible when most of the methods you'd care about are added by plugins that don't have a reference to the "actual" `Test` object until after they're instantiated (since it doesn't exist until after the plugins are all loaded and attached to it, which is _after_ all the plugin constructors have run).

There _is_ a safely pre-bound `test()` method that's exported by `tap` on the _root_ test object, so you can do:

```ts
import t, { test } from 'tap'

test(...)
```

and it'll work fine.

But in a subtest, sorry, you'll have to reference the methods on the object, or bind them yourself.

Similarly, the `const { test, before } = require('tap')` isn't going to work, because _only_ a handful of known methods provided by the core TestBase class are pre-bound, and `before` is provided by a plugin, so it might not exist.

I suppose `after`, `before`, etc could be added to the list, since they're relatively well-known. It wouldn't be terribly hard to pre-bind every method on the root TAP test object, but even so, `import { somePluginProvidedMethod } from 'tap'` won't work, because it isn't a named export, and making that work across dialects would require naming everything explicitly in the exports list, which would get quite tedious.  (It could work in cjs, because there is no difference between "named export" and "property of the default export".)

So, "don't rely on methods being pre-bound, or every method being in the exports" kind of feels like something that should just be called out in the changelog as a breaking change.

**Comment by isaacs** [comment]
> Picking up wrong "class" name

The issue here is that it _is_ emitting your expected warning, but only after emitting a node core deprecation warning about obsolete loader hooks. Removing those, since tap doesn't support any node versions that require them, anyhow.

**Comment by isaacs** [comment]
> The exclude option option does not accept a list of strings.

Hm, it seems like making those lists would actually be fine. In an earlier iteration, it wasn't possible to override a list type config option default from the cli, only add to it, but I guess that changed along the way at some point.

**Comment by jsumners** [comment]
> > The exclude option option does not accept a list of strings.
> 
> Hm, it seems like making those lists would actually be fine. In an earlier iteration, it wasn't possible to override a list type config option default from the cli, only add to it, but I guess that changed along the way at some point.

I should point out: `include` is the same. In my use case I think an array of `exclude` combined with `files` will solve the problem. But there may be a case where someone needs to use `exclude` in combination with `include` as an array.

**Comment by jsumners** [comment]
> > Picking up wrong "class" name
> 
> The issue here is that it _is_ emitting your expected warning, but only after emitting a node core deprecation warning about obsolete loader hooks. Removing those, since tap doesn't support any node versions that require them, anyhow.

We remove all listeners for `warning` as a first course of action when testing these deprecation warnings -- https://github.com/fastify/fastify/blob/060c2e3ac423f90a4bb9337b3f1a655c0d318e89/test/listen.deprecated.test.js#L13. Based upon https://github.com/tapjs/tapjs/commit/8bf77c59c48c54093e8001ea357f9713adb12e09 I assume you're saying that `tap` was adding new listeners at some point after the listeners removal?

**Comment by jsumners** [comment]
> Ah, yeah, [this](https://github.com/fastify/fastify/blob/ce216c1ddcf6be3df65d31d5e5ef8d6d9c1076ee/test/404s.test.js#L21-L24) isn't going to work. The methods on Test objects are no longer pre-bound, because it's just not feasible when most of the methods you'd care about are added by plugins that don't have a reference to the "actual" `Test` object until after they're instantiated (since it doesn't exist until after the plugins are all loaded and attached to it, which is _after_ all the plugin constructors have run).
> 
> There _is_ a safely pre-bound `test()` method that's exported by `tap` on the _root_ test object, so you can do:

Are you saying that this is no longer supported?:

```js
const { test } = require('tap')

test('#someMethod', t => {
  t.test('does a thing', async t => {})

  t.test('does another thing', async t => {})

  t.end()
})
```

What about?

```js
const tap = require('tap')

tap.test('#someMethod', t => {
  t.test('does a thing', async t => {})

  t.test('does another thing', async t => {})

  t.end()
})
```

> So, "don't rely on methods being pre-bound, or every method being in the exports" kind of feels like something that should just be called out in the changelog as a breaking change.

To me, this sounds less like a "breaking change" and a radical departure from the established API.

**Comment by isaacs** [comment]
No, that still works on the top level export. 

In cjs, the "top level export" is the root tap object. In esm, they're different. 

So this works on both:

```ts
const { test } = require('tap')
import { test } from 'tap'
const { test } = await import ('tap')
```

But this will only work on cjs, not esm:

```ts
const t = require('tap')
const { test } = t
```

And this way is broken (currently, but fixable):

```ts
import t from 'tap'
const { test } = t
```

Non-root test objects don't have anything prebound (and kind of can't, at least not without a lot of refactoring) so this is broken everywhere:

```ts
t.test(t => {
  const { test } = t
})
```

**Comment by isaacs** [comment]
> Based upon 8bf77c5 I assume you're saying that tap was adding new listeners at some point after the listeners removal?

It's not that tap added listeners. It added deprecation warnings being emitted, which triggered your test with unexpected data. When I updated the test to throw away anything that didn't match, it passed, but that was a bug in tap. It shouldn't do that.

**Comment by jsumners** [comment]
> It's not that tap added listeners. It added deprecation warnings being emitted, which triggered your test with unexpected data. When I updated the test to throw away anything that didn't match, it passed, but that was a bug in tap. It shouldn't do that.

👍

**Comment by jsumners** [comment]
> No, that still works on the top level export.
> 
> In cjs, the "top level export" is the root tap object. In esm, they're different.

Sorry, I'm having a difficult time understanding. I believe the below scripts replicate the test setup linked in the Fastify repo, but none of the below fails.

<details>
<summary>package.json</summary>

```json
{
  "dependencies": {
    "tap": "^18.0.0-17"
  }
}
```

</details>

<details>
<summary>index.js</summary>

```js
'use strict'

module.exports = function add(a, b) {
  return a + b
}
```

</details>

<details>
<summary>index.test.cjs.js</summary>

```js
'use strict'

const tap = require('tap')
const add = require('./index')

tap.test('add function', t => {
  t.test('adds correctly', async t => {
    t.equal(add(1, 1), 2)
  })

  t.test('concats strings', async t => {
    t.equal(add('a', 'b'), 'ab')
  })

  t.end()
})

tap.test('add function (with plans)', t => {
  t.plan(2)

  t.test('adds correctly', t => {
    t.plan(1)
    t.equal(add(1, 1), 2)
  })

  t.test('concats strings', t => {
    t.plan(1)
    t.equal(add('a', 'b'), 'ab')
  })
})
```

</details>

<details>
<summary>index.test.cjs2.js</summary>

```js
'use strict'

const { test } = require('tap')
const add = require('./index')

test('add function', t => {
  t.test('adds correctly', async t => {
    t.equal(add(1, 1), 2)
  })

  t.test('concats strings', async t => {
    t.equal(add('a', 'b'), 'ab')
  })

  t.end()
})

test('add function (with plans)', t => {
  t.plan(2)

  t.test('adds correctly', t => {
    t.plan(1)
    t.equal(add(1, 1), 2)
  })

  t.test('concats strings', t => {
    t.plan(1)
    t.equal(add('a', 'b'), 'ab')
  })
})
```

</details>

<details>
<summary>index.test.esm.mjs</summary>

```js
import tap from 'tap'
const { default: add } = await import('./index.js')

tap.test('add function', t => {
  t.test('adds correctly', async t => {
    t.equal(add(1, 1), 2)
  })

  t.test('concats strings', async t => {
    t.equal(add('a', 'b'), 'ab')
  })

  t.end()
})

tap.test('add function (with plans)', t => {
  t.plan(2)

  t.test('adds correctly', t => {
    t.plan(1)
    t.equal(add(1, 1), 2)
  })

  t.test('concats strings', t => {
    t.plan(1)
    t.equal(add('a', 'b'), 'ab')
  })
})
```

</details>

**Comment by isaacs** [comment]
The fastify tests have one where it pulls the `test` method off a t that _isnt_ the root test and calls it as a function rather than an object method. That's the line I linked to.

**Comment by isaacs** [comment]
> Cannot disable ts or jsx. tap@16 supports ts: false, jsx: false, and flow: false in the configuration file. We use these because we use tsd for testing types, and our tests are all under a single test/ directory.

So, you can technically disable typescript (and along with it, jsx and tsx), by running `tap plugin rm typescript`.  But I just realized if you do that, it'll still try to run `.ts` and `.tsx` files. I'll have to give a think about how to let a plugin update a config default. Maybe along with `config`, a plugin could export a `configDefault` object which would mutate the default of any a existing config values. Or maybe, rather than a `configDefault`, a plugin should just export `filetypes` array or something? I'm not sure what other config values you'd want to mutate, tbh.

But anyway, as of tap@18.0.0-17 published just now, you can update the `include` and `exclude` to include/exclude the files you want, and `tap plugin rm typescript` if you want to disable typescript inclusion entirely.

**Comment by isaacs** [comment]
Yeah, turned out to be pretty easy to make everything bound, actually. Shouldn't be an issue as of 0668dc7378a31582c689dcb10793c9b54bd6faa7

Sorry for all the unnecessary rationalization lol

**Comment by isaacs** [comment]
Ok, I think all of the issues you found have been addressed in tap@18.0.0-18

- `include` and `exclude` configs are lists, not single string options.
- plugins can specify `testFileExtensions`, specifying any extra file type extensions that their loaders know how to handle.
- `include` config entries can contain the special token `__EXTENSIONS__` which expands to a glob of the supported file extensions, according to the plugins supporting them. So, this means that if you `tap plugin rm @tapjs/typescript`, then it won't run `.ts`, `.mts`, `.cts`, `.tsx`, or `.jsx` files, which effectively brings back the `--no-ts`/`--no-jsx` behavior.  (Of course, you could still also just specify a `include` config with the filenames you want.)
- all  methods on `Test` objects are called on the appropriate object if `this` is undefined. (The [relevant bit of this change](https://github.com/tapjs/tapjs/commit/0668dc7378a31582c689dcb10793c9b54bd6faa7#diff-0865bd4793cd72e92424fea60f5b94529333b3154afb670b02fd033b0503a47fL44-R47) turned out to be laughably small, I was just being dense and forgot that I was already setting `this` explicitly anyway.)

**Comment by jsumners** [comment]
Looking real good now. I just need to figure out why these "bundler" tests are failing, but I'm not even sure they are supposed to be run by `tap`. So I need to get with some other team member(s) on that one.

I'm happy you were able to think of a way to make things work. I believe it will make the upgrade a lot easier for many teams.

**Comment by jsumners** [comment]
I'm not sure how the `test/bundler/` directory was being ignored by `tap@16`, but reading the PR that created the directory, it's clear that it should not be included in the unit tests. So making use of `exclude` accepting an array has solved that problem. https://github.com/fastify/fastify/pull/4978 is now all green (other than whatever the hell pnpm is doing in CI) 😀

Looking forward to the release so that I can make my PR official.

**Comment by isaacs** [comment]
Sweet! Now just need to finish docs and website. Or at least docs and ship the new content as plain old html lol
