### ISSUE TITLE
type of array failure

### ISSUE THREAD

**Issue by llafuente** [tapjs/tapjs#144]
It's not an bug, just an unexpected behaviour.

``` js
t.type([], "array") // fails, [] is "object", same as using typeof
t.type([],  Array) // pass
```

I think both should be compatible.

**Comment by rmg** [comment]
@isaacs because of how `typeof` works, I wonder if it would make sense to have a `t.isArray([])`.. On the one hand it feels like bloat, but on the other hand, there's precedence with [Array.isArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) and [util.isArray](https://nodejs.org/api/util.html#util_util_isarray_object) already singling out Array type checking. 

@llafuente for a more immediate solution, you might find [t.addAssert()](https://github.com/isaacs/node-tap#taddassertname-length-fn) useful for adding custom type asserts like this:

``` js
tap.Test.prototype.addAssert('isArray', 1, function (maybeArray, message, extra) {
  message = message || 'should be an Array';
  return this.assert(Array.isArray(maybeArray), message, extra);
});
```

Then you should be able to do:

``` js
t.isArray([]) // passes
t.isArray('not an Array') // fails
```

**Comment by isaacs** [comment]
`t.type` can match either the `typeof` result, the class, or the name of the class.  So, `t.type([], "Array")` works.

Should we make that case-insensitive?  Meh.  Feels like the wrong approach, and it'd potentially cause some false-pass tests, so it's technically a breaking change.  Maybe just clearer documentation?

Adding `t.isArray` seems fine.  If you find yourself adding that assert in all your tests and it's handy, open a PR.

**Comment by llafuente** [comment]
>  Maybe just clearer documentation?

This would be enough, i thought it was lowercased after seen "object", or "number"
