### ISSUE TITLE
match() assert won't match non-enumerable properties, but claims they are "found"

### ISSUE THREAD

**Issue by sam-github** [tapjs/tapjs#150]
```
console.error('has', e.hasOwnProperty('id'));                        
tt.match(e, {id: 1}, 'executor should be found');                    
```

`e.id` isn't (edit: _is_) in the prototype, or somewhere, so the `match()` test won't find it for purposes of comparison. I don't know if that makes sense, I think these should be equivalent:

```
t.equal(e.id, 1);
t.match(e, {id: 1});
```

and ATM, they are not.

but if you don't agree, then on failure, properties that are not "own properties" should not be listed in the "found" section, that's not very helpful:

```
has false
        not ok 9 - executor should be found
          ---
          found:
            __cachedRelations: {}
              id: 1
            __dataSource: null
          pattern:
            id: 1
```

**Comment by rmg** [comment]
@isaacs I think when printing out the `found` block it should probably use `Object.keys()` instead of `Object.getOwnPropertyNames()`, since it leads to confusing output like the above. This is because `Object.getOwnPropertyNames()` returns non-enumerable properties which get printed in the diag, but `match()` skips those properties.

**Comment by isaacs** [comment]
I agree that `t.equal(e.id, 1)` should be equivalent to `t.match(e, {id:1})`.  This is a bug.

**Comment by sam-github** [comment]
Thanks, Issacs.
