### ISSUE TITLE
Feature request: retry test on failure

### ISSUE THREAD

**Issue by cesarandreu** [tapjs/tapjs#151]
I would like to retry tests on failure. After looking around, the only solution for retrying tests is [mocha-retry](https://github.com/giggio/mocha-retry), which is broken. I'm not sure if any of the other popular test frameworks support retrying.

I'm currently using Protractor (which wraps Selenium Webdriver), and will shortly be moving to either webdriverio or nightwatch, to run end-to-end tests on my application. Selenium tests are incredibly flaky... Regardless of what you try, you get occasional failures. :(

If node-tap had support for retrying, I'd use it as my test framework for end-to-end tests.

**Comment by isaacs** [comment]
I've been thinking about this, and I keep coming to the conclusion that flaky tests are just notoriously problematic.  They should always be made non-flaky, or deleted, because "Oh, that test always fails, don't worry about that one" is always a problem.

Also, running a subtest more than once could create really weird effects on shared data objects or the state of the system.  It feels very wrong for a test runner to do that.

Maybe it would help if you could specify in more detail how you'd like this to work.  What's the level of retrying?  How many times does it retry?  What does that do to the TAP output?  (Ie, would it mean that it has to buffer up the TAP output in case it failed the first time but passed the second?)  What if it fails for a different reason three times, which do we report?

I fear that this may be too big big a divergence from predictability, which runs counter to the goals of this test runner.

If you want to re-run just the files that failed (which is a super handy way to do TDD type activities) you can use the `--save-file=<filename>` argument to tap, so that it'll re-run the failing tests on each invocation, until finally they all pass, at which point the file will be empty so it'll run everything one last time to make sure there's no new failures.

**Comment by isaacs** [comment]
Having slept on this many more times, I'm still convinced it's not really in line with node-tap's design.  If I had a function that works "most of the time", I'd probably be inclined to just run it until it works (or hits some max count) and then `t.ok(...)` whatever the result was at that point.
