### ISSUE TITLE
tap runs tests from `process.on('exit'`

### ISSUE THREAD

**Issue by sam-github** [tapjs/tapjs#161]
Tests should not be run from `process.on('exit', ...`, because any async activity that is scheduled will not actually occur.

I doubt this is intentional, it may just be a side effect of https://github.com/isaacs/node-tap/issues/152, but I am reporting seperately because it is not immediately obvious why a test that is clearly scheduling an async activity is allowing node to exit.

Example:

```
'use strict';

var tap = require('tap');

tap.test('t1', function(t) {
  //t.plan(1);
  process.on('some event that never happens', function() {
    t.pass('ok');
  });
});

tap.test('t2', function(t) {
  console.log('t2 running after node is exiting? %j', process._exiting);
  process.nextTick(function() {
    // Never runs, wtf?
    t.end();
  });
});

```

Output:

```
TAP version 13
    # Subtest: t1
    1..0
ok 1 - t1 # time=12.3ms

    # Subtest: t2
t2 running after node is exiting? true
```

In above,
- test `t1` is passing wrongly, it was never ended
- test `t2` is running in the exit event handler... so it fails to actually run its next tick and pass (its a test that can never fail)
- the exit status is `0`, wrongly, the last test never ended and has no `ok`

**Comment by isaacs** [comment]
So, what's happening is that the root test's `endAll()` method is being called on `process.emit('exit')`.  This is _supposed_ to catch unfinished child tests, however, it's testing `!child._plan` instead of `child._plan === -1` (ie, no plan, vs a plan of 0).

Then, it's also not handling the case where a test never got to be run, because it was sitting in the queue after the unfinished child test.  So it tries to start it, but never finishes _that_ one, and never catches the error.

Better behavior (imo) would be to properly detect the unfinished first child, and treat it as a failure, and then also detect the existence of other junk in the queue and fail for them as well.
