### ISSUE TITLE
Shared tests or requiring test files

### ISSUE THREAD

**Issue by lgomez** [tapjs/tapjs#186]
Hi there. First, thank you for this module.

I'm trying to figure out how to structure my tests and, more importantly, DRY them up. So two related questions:
- I want to have better control over the order in which I run my tests. I figured I could have an entry point that I use to define the order and run the tests like `test/index.js` and then execute it like so: `tap test/index`. This file would contain something like 

```
reuire('./someTest.js');
require('./secondSetOfTests.js');
...
```
- I have tests that could be share like testing a db connection which needs to happen and be checked on nearly every test file but I don't want to be writing the same test in every file.

How would you do this or is this an anti-pattern?

**Comment by isaacs** [comment]
When order matters, I usually put numbers in the test files.  For example, https://github.com/npm/npm-registry-couchapp/tree/master/test or the `00-setup.js` and `zz-cleanup.js` in https://github.com/isaacs/node-glob/tree/master/test

For shared things, I'll usually create a `test/common.js`.  There are a few ways to handle this being loaded as a top-level test.  You can either give it a dot-prefixed name, like `test/.common.js` so that it's skipped by the `test/*.js` pattern, or just have it do a "dummy test" like this:

``` javascript
// test/common.js
if (require.main === module) {
  require('tap').pass('common test file')
  return
}

// db loading stuff here...
```

I don't recommend having a single `test/index.js` that uses `require()` to load all of your tests in a specific order.  Tests frequently do stateful stuff, and leave litter around in memory, and (in my experience) it's a pain to account for all that.

**Comment by lgomez** [comment]
Thank you very much!
