### ISSUE TITLE
Install fails on Node 0.8

### ISSUE THREAD

**Issue by quantizor** [tapjs/tapjs#195]
I know it's a dead version, but your supported engines listing includes 0.8 and use of the caret (`^`) version selector is not supported in that version.

You'll need to switch to tildes to properly support it, or I'd recommend doing the tilde switch, releasing a new minor version and then going back to carets and dumping node 0.8 as a supported target with a new release.

**Comment by quantizor** [comment]
Although https://github.com/isaacs/tap-mocha-reporter has always used carets, so I don't think this library would have ever worked in Node 0.8. Maybe just bump the supported engine and call it a day...

**Comment by isaacs** [comment]
It works fine on Node 0.8, and I do run tests there somewhat regularly.  What it doesn't work with is npm 1.2.  If you first do `npm install npm@2 -g`, then it should work fine.

**Comment by quantizor** [comment]
If you add 0.8 to your travis checks, I'll bet you it will fail... since the npm version that comes with 0.8 doesn't work with carets. The upgrade method you described is fine, but it's a bit disingenuous to say you support the 0.8 engine if you require a separate npm upgrade. Just sayin'.

**Comment by isaacs** [comment]
Add this to your .travis.yml file:

``` yaml
before_install:
  - npm install -g npm@latest
```

It's not disingenuous at all.  The node 0.8 runtime works fine with this module.  The npm that ships with node 0.8 is 2.5 years old.  I've requested for years to the node project upgrade it, and finally gave up.  At this point, the Node Foundation's TSC has no interest in ever touching 0.8 again, since it's so far past its long term support lifetime.

If you want to use old unsupported software, you're going to have to expect to work around some difficulties.  I don't think that asking you to add 2 lines to a .travis.yml file is unreasonable.
