### ISSUE TITLE
Should running tests with coverage fail if coveralls command fails?

### ISSUE THREAD

**Issue by evanlucas** [tapjs/tapjs#196]
I have run into issues today where my tests pass, but coveralls is down. Should this actually fail the build or is there a better way of handling an issue such as this?

**Comment by isaacs** [comment]
That's an interesting question.

I'm not sure of the answer.  My general tendency is to favor failing if anything didn't go as expected, since otherwise you'll probably not notice, and then be surprised later.

You can always re-try the build later when coveralls comes back, right?  Maybe this could be a cli option or something?

**Comment by evanlucas** [comment]
Sure, retrying is no problem and I guess every developer will have his or her own preference on it? Was just curious. I may take a look into adding an option in the future, but see no reason for this to stay open. Thanks for your response!
