### ISSUE TITLE
COVERALLS_REPO_TOKEN not needed on Travis

### ISSUE THREAD

**Issue by jo** [tapjs/tapjs#210]
Thank you so much for integrating nyc and coveralls!

Before that [we used nyc and coveralls manually](https://github.com/eHealthAfrica/kazana-bootstrap/commit/950d2bf8042381f17e93c9395a9cbdd5259ec9a3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R6) to upload coverage to Coveralls.io. We did not need to add any token; [coveralls supports travis out of the box](https://github.com/nickmerwin/node-coveralls#usage):

> This library currently supports travis-ci with no extra effort beyond piping the lcov output to coveralls. 

It would be great if tap could support sending coverage report to coveralls.io without the need to add the `COVERALLS_REPO_TOKEN` environment variable.

**Comment by isaacs** [comment]
Wait, so, coveralls can figure out the location without the `COVERALLS_REPO_TOKEN`??  That's awesome, I had no idea!

Is it enough to check if `process.env.TRAVIS === '1'` then?  How does it figure it out?

**Comment by jamestalmage** [comment]
I would bet it's from `TRAVIS_REPO_SLUG` from the [Default Environment Variables](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables).

I would prefer that `tap` not rely on `COVERALLS_REPO_TOKEN`, since that is not available for PR's from non-collaborators.  I've been told that token is only necessary for authentication on private repos (not sure if that only means privately hosted, or also includes GitHub private repos).

**Comment by jo** [comment]
This is awesome indeed. 

The [check coveralls uses](https://github.com/nickmerwin/node-coveralls/blob/master/lib/getOptions.js#L19-L24) is just an `if (process.env.TRAVIS)`. So I'm not sure if the `TRAVIS` environment variable is set to `'1'`, the [docs state its set to `true`](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables).

Coveralls [can reference a repository either by `service_job_id` and `service_name` or via the `repo_token`](https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction). In case of Travis the `TRAVIS_JOB_ID` environment variable will be used to find the repository.

**Comment by jo** [comment]
I still find the  `COVERALLS_REPO_TOKEN` support useful to submit reports from a local maschine.

**Comment by isaacs** [comment]
> I would prefer that tap not rely on COVERALLS_REPO_TOKEN, since that is not available for PR's from non-collaborators.

I thought that Travis always ran tests with the environment vars you set?

> I still find the COVERALLS_REPO_TOKEN support useful to submit reports from a local maschine.

Yes, nothing's getting removed, just adding support for another thing in addition to that :)

**Comment by jamestalmage** [comment]
> I still find the COVERALLS_REPO_TOKEN support useful

Yeah, sure. It's presence should indicate you want it to upload, but it would be nice if that wasn't the only way to trigger it. 

Use cases to cover:
- The build is running on Travis, but they don't want coverage uploaded (i.e. not using coveralls).
- The build is not on Travis, but they do want coverage uploaded. The presence of `COVERALLS_REPO _TOKEN` is sufficient here.

Ideally you could reuse the same test script on Travis and local dev machines. I've never had a use for uploading to Travis from my local machine, so I definitely want `tap` to detect the environment. 

Perhaps the best way to handle this would be to add a `--coveralls-if=TRAVIS` (a string flag that conditionally uploads if the specified environment variable is set). `COVERALLS_REPO_TOKEN` continues to automatically trigger an upload.

> I thought that Travis always ran tests with the environment vars you set?

"secure" environment variables are not available to PR's. Otherwise I could just submit a PR with `console.log(process.env.XXX)` to get your token

**Comment by isaacs** [comment]
There's basically no downside to uploading to coveralls from CI.

The hazard I could see would be if a repo isn't set up with Coveralls, what will the failure look like?

**Comment by jamestalmage** [comment]
> The hazard I could see would be if a repo isn't set up with Coveralls

That is the scenario I was trying to cover with "they don't want coverage uploaded".  I guess you could just try on CI, and ignore if it fails to upload.

**Comment by jo** [comment]
I could imagine that there might be privacy concerns about sending data of private repositories to a third party.

**Comment by isaacs** [comment]
I can't see a way to detect that you're on Travis, and it's safe to upload your coverage to coveralls, and there's reasonable expectation that it'll work (because the repo has coveralls set up), but also that the repo is public.

Requiring the COVERALLS_REPO_TOKEN in the env seems like the most deterministic way to do that, even though it does add an extra step.

If someone can figure another way out of this puzzle, I'm open to it, but otherwise I'm going to close this.
