### ISSUE TITLE
Why is t.throws() so hard to use?

### ISSUE THREAD

**Issue by ibc** [tapjs/tapjs#216]
``` js
t.throws(function() {
    throw new TypeError('some type error');
}, TypeError, 'should throw a TypeError');
```

This just does not work.

> t.throws(fn, [expectedError], message, extra)
> 
> Expect the function to throw an error. If an expected error is provided, then also verify that the thrown error matches the expected error.

How is such a "match" verified?

**Comment by ibc** [comment]
I hope such a "error match" is not based on a just descriptive `message` property...

**Comment by ibc** [comment]
The only robust alternative coming to my mind is the following:

``` js
try {
    throw new TypeError('some type error');
} catch (error) {
    t.ok(error instanceof TypeError, 'should throw TypeError');
    t.end();
}
```

Do I miss something?

**Comment by isaacs** [comment]
The intent was to pass in a sample error object.  So, you'd do soething like:

``` javascript
t.throws(function() {
    throw new TypeError('some type error');
}, new TypeError('some type error'), 'should throw a TypeError');
```

The match in that case is based on the message property, type, and any other additional fields provided.  For example, you could specify something like this:

``` javascript
var expect = new Error("ENOENT: no such file or directory, open 'does not exist'")
expect.code = 'ENOENT'
expect.syscall = 'open'
expect.path = 'does not exist'
t.throws(function () {
  fs.readFileSync('does not exist')
}, expect)
```

> I hope such a "error match" is not based on a just descriptive message property...

Since there are only 4 Error types in JavaScript, and the language lacks typed catches, it's much more common to test based on message and other properties, as that tends to be much more restrictive.

Nevertheless, the feature you're expecting was easy to add, and it's a very reasonable thing to expect, so I added it in v5.4.0.

**Comment by ibc** [comment]
Thanks for the explanation. If you added this feature for v5.4.0, may you please update this issue?

**Comment by ibc** [comment]
Sorry, I missed the commit and the release :)

**Comment by ibc** [comment]
It works fine :)
Thanks a lot.

**Comment by bathos** [comment]
_Not directly related to the original question in this old thread, but for anybody whose Google searches have brought them to this issue like mine did:_

If you imagined that passing a string for the argument named "message" would match against the error message, it won’t — the "message" that’s being referred to is an optional test name for the specific assertion, not the error message. However there is a simple way:

```js
t.throws(fn, /regular-expression/);
```

(This is also true for `Test.prototype.rejects`).

---

@isaacs I’m a bit horrified by the number of incorrect assertions with tap I’ve probably written in the past because I didn’t realize this 😅 (with the string arg, you get a pass if the fn just throws, regardless of what it throws, so I didn’t see the mistake for a long time). Maybe this was just me, but if not, I’m wondering if the documentation for `throws` could be clearer?

**Comment by JJ** [comment]
I still couldn't make this work properly:

```javascript
test("Exception works as expected", function (t) {
  t.throws(function () {
    throw new Error("Foo");
  }, Error);
});
```

Yields:

```
 FAIL ​ test/unit/exceptions.js
 ✖ test unfinished

  test: Exception works as expected
  stack: |
    file://test/unit/exceptions.js:10:1
    async Promise.all (index 0)
  at:
    line: 10
    column: 1
    file: file://test/unit/exceptions.js

​ FAIL ​ test/unit/exceptions.js 1 failed of 2 14.391ms
 ✖ test unfinished



                         
  🌈 SUMMARY RESULTS 🌈  
                         
​ FAIL ​ test/unit/exceptions.js 1 failed of 2 14.391ms
 ✖ test unfinished
```

*Update* OK, I see that `t.end()` is missing...
