### ISSUE TITLE
configurable colors

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#227]
Make colors (including diff colors) configurable

**Comment by marlun** [comment]
In my terminal color scheme the foreground color of diffs are light gray on light red and green which is a little hard to read. Would appreciate this if it would help me.

**Comment by remy** [comment]
I appreciate this is a near 2 year old issue, but since it's still open, this is what it looks like on my dark terminal:

<img width="1279" alt="screen shot 2018-01-07 at 14 30 17" src="https://user-images.githubusercontent.com/13700/34650323-5b58f166-f3b7-11e7-824f-8b7a0beada3d.png">

Is that expected? If so, _maybe_ (without checking the source), it could be a job of changing the foreground colour to black (which I'm guessing is being left untouched atm?).

If I can get any direction, I might take a quick shot a PR.
