### ISSUE TITLE
Creating TypeScript types definition

### ISSUE THREAD

**Issue by brennanMKE** [tapjs/tapjs#237]
http://definitelytyped.org/guides/contributing.html

There's currently no definition for the `tap` module. I like using `tap` so I will start creating the initial definition for the functions that I am using. I can submit it as a PR and then follow the guidelines for contributing to DefinitelyTyped.

**Comment by brennanMKE** [comment]
This may cover most of it.

``` typescript
// tap.d.ts

declare module Test {

  class Deferred {
    resolve();
    reject();
  }

  class test {
    constructor(options?: any);
    tearDown();
    setTimeout(n: number);
    endAll();
    threw(er: Error, extra: Error, proxy: any);
    pragma(set: any);
    plan(n: number, comment?: string);
    test(name: string, extra: Error, cb: () => void, deferred: Deferred);
    loop(self: test, arr: test[], cb: () => void, i: number);
    next(er: Error);
    current();
    stdin(name: string, extra: any, deferred: Deferred);
    spawn(cmd: string, args: string, options: any, name: string, extra: any, deferred: Deferred);
    done(implicit: boolean);
    autoend();
    printResult(ok: boolean, message: string, extra: any);
    writeDiags(extra: any);
    passing();
    pass(message: string, extra: any);
    fail(message: string, extra: any);
    addAssert(name: string, length: number, fn: () => void);
    comment();
    push(chunk: any, encoding?: string);
    bailout(message: string);
    beforeEach(fn: () => void);
    afterEach(fn: () => void);
  }

}
```

**Comment by brennanMKE** [comment]
See PR

https://github.com/tapjs/node-tap/pull/238

**Comment by isaacs** [comment]
I'm in favor of this!  Comment left on PR.  Thanks for taking this on :)

**Comment by brennanMKE** [comment]
I haven't had time to make any updates. We are officially using Mocha but I have used `tap` in the past because it just works. I will try to come back to it for my own projects which I will be doing in TypeScript going forward.

**Comment by jamestalmage** [comment]
> I can submit it as a PR and then follow the guidelines for contributing to DefinitelyTyped.

My understanding is that it is no longer necessary to submit to DefintelyTyped if the `.d.ts` file is deployed to `npm`. DefinitelyTyped still exists to accommodate libs that refuse to do that. [Reference](https://www.reddit.com/r/typescript/comments/3ur0xb/question_node_where_should_i_store_my_dts_files/)

**Comment by brennanMKE** [comment]
Yes, I started using `typings` instead of `tsc` which is now deprecated. I do not know how types are supposed to be deployed now. It's been a moving target in recent months.

**Comment by dlmanning** [comment]
FYI : have attempted to pick this up in #256

**Comment by huan** [comment]
@isaacs 

the absense of this file casuse you can not `import { test } from 'tap'`.

I suggest you should consider to merge this PR, for adding the `index.d.ts` file into tap reposity.

after that, any typescript user could directly import tap, that would be wonderful! :)

**Comment by isaacs** [comment]
@zixia It needs tests.

**Comment by brennanMKE** [comment]
How is testing done for typings?

**Comment by isaacs** [comment]
@brennanMKE Good question!  I'd add typings or typescript or whatever as a devDependency.  Add a JavaScript file in `test/` that'll fail if the typings don't match.

Basically, if I change the return type of some function, or add an argument, or whatever, then I'll almost certainly forget to update the type definition file.  So, to prevent that, there should be something that'll raise the error when I run `npm test` if that happens.  That's the bottom line requirement, I'm pretty agnostic about the implementation.  If you have any questions, I'm happy to provide answers if I can.

**Comment by d99m** [comment]
@brennanMKE, it's pretty much done as @isaacs described it. Testing is usually done by adding `{libname}-tests.ts` file alongside `{libname}.d.ts`. In this file everything exposed in the public API should be called with correct type annotation. If the compiler compiles without any errors, that means type definitions are valid. Otherwise, there is a mismatch between API and the definitions file. A good example of a thoroughly tested type definitions are in the [`typescript-ramda`](https://github.com/donnut/typescript-ramda/blob/master/ramda-tests.ts) repository. Hope that helps.

**Comment by brennanMKE** [comment]
Thanks is good to know. I never considered how testing ambient type definitions would be done. Generally I'd prefer the original code start as TypeScript so the interface could be extracted from it while the JavaScript is published on npm.

**Comment by longrunningprocess** [comment]
Just tried this today, looks like simply adding something to this registry might do it?  Hope this is helpful:

```
typings install tap                                                                                                                  
typings ERR! message Unable to find "tap" ("npm") in the registry.                                                                           
typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
```

**Comment by huan** [comment]
@isaacs ping~

I suggest let's start to add type definition to tap, then we can test & fix it.

It's not a big deal because this only affects the TypeScript users. ;-p

**Comment by reverofevil** [comment]
What's the current progress on this?

**Comment by isaacs** [comment]
@zixia @polkovnikov-ph Nothing has changed, because no tests have been added.

If you want https://github.com/tapjs/node-tap/pull/256 or any PR to land in this repo, at a bare minimum it must have a test that:

1. fails before the patch is applied
2. succeeds when the patch is applied

Without that, I won't add any code to this project, because I can't verify that it works, and I can't prevent myself from breaking it in the future.

> It's not a big deal because this only affects the TypeScript users. ;-p

If you want to create a separate repo that has typing info, maintained by someone else, then that's fine.  You can chase your own duck.  But, as for me, and my own personal values and time and energy, I don't maintain code that doesn't have tests, and that includes type info.

Look, as the author of a test framework, it should not be _super_ surprising that I'm a little bit finicky about needing tests for every change.  I'm happy to accept a PR with typings for node-tap, but I won't accept _any_ PR here (or anywhere else) that adds functionality and doesn't have tests.  To do otherwise would be irresponsible, because I can guarantee you I will break it if it doesn't have tests, and while it's fine to say "it only affects TypeScript users", those users are going to come here and complain when it doesn't work, and they'll be right to complain.  I don't need that on my conscience.

Progress will be evident in https://github.com/tapjs/node-tap/pull/256, which will land once there are tests for it.

I'm locking this issue so that I don't have to keep repeating this message.

**Comment by isaacs** [comment]
Tap v18 has types now, as it's written in TypeScript, and so the types are always up to date and fully tested.

Check it out with `npm i tap@pre`. Be sure to read the [changelog](https://node-tap.org/changelog/#18.0) as a lot has changed.
