### ISSUE TITLE
"not ok timeout" for express app that connects to mongo

### ISSUE THREAD

**Issue by melo0187** [tapjs/tapjs#239]
I require my express app in the test file and also require supertest to write API tests with tap.
Sadly things do not work as long as my app connects to mongoDB with mongoose. Running the test file with tap always gives this output:

```
test/api.trips.spec.js ................................ 1/2 30s
  not ok timeout!
    handles:
      - type: Socket
        events:
          - end
          - finish
          - _socketEnd
          - connect
          - error
          - timeout
          - close
          - data
    signal: SIGTERM

total ................................................. 1/2


  1 passing (30s)
  1 failing
```

When I remove the part where the connection to mongo is created from my express app the test will instantly pass.
I did not even start writing a real test since even this dummy one won't pass:

```
var test = require('tap').test;
var app = require('../app');

test('test my app', function (t) {
    t.pass();
    t.end();
});
```

Or does it pass? Why does the output say there are two tests anyway?

Any help is much appreciated!

**Comment by Freyert** [comment]
@melo0187 try just running the test file with `node <test-file>`. This will output the full TAP output and might provide more information.

You might also pass a string into `t.pass` so we can see that it is the one passing.

**Comment by isaacs** [comment]
So, here's what's happening:

The test function runs, and it creates a single passing test, and then ends.

However, the process doesn't end, because you have a socket left open!

My guess is that mongoose is connecting to the mongodb server, but never closing the connection.  This is pretty normal.

You can either (a) kill the connection (for example, in a `test(...)` block after all the other testing is done), or (b) call `socket.unref()` on the socket (assuming you can get a reference to it) so that it doesn't keep the process from closing gracefully.

I very much do _not_ recommend forcibly killing the process via `process.exit()` or some such.  It will tend to obscure cases where you're leaving things lying around in an un-closed state, and thus it will hide valid problems with your program.

Hope this helps!

**Comment by isaacs** [comment]
By the way, the reason I know it's a socket is this bit:

```
    handles:
      - type: Socket
        events:
          - end
          - finish
          - _socketEnd
          - connect
          - error
          - timeout
          - close
          - data
```

Tap will dump a list of all the open active handles and requests when the process is forcibly killed due to a timeout.

**Comment by melo0187** [comment]
@isaacs thank you for clarifying!
