### ISSUE TITLE
Test process closes with SIGPIPE

### ISSUE THREAD

**Issue by novemberborn** [tapjs/tapjs#242]
[AVA](https://github.com/sindresorhus/ava) uses tap to run its own tests. We've been seeing intermittent test failures. I've been able to reproduce these outside of AVA but only when tap is used. I suspect it might actually be a Node issue but I need some help reproducing it outside of tap.

In essence the process spawned by tap to run the test is closed with a `SIGPIPE` signal. This seems to happen when sending a message to a child process (of the test process) that is exiting. See https://github.com/novemberborn/_ava-tap-crash for full background and a reproduction of the issue. https://github.com/sindresorhus/ava/pull/642 fixes the issue in AVA.

I'd appreciate any insight into how tap spawns processes, and why `SIGPIPE` occurs in tap but not standalone. Thanks!

**Comment by isaacs** [comment]
Poking at this now.

I think it's a race condition.  The SIGPIPE probably happens more frequently when using tap because it's just doing more stuff, and doing that stuff takes longer.

Note that this:

```
  process.on('exit', function (code, signal) {
    // Once you reproduce the crash, note how this line didn't log anything.
    console.error('child exited', code, signal)
  })
```

is really not a mystery.  When a process dies due to receiving a fatal signal, it does not emit an `error` event.  That's like a "do not pass go, do not collect $200" kind of exit, no more trips around the event loop or into JS.

**Comment by isaacs** [comment]
Yeah, what's happening (near as I can tell) is that the `foo.js` process is exiting before the `bye` message can be sent to it.

This only happens when using tap, because tap is doing a bunch more stuff at startup, putting things on the event loop, running JS, etc.  When running in standalone mode, it doesn't ever fail because it's never slow enough to be trying to send the message before the foo.js process is closed.  (In other words, `standalone.js` and `foo.js` do roughly the same amount of stuff at startup, but `tap.js` is being loaded as a child process in node-tap, its output is a pipe being read by the parent, it loads a test framework, etc etc.)

I'd be willing to bet, though, that if you ran this for long enough, or in enough different varying CPU utilization scenarios, it'd eventually fail without tap's involvement as well.  It's a pretty narrow window to get through, where the IPC channel has been set up, but then the process has been torn down, and the exit event hasn't gotten to the parent process yet.  The more JS stuff you're doing, the more likely that something might get delayed, resulting in trying to write to a pipe that no longer has a reader.

You can work around this in one of two ways:
1. Make the `foo.js` file stick around a bit longer.  Set up a `setInterval` or something to keep the event loop active.
2. Listen in the parent process for `SIGPIPE`, and know that this means that your child proc got away from you, and the node process didn't catch the exit (really, the channel close) in time to prevent the write on the IPC pipe.

So, this isn't really a tap bug (except in the general sense that if tap could do all it does with less code, then that'd be better -- but it does a lot of useful stuff, and that stuff requires some CPU cycles), and I'd argue it's not really a node bug either (except in the sense that if node could catch channel close events faster and avoid invalid IPC writes then that'd be better -- but it can't interrupt JavaScript in flight either).  It's just a challenge of using inter-process communication in this way.  It's not synchronous, and the ordering of events is not guaranteed.

**Comment by novemberborn** [comment]
@isaacs thanks for the explanation. The solution in AVA was to track when we'd told the child process to exit and not sending any more messages afterwards.
