### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by watilde** [tapjs/tapjs#259]
Let me proposal `-j` option to `tap` command to decrease test time.

```
$ node -e "console.log(require('os').cpus().length)" | tap -j
```

**Comment by isaacs** [comment]
(did you forget an `xargs` in there?  Or are you suggesting we read the job number from stdin?)

I assume that this would be like `make -j4`, to run tests in parallel, like http://npm.im/ava

The challenge is that, since tests are not a directed graph (like compilation targets), and instead often _must_ be run in a specific order, it's very challenging to have parallel jobs.  At the very least, it adds a lot of buffering and stuff in order to not have the output get all mixed up.

I think this probably won't happen.  If you have enough tests, and they are slow enough, that it's worth going through the extra effort to run them in parallel safely, then http://npm.im/ava might be a better fit.

That being said, I'm definitely interested in hearing how you might see this working and exploring it.  I just don't want to give any false hopes :)

**Comment by jamestalmage** [comment]
I second the AVA recommendation! 😈 

As @isaacs mentioned, there are lots of pitfalls around parallel testing, but it's what we are focused on solving.

Specifically, while AVA does offer a `TAP` compliant output, it does not support nesting. We are considering offering nested groups for grouping hooks (`beforeEach`, etc). But it will likely never offer nesting of the `TAP` output via [SubTests](https://github.com/isaacs/testanything.github.io/blob/561d60903f3970ca6d9fe59ad8f467b578e67db2/tap-version-14-specification.md#subtests). Because test results arrive interleaved, it would mean buffering output until all subtests were complete before printing. Instead we just abandon the concept of sub tests entirely, and prefix the test name as necessary to help you locate failures. I think `node-tap` would have similar difficulties if it were run in parallel.

**Comment by watilde** [comment]
When I was waiting the result of `npm test` in my local, simply I thought it would be nice if the `tap` can create `cluster.fork` in `runAllFiles` to run tests in parallel, but at first I should care about the order of running files specified like you said😭 

Yeah I will try to use ava. Thanks for your courteous replies😺

**Comment by pke** [comment]
@jamestalmage @isaacs so AVA is a (drop-in) replacement for this lib?

**Comment by isaacs** [comment]
@pke Ava is an alternative test framework and runner but definitely not a drop-in replacement.  It's very different.

Also, node-tap supports parallel tests now. http://www.node-tap.org/parallel/

**Comment by tryhardest** [comment]
@isaacs or perhaps @jamestalmage I am just going through them both and though now that Node-Tap has parallel, would yu be able to kindly speak to which AVA vs Node-Tap might each be better suited too?

Or at least the ways that Node-Tap differs or is a better-suited use case for? Thank you

**Comment by isaacs** [comment]
I haven't used ava extensively.  Since tap is custom-built for my preferences, I find it suits me best :)

Parallel testing isn't really new in tap (it's been there for a few years now, through 4 major versions), and so it really isn't a differentiator between ava and tap.

The best way to check if tap might be a good fit for you would be to look at [the list of opinions that tap has](https://node-tap.org/#why-tap).  If those resonate with you, then there's a good chance tap will as well.
