### ISSUE TITLE
Using tap with TypeScript

### ISSUE THREAD

**Issue by cweilguny** [tapjs/tapjs#313]
Hi,
is there a best-practice to using tap with tests written in typescript?

I'm running my typescript files with [ts-node](https://www.npmjs.com/package/ts-node):
`ts-node some-file.ts`.

In the ts-node documentation there is an example for tape:
`ts-node node_modules/tape/bin/tape some-test.js`.

Piping the output of this example through `tap` works, but you only get the TAP results formatted. To get the comforts of tap, like coverage, I tried to swap tape with tap:
`ts-node node_modules/tap/bin/run some-test.ts`.

Where the test file is as simple as:

``` typescript
import {test} from "tape";
test("Tests up and running", function(t) {
    t.plan(1);
    t.ok(t, "Yope!");
});
```

Running the test with the above command gives just this output, as if there is no test in the test file (but there is):

``` plain
total ................................................. 0/0
  0 passing (150.283ms)
  ok
```

How do you guys run typescript tape tests with tap?

**Comment by isaacs** [comment]
So, you'd have to either compile your tests to JavaScript or (on Unix systems) you could use a shebang line like `#!/usr/bin/env ts-node` at the top of the file, and `chmod 0755 test.ts` to make the test file executable, and then run `tap test.ts`.

When I try this, though, I get the following error, probably because I don't know how to type script:

```
$ node_modules/.bin/ts-node test.ts

/Users/isaacs/dev/js/x/node_modules/ts-node/src/index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
test.ts (2,15): Cannot find module 'tape'. (2307)
```

**Comment by cweilguny** [comment]
Well, this just moves the call to ts-node into the file but doesn't change the results. But thanks anyway!

I hoped one of the tap users did try that already. But I feel it's more like a ts-node issue instead of node-tap, so I asked over there.

**Comment by huan** [comment]
@isaacs @netdesk 

we got error of `test.ts (2,15): Cannot find module 'tape'. (2307)` is because typescript force define type in a defination file, when use `import`.

the quick fix is not to use `import`, use `require` instead:

```
const { test } = require('tap')
```

then after I put a shebang in the 1st line of test.ts file:

```
#!/usr/bin/env ts-node
```

and make the test file executable:

```
$ chmod +x test.ts
```

finally tap worked with ts-node and typescript! (in two ways)

I can run the test.ts directly to test like this:

```
$ ./test.ts
```

and also I can use tap as typescript tests runner:

```
$ tap ./
```

works like a charm. this push me back here from AVA, thanks!

https://github.com/avajs/ava/issues/631#issuecomment-250067693

**Comment by kevincaradant** [comment]
Hi

Sorry to ask again that @zixia , but I see you on a lot of issues about TS on Tap, Ts-node, AVA etc
I want to use TAP instead of TAPE to have the coverage which works with the compile on the fly and don't use if possible nyc until they fix the problem of compile with TAPE.
I'm using UNIX and Windows and I tried to apply exactly the command on Windows:
`ts-node node_modules/tap/bin/run some-test.ts.`

Result 0% as in the initial post that seems normal ?

But I don't understand how to resolve this issue under Windows.
What steps have I to follow to fix it ? 

I tried AVA but same problem, I was lost. Have I to use your fork of AVA @zixia ?
Maybe you will be able to help me :)

Thank you in advance

**Comment by huan** [comment]
Hi @kevincaradant ,

I never try to get the coverage under win32, I just put all of them to CI.

I suggest you do so too, if you only want to get the code coverage. :)

Hope this could help you.

Huan

**Comment by kevincaradant** [comment]
Ok Alright.

Thank you for your answer, I will check that  :)

**Comment by ilyadoroshin** [comment]
Leaving the link to my PR that makes tap work with ts-node #481
