### ISSUE TITLE
Suite-wide setup and teardown

### ISSUE THREAD

**Issue by jtlapp** [tapjs/tapjs#325]
I'm writing an end-to-end test suite for a site with a backend database. There will be many test files. The following procedure must precede a run of any set of these files:
1. Build the database schema using DB migrations.
2. Launch the web server being tested.
3. Launch the [Selenium](http://www.seleniumhq.org/) server for use with [webdriver.io](http://webdriver.io/).

I now run the entire test suite or just the few files I'm working on. When I'm done, ideally cleanup would be automated:
1. Terminate Selenium.
2. Terminate the web server.
3. Tear down the test database.

Are there any ways other than the following for accomplishing this?
1. Manually run setup and teardown scripts before and after testing.
2. Create a script that brackets a call to the `tap` test runner between calls to scripts that setup and teardown.
3. Rely on the [glob](https://github.com/isaacs/node-glob) sort of files, naming the first and last files to run so they sort first and last.

The second two of the above options require that you run the entire test suite -- you can't cherry pick test files to run and be assured of setup and teardown for those files.

I'm entertaining the following solution for [`subtap`](https://github.com/jtlapp/subtap), which is my debugging-focused test runner that works on top of `tap`:
1. The test runner passes the argument `--first-of-run` to the very first file that it runs.
2. The test runner passes `--first-of-dir` to the first file that it runs from each directory.
3. The test runner passes `--last-of-dir` to the last file that it runs from each directory.
4. The test runner passes `--last-of-run` to the very last file that it runs.
5. An option passed to the test runner enables or disables the above behavior.

Each test file could then call setup and teardown function in a shared library. Those functions would look for these arguments to decide whether this particular file is responsible for setup or teardown. The `--first-of-dir` and `--last-of-dir` arguments allow setup and teardown to vary by directory, even having no setup or teardown for some directories, such as those that only do unit testing.

However, I'm reluctant to add this behavior to `subtap` because I view `subtap` as my tool for debugging tests, not my tool for running regression tests or checking for coverage. I would like the latter tool to remain `tap`. I would prefer that the same solution be available to both `tap` and `subtap`, so that I could run my tests with either runner.

Is there a solution to this general problem that I'm missing? If not, would you mind coordinating one with me, so that `subtap` test suites remain compatible with `tap` test suites? Thanks!

**Comment by jtlapp** [comment]
There's a challenge for the use case I identified: one process needs to terminate processes started by another process. I guess the initial process would have to write the PIDs somewhere.

What do most people do? Manually prep the test suite, and manually tear it down?

**Comment by isaacs** [comment]
The solution you're suggesting adds a _lot_ of API surface.

Typically, I just put a `00-setup.js` file in the directory to do all the setup, and a `zz-teardown.js` if teardown is necessary.  For example, this setup and teardown might [create fixtures](https://github.com/isaacs/node-glob/blob/master/test/00-setup.js) or [start a server in a detached process](https://github.com/npm/couch-login/blob/master/test/00-setup.js) (this particular test was the inspiration for [t-up](http://npm.im/t-up), which makes this kind of thing much easier).

Within a specific test file, I usually do this with `t.test(..)` blocks, because I like the file to read in order of execution.  It always seems weird to me to have the teardown be at the top of the file, but that's just me and my own esthetic preference.

**Comment by isaacs** [comment]
> There's a challenge for the use case I identified: one process needs to terminate processes started by another process.

Sorry, I missed this bit.  That's exactly and only what `t-up` is for :)  It does it by writing the pid to a file, yes.

**Comment by jtlapp** [comment]
Dang that's all helpful! I'm building a test suite this weekend, making sure all the pieces are in place for someone else to follow with her own suite. Two things I notice:
- We'll be duplicating the 00-setup.js and zz-teardown.js in each directory. I guess we can handle that with symbolic links.
- There's a lot more typing involved with executing just one file, since you now have to explicitly run the setup and teardown files too. At least that seems to be the case for the `tap` test runner. With `subtap`, I can have the setup and teardown files run for any subset of subtests I want to run.

I'll see where I end up. Your solution may work fine.

Incidentally, I see very little mention of `tap` out on the intertubes. It's all `tape` and some [`faucet`](https://github.com/substack/faucet). Yet after trying to pull off my test runner on top of `tape`, I discovered that its architecture limits its flexibility and my ability to extend it, whether by forking or monkey-patching (I tried both). And `faucet` appears to be dead.  I am constantly surprised at what I'm able to do with `tap`.

Github shows `tap` preceding `tape` by about a year, so the timing doesn't explain it. Any idea why `tap` is relatively unknown? Once I started investigating `tap`, I found myself missing `faucet` and opted to support faucet-like pretty-printing in `subtap`. How do we sweeten up the `tap` tool suite?

**Comment by jtlapp** [comment]
An observation. You mentioned not liking to put a teardown first. My tests connect to a database. If a test errors for some reason and doesn't make it to the cleanup statement, the test doesn't close the database connection, and the process hangs. The test runner catches this by timing out.

However, if I put a teardown first to always close the DB connection, an error causes the test to end immediately, no waiting for the runner to timeout. Much less annoying.

UPDATE: But that's still different from providing an `afterEach()` teardown for each subtest.

**Comment by isaacs** [comment]
> However, if I put a teardown first to always close the DB connection, an error causes the test to end immediately, no waiting for the runner to timeout. Much less annoying.

That sounds like a reasonable justification.  It's all tradeoffs :)

> Github shows tap preceding tape by about a year, so the timing doesn't explain it. Any idea why tap is relatively unknown? Once I started investigating tap, I found myself missing faucet and opted to support faucet-like pretty-printing in subtap. How do we sweeten up the tap tool suite?

Idk.  Probably has something to do with Substack being a better OSS personality cult than I am, along with the fact that tape was much better on day 1 than tap (and is the number 1 test runner among the browserify crew), and that node-tap didn't get much love until I picked it up again and rewrote it in mid-2015.

The lack of popularity doesn't bother me much, though.  It's primary purpose from my point of view is as a gardening project.

**Comment by focusaurus** [comment]
Just want to chime in that I have very similar use case to @jtlapp although a bit simpler. Ideally my code would:
- connect to db, reset schema
- start web app
- run all tests
- close down and exit

I'd prefer having this all be a single process but I was able to get it working with tap by
- running the DB setup/wipe script prior to the tests (scripted normally, ad-hoc as needed)
- putting a boilerplate `tap.tearDown(process.exit)` in every file, which alleviates the need to explicitly stop the web server, disconnect DB pool, and allow node to exit.

This actually is working OK for me. I'm starting/stopping a web server and associated DB connection pools a lot of times, which makes my whole suite slower, but it's still small enough that for systems level tests it's tolerable. If this app had more mocky/fast unit tests I'd have a separate suite for that which would be fine.

---

(Aside for misc praise)

I like that tap properly handles invalid test files (javascript syntax errors, unexpected runtime exceptions) properly, keeps running the other tests, but still reports the failure in TAP and exits non-zero. I've had problems getting that right with both `tape` and `tape-catch`.

I love that the path to the  file is printed and that basic synchronous tests can be 1-liners with no extra function definition. And that I can use `same` instead of `deepEqual`.

**Comment by jtlapp** [comment]
My unit of test is the root-level subtest, so I have a call to `afterEach()` make sure things get cleaned up before the next test. But I do close the DB connection in a `teardown()` on the root.

I haven't yet been able to pursue full multi-file automation because [`webdriverio`](http://webdriver.io/) sometimes times out trying to get a response from Selenium. When it does browser windows remain open, and (only) in this circumstance my process exit handlers can't close them. I don't want a thousand windows open at the end of the test run. I've put this on hold until I get smart enough about how multiple exit handlers interact together -- they don't seem completely independent as yet. But I do otherwise have `tap` and [`subtap`](https://github.com/jtlapp/subtap) working nicely with `webdriverio` and Selenium.

I also came to `tap` after getting frustrated with the fragility of `tape`. `tap` is well designed.

**Comment by konobi** [comment]
Generally for this sort of thing, I have a `test/lib` folder that I keep shared code in that's explicitly for  reuse in test code only. That way I can `require('./lib/setup')() and require('./lib/teardown')()`. Tests are _just_ code, so code reuse between tests is just fine. Make sure that your tap tests correctly encode what you are testing in each script and that you don't lose their meaning while trying to DRY. Tests are one place where I am fine with a little redundancy, as long as the tests make sense in the context they're defined in.

**Comment by isaacs** [comment]
Closing this because there's already a few ways to do it, and there hasn't been much activity here.  Happy to reopen if I'm misreading the situation.
