### ISSUE TITLE
Focused specs

### ISSUE THREAD

**Issue by emilos** [tapjs/tapjs#326]
Is it possible to run one spec only? I had a look at the docs but didn't find any info about it. `jasmine` has a concept of focused specs `fit`, mocha provides an `only` method. I like tap much and such feature would make my work easier in some cases.

I can have a look at it and create a PR if it's in scope of the project.

**Comment by konobi** [comment]
You can run one file at a time pretty easily. Perhaps it's better to break your script out into separate files rather than trying to run something in the middle of a file.

**Comment by isaacs** [comment]
Yeah, we've talked in the past about ways to do this, but it sort of runs counter to the design principles of node-tap.

Tap runs the test functions immediately, so that there's as close as possible correlation between the test file and the TAP output.  So that a file like this:

```javascript
var t = require('tap')
console.log('one')
t.test('two', function (t) {
  console.log('two')
  t.pass('this is fine')
  t.end()
})
console.log('three')
t.test('four', function (t) {
  console.log('four')
  t.pass('also fine')
  t.end()
})
```

produces the following intelligible output:

```tap
one
TAP version 13
# Subtest: two
two
    ok 1 - this is fine
    1..1
ok 1 - two # time=8.545ms

three
# Subtest: four
four
    ok 1 - also fine
    1..1
ok 2 - four # time=1.01ms

1..2
# time=30.565ms
```

That only works if tests are run _before_ any subsequent tests are even encountered.  If there was a `.only()` method on the second test, then it wouldn't know until it had _already_ run the first test, and the only way to do that is to make all the `t.test()` calls async, which means that console.logs came out of order.  They may come out of order _anyway_, of course, if a deferral of t.end() pushes them into a queue, but at least in the sync test case, it just runs top to bottom, and that helps debugging in a surprising number of cases.

(Hijacking console.log and pushing it into the same queue is a bad idea that I've tried.  It very much does not make things less confusing.)

It would be possible to say, from the top level, "only run tests matching some pattern", but then that's a bit hard to do in a way that's sensitive to child tests.

```js
t.test('one', function (t) {
  t.test('two', function (t) {
    t.pass('this is fine')
    t.end()
  })
  t.end()
})
```

So, if I run `tap test.js --only-run-tests-matching=/two/` then how does it know that a child test named "two" is coming when it encounters the parent test?  If I do `--match=/one$/` then should it run the `two` child test?  (And if it doesn't, then the parent test is invalid!)  What if you do `tap.plan(4)` at the top, should we ignore the plan, or produce invalid TAP, or ignore the `--match` arg?  It's more complicated than it looks!

The state of the art currently is to use multiple test files.  It's a good idea anyway.  Each one gets a standalone process context, it's very clean and predictable.  You can do `node test/foo.js` to run the test file directly, or `tap test/foo.js` to get all the fancy output prettiness.

I do occasionally, in debugging, comment out huge chunks of a file or put a `return` halfway down, but that's more the exception than the rule, and I usually take that debugging action as a smell indicating that I should _probably_ split the tests up into separate files.

**Comment by emilos** [comment]
Thanks for the explanation, that definitely makes sense. I believe that splitting the files is not always a solution though, e.g. you might have very few specs which take a very long time to run.

I know the issue is closed, but I though of other way to do it and maybe the solution below would make you interested. Basically `only` would be treated as syntax sugar for skipping all other tests.

The idea is quite simple:
- add a first pass test to see if any of the specs has `.only(` (simple regexp would probably be enough)
- if it doesn't continue as usual
- if it has then preprocess the test files with some simple static code analysis, e.g.

input

```javascript
var t = require('tap')
console.log('one')
t.test('two', function (t) {
  console.log('two')
  t.pass('this is fine')
  t.end()
})
console.log('three')
t.test.only('four', function (t) {
  console.log('four')
  t.pass('also fine')
  t.end()
})
```

output

```javascript
var t = require('tap')
console.log('one')
t.test('two', { skip: true }, function (t) {
  console.log('two')
  t.pass('this is fine')
  t.end()
})
console.log('three')
t.test('four', function (t) {
  console.log('four')
  t.pass('also fine')
  t.end()
})
```

Would this make any sense?

**Comment by isaacs** [comment]
@emilos You can definitely write such a thing without making any changes to node-tap.  You don't need my permission, but you have my blessing :)

I'd recommend _not_ using a regexp.  Consider this program:

```js
var o = 'only'
t.test[o]('only run this', fn)
```

**Comment by emilos** [comment]
Haha, thanks. I'd probably ignore cases like that. The first pass test would simply check if it makes any sense to make the static code analysis that would check it properly :) - it would be expensive to do it for every test file. It was worth asking anyway, thanks for your time!

**Comment by konobi** [comment]
With TAP, the general way to run a specific test, is to split that test out into a different test script.
