### ISSUE TITLE
Allow Multiple Reporters

### ISSUE THREAD

**Issue by shaicantor** [tapjs/tapjs#335]
Can you add the feature to add multiple reporters?
For example: spec and xunit.
Meaning, writing spec output and xunit xml file.
There are a few reporters that are doing this, but the tap-mocha-reporter used by tap doesn't allow it.

https://www.npmjs.com/package/spec-xunit-file
https://www.npmjs.com/package/tap-xunit-file

**Comment by wking** [comment]
There's lots and lots of discussion in the analogous Mocha PR: mochajs/mocha#2184.  The main sticking point there seems to be [figuring out how to pass configuration options into multiple reporters][1].

[1]: https://github.com/mochajs/mocha/pull/2184#issuecomment-351556819

**Comment by isaacs** [comment]
The way that tap does reporters is really not very amenable to having multiple of them running at the same time, since a reporter can be an ink React component that takes over the whole terminal.

But, with tap 18, you can run `tap replay --reporter=whatever` to run the test output through a different reporter without actually running all the tests again.  Second process, so no issues figuring out how to specify which reporter gets which options, etc.

Check it out with `npm i tap@pre`. Be sure to read the [changelog](https://node-tap.org/changelog/#18.0) as a lot has changed.
