### ISSUE TITLE
Update coveralls dep to fix warning

### ISSUE THREAD

**Issue by OmgImAlexis** [tapjs/tapjs#337]
Coveralls relies on request which is using an outdated dep, once it's updated this repo should update it's Coveralls version.

Ref: https://github.com/nickmerwin/node-coveralls/issues/149

**Comment by isaacs** [comment]
Seems fine to me.  Patch welcome.

**Comment by metasean** [comment]
(a) Coveralls is still using `request`_4.5 years_ after this issue was posted!
(b) Coveralls most recent update was _more than a year ago_ (May 1, 2020).
(c) Coveralls has a fork that is removes `request` _and_ is being maintained slightly more actively (with their most recent update being Jan 18, 2021).

So, I'd love to see this issue re-opened with the goal of _replacing_ the unmaintained and clearly out-of-date `coveralls` library with `coveralls-next` (https://github.com/jtwebman/coveralls-next).
