### ISSUE TITLE
Does TAP_TIMEOUT always trump test timeouts?

### ISSUE THREAD

**Issue by djMax** [tapjs/tapjs#338]
I have some tests that hit external services that I know take a while - sometimes 60 seconds. The rest of my tests are not like that. So I want to set the test timeout IN the test, which I do with test('whatever', {timeout:60000}, async () => await doStuff());

But unless I pass TAP_TIMEOUT to the overall runner, these tests will fail. Is that the intended behavior? I see the timer set in test.js ~line 900, and that's the one that's killing my tests, and I don't see how I would reset that timeout. So that implies I have to both set a test timeout AND the runner arg?

**Comment by isaacs** [comment]
This is essentially the same problem as https://github.com/tapjs/node-tap/issues/316

The timeout that you pass in the test is how long that test will time out at.  But the runner itself will time out well before that happens.

For example, if you have a runner-level timeout of 1000ms, but then 100 tests each of which have a timeout of 1000ms, clearly the runner will time out before the child tests are all done.

If there were a way for the child stream to signal how much time it's going to need, there'd be another heuristic to go on, but you'd probably _still_ want a top-level control in many cases.  To make matters worse, there is no way currently to _override_ the presence of a top-level timeout in the runner, only to make it a very large number.

So, this is "by design", but I think this part of the design isn't particularly _good_, so that's not much of a justification.

Communicating timeouts up the test stack is tricky.  I think an ok workaround would be if there were a switch in the runner to turn off the top-level timer entirely.  Then you could do `--no-timeout` or something, and set the timeouts yourself however you like, in a more granular way.

**Comment by isaacs** [comment]
In v10, you'll be able to do `-T` or `--no-timeout` or set the `TAP_TIMEOUT` env to 0 in order to allow test files to just run as long as they need to.
