### ISSUE TITLE
Which test timed out?

### ISSUE THREAD

**Issue by nrstott** [tapjs/tapjs#34]
It would be very helpful if when receiving a timeout from a test, the test that timed out was reported.  Right now it is hard to determine which tests are timing out.

Output like this is common:

```
killing: test/router.test.js (timed out)
ok test/router.test.js .................................. 2/2
total ................................................... 2/3
```

**Comment by isaacs** [comment]
+1.  Maybe timeouts should just dump the stdout/stderr so that you can see what happened so far.  Also, it should be treated as a failure.

**Comment by nrstott** [comment]
That makes sense.  That would be very helpful.

**Comment by nrstott** [comment]
Oh, as an addendum, when a test timeout it seems to stop all future tests in that file from running.  I have discovered that I can find the test by looking at the 'total' and counting down to the test that is x asserts beyond the number passed in the order of the file.

**Comment by isaacs** [comment]
Yes, if the **process** times out, then it just forcibly kills it, so any additional tests in the file fail.  You can set a timeout per-test by doing something like:

``` javascript
test("timeout test", { timeout: 1000 }, function (t) {
  setTimeout(t.end.bind(t), 2000)
})
```

which will fail after 1000ms.

The issue of course is that the default `TAP_TIMEOUT` value that the runner uses is 30 seconds, and the default timeout config for each test is _also_ 30 seconds, so if a test times out, then it'll already have timed out the whole script.

Perhaps the TAP_TIMEOUT env should be higher, or the default test timeout should be lower?  I'm not sure.

In the meantime, you can set a lower timeout per-test, and run them with something like this:

```
TAP_TIMEOUT=120 tap slow.js
# or, even:
TAP_TIMEOUT=120 npm test
```

Really, though, I think reporting the failure properly will make this less of an issue, since you'll see the output and be able to tell how far it got.

**Comment by nrstott** [comment]
Thanks.

It's difficult to decide what default timeouts should be.  For the general use-case I would think that < 10 seconds would be good for a per test timeout.

I agree that making it report the failure properly will make this less of an issue.
