### ISSUE TITLE
RangeError: Invalid Array Length

### ISSUE THREAD

**Issue by gmaclennan** [tapjs/tapjs#340]
I get this error when running tests on travis-ci, but not when running locally. The tests all passed before using `tape test/*.js`.

```
 ---
  at:
    line: 175
    column: 11
    file: node_modules/tap-mocha-reporter/lib/reporters/classic.js
    function: doDiff
  stack: >
    doDiff (node_modules/tap-mocha-reporter/lib/reporters/classic.js:175:11)
    node_modules/tap-mocha-reporter/lib/reporters/classic.js:280:31
    Runner.<anonymous>
    (node_modules/tap-mocha-reporter/lib/reporters/classic.js:269:13)
    Parser.<anonymous> (node_modules/tap-mocha-reporter/lib/runner.js:207:18)
    Parser.emitResult
    (node_modules/tap-mocha-reporter/node_modules/tap-parser/index.js:550:8)
    Parser.startChild
    (node_modules/tap-mocha-reporter/node_modules/tap-parser/index.js:579:10)
    Parser.parseIndent
    (node_modules/tap-mocha-reporter/node_modules/tap-parser/index.js:894:12)
    Parser.parse
    (node_modules/tap-mocha-reporter/node_modules/tap-parser/index.js:730:10)
    Parser.write
    (node_modules/tap-mocha-reporter/node_modules/tap-parser/index.js:348:10)
    Runner.write (node_modules/tap-mocha-reporter/lib/runner.js:81:28)
    Formatter.write (node_modules/tap-mocha-reporter/index.js:68:28)
  test: TAP
  message: 'RangeError: Invalid array length'
  source: |
    ? new Array(width - '+++ found'.length + 1).join(' ')
```

Failing build:

https://travis-ci.org/digidem/osm-p2p-server/builds/193585629

**Comment by isaacs** [comment]
That's a really bizarre thing, for at least 2 reasons.

First, it would only try to generate a diff if the test is already failing.  It _looks_ like the issue is a timeout or something?

Second, if you look at the code in that part of the report generator, it would only be able to throw that error if `width - '+++ found'.length + 1` was less than 0, meaning effectively that the `width` var is less than `'+++ found'.length` or `9`.  That variable is set as the longest line in the patch it generated, up to `maxLength` which is the number of columns in the terminal minus 5 (to make for margins on the sides).

So the screen would have to be less than 14 characters wide to trigger this error.  Travis's terminal reports way more than that.

The other weird thing is that when I scrunch my terminal window down to 13 chars to trigger this, it doesn't actually print an error, it just skips the output of the test failure entirely, which isn't a great behavior, but is pretty different than what you're seeing here.

Anyway, it's easy enough to fix, so I'm gonna do that, but the mystery is really bananas.
