### ISSUE TITLE
combined coverage, multiple tests

### ISSUE THREAD

**Issue by tomdavidson** [tapjs/tapjs#341]
Does node-tap have the ability to combine coverage files? For example, say I have a coverage file from my integration tests then I run my unit tests with a watch - but the integration file coverage is overwritten.

I could config both sets of tests to use a different output file, but I would want to combine them to upload a report and my editor watches a single lcov file.

**Comment by isaacs** [comment]
So, I think the answer when you posted this issue was "no", but now it's "yes".

Add `--nyc-arg=--clean=false` and it won't delete the old test coverage files.

However, this also means that the coverage temp files aren't necessarily going to be overwritten, either, so if a test reduces coverage considerably, or if new uncovered code is added, you won't catch that.

This is something that I intend to address when building the `--watch` and `--only-changed` options, but I won't get to it for a while.  My thinking is that I can use the `--build-process-tree` option coming to nyc v14, and then look in the `.nyc_output/processinfo` folder to see if there's a previous process with the same args, and if so, delete it and all its coverage prior to running the test.

In fact, that should probably just be the default behavior in most cases, unless you're running `tap` with no args or `npm test`.  I'm not as confident on that, though.

**Comment by isaacs** [comment]
As of now in v13, it's safe to re-run tests with `--nyc-arg=--clean=false`.  That's a bit of a janky API surface at the moment, but I intend to make `--nyc-arg=--clean=false` the default when using a resumed test run with a `--save` file or when using `--watch` (when implemented).
