### ISSUE TITLE
Tests failing with count !== plan on travis

### ISSUE THREAD

**Issue by gmaclennan** [tapjs/tapjs#345]
Ok, here is another strange one. After the bizarreness of #340 was fixed, now I get an error of `count !== plan` on travis, but tests pass fine locally (ignoring the genuine failing test in `test/api/get_changes.test.js`). These tests calculate plan dynamically, which could be the source? Very bizarre that this should only fail on travis though. Failing build here: https://travis-ci.org/digidem/osm-p2p-server/builds/198236574

**Comment by zkat** [comment]
I'm getting a similar issue, except on AppVeyor: https://ci.appveyor.com/project/zkat/pacote/build/1.0.44/job/wi6qw167u264que2#L613

**Comment by isaacs** [comment]
@gmaclennan It looks like your tests are quitting the process after the first test without outputting a plan.  Any chance you could add `-Rtap` to the test command (or set `TAP=1` in the environment) and share the output?

@zkat Since AppVeyor shows the TAP, that makes it a little easier to see what's going on, thanks.  It looks like it's also putting that last `'does not insert plain manifests into the cache'` TODO test ahead of the `falls back to registry if cache entry missing`, which is another clue perhaps.

Does this happen regularly?  Can you get it to occur locally?

**Comment by isaacs** [comment]
@zkat Can you add this to your https://github.com/zkat/pacote/blob/latest/test/registry.manifest.cache.js file?

```javascript
var signalExit = require('signal-exit')
signalExit(function (code, signal) {
  console.error('SE code=%j signal=%j process.exitCode=%j', code, signal, process.exitCode)
})
process.on('exit', function (code) {
  console.error('PE code=%j process.exitCode=%j', code, process.exitCode)
})
process.reallyExit = function (original) { return function (code) {
  console.error('reallyExit code=%j process.exitCode=%j', code, process.exitCode)
  return original.apply(this, arguments)
}}(process.reallyExit)
```

The only way that I can reproduce this is by forcibly throwing a `process.reallyExit()` in there.  Somehow, the process is terminating without passing through either the signal handlers or `process.on('exit')` handler.

**Comment by zkat** [comment]
@isaacs 

It didn't reproduce at first, so I changed things to `console.log`, but in retrospect I think that was just a hiccup. Here's a super helpful test run that actually has BOTH the non-failing race with your output AND the failure case, which doesn't seem to output tour debut info:

https://ci.appveyor.com/project/zkat/pacote/build/1.0.60

**Comment by gmaclennan** [comment]
@isaacs thanks so much for following up on this. I see from adding the `-Rtap` option that this is a timeout error. This reminded me that on Travis, differently than locally, we have a random delay on leveldb requests, to better catch race conditions. I think this was running on `tape` ok because `tape` has a timeout per-test, not per-file. The `bbox_order.js` test was taking 35 seconds to run: https://travis-ci.org/digidem/osm-p2p-server/jobs/201580655#L1395

All fixed now by removing removing the timeout.

**Comment by isaacs** [comment]
Oh!  Another way to get this to happen is to do something like this:

```js
process.on('exit', function (code) {
  process.exit(code)
})
```

If a `process.on('exit')` handler is registered before tap's `process.on('exit')` handler, and it calls `process.exit()`, then that'll detect that `'exit'` has already been emitted, and jump straight to `process.reallyExit()`.

@gmaclennan Huh. In that case, it should've been printing some better output about the timeout failing, because the child process would get a `SIGTERM` instead of exiting normally.  Maybe that's a different issue, though?

**Comment by isaacs** [comment]
@zkat Can you try putting `"tap": "tapjs/node-tap#stdout-dejank"` in your package.json and see if that makes a difference?  I'm trying to work around the case where maybe it's failing because stdout doesn't finish emitting by the time the `close` event happens.

**Comment by isaacs** [comment]
This should no longer be mysterious in 10.2.  A problem arises when a `teardown` handler throws an error, and when a root autoend is triggered while a test is unfinished.  Now both cases are handled rather than the errors being swallowed.  Can't guarantee it'll make the tests start passing, but they'll fail less mysteriously :)
