### ISSUE TITLE
Inconsistent uncaughtException handling

### ISSUE THREAD

**Issue by shyiko** [tapjs/tapjs#346]
```
$ for f in test/*.test.js; do printf "$f\n\n"; cat $f | nl -bn; echo; done
test/a.test.js

       const t = require('tap')
       t.test(() => {
         throw new Error('err')
       })

test/b.test.js

       const t = require('tap')
       throw new Error('err')

test/c.test.js

       const t = require('tap')
       process.on('uncaughtException', t.threw)
       throw new Error('err')

$ tap test/*.test.js
test/a.test.js .<reducted>/test/b.test.js:2
throw new Error('err')
^

Error: err
    at Object.<anonymous> (<reducted>/test/b.test.js:2:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
test/a.test.js ........................................ 0/1
  (unnamed test)
  not ok err
    stack: |
      Test.t.test (test/a.test.js:3:9)
      Object.<anonymous> (test/a.test.js:2:3)
    at:
      line: 3
      column: 9
      file: test/a.test.js
      function: Test.t.test
    test: (unnamed test)
    source: |
      throw new Error('err')

test/b.test.js ........................................ 0/1
  not ok test/b.test.js
    timeout: 30000
    file: test/b.test.js
    command: <reducted>/.nvm/versions/node/v6.9.1/bin/node
    args:
      - test/b.test.js
    cwd: <reducted>
    exitCode: 1

test/c.test.js ........................................ 0/1
  not ok err
    at:
      line: 3
      column: 7
      file: test/c.test.js
      function: Object.<anonymous>
    stack: |
      Object.<anonymous> (test/c.test.js:3:7)
    test: TAP
    source: |
      throw new Error('err')

total ................................................. 0/3
  

  0 passing (518.773ms)
  3 failing
```

In the example above `b.test.js` is reported as timed out with actual error logged before the tests results. Shouldn't all three cases yield the same result?

**Comment by isaacs** [comment]
So, it's not reporting that it has timed out, but just that it has a timeout value set in its options.

What's happening is that the error is being thrown as normal, but TAP never gets its hooks in it.  Then the runner cli sees the exit code and says "Whatever went wrong, i don't know, but we're exiting with a non-zero exit code, so that's a failure."

If you run the script directly, you see this:

```
$ node e.js
/Users/isaacs/dev/js/tap/e.js:2
throw new Error('err')
^

Error: err
    at Object.<anonymous> (/Users/isaacs/dev/js/tap/e.js:2:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

If there's any TAP output at all that's been produced, it hooks into the error event to catch it, and you get this:

```
$ cat e.js
const t = require('tap')
t.comment('some output')
throw new Error('err')

$ node e.js
TAP version 13
# some output
not ok 1 - err
  ---
  at:
    line: 3
    column: 7
    file: e.js
    function: Object.<anonymous>
  stack: |
    Object.<anonymous> (e.js:3:7)
  test: TAP
  source: |
    throw new Error('err')
  ...

1..1
# failed 1 test
# time=19.825ms
```

The reason for this is that you might want to extend tap by doing `var Test = require('tap').Test; util.extends(MyThing, Test)`, and then you wouldn't want node-tap to hijack the output.

I think probably the best solution would be to put a handler on `process.on('uncaughtException')` to say "If it hasn't piped yet, then start doing the TAP thing now"?

**Comment by shyiko** [comment]
> The reason for this is that you might want to extend tap by doing var Test = require('tap').Test; util.extends(MyThing, Test), and then you wouldn't want node-tap to hijack the output.
 
Makes perfect sense. 

What about introducing something like

```
const tap = require('tap')
process.on('uncaughtException', tap.threw).on('unhandledRejection', tap.threw)
module.exports = tap
```

and making it available through `require('tap/hijack')` or `require('tap').hijack()` or even `require('tap-hijack')`? One could of course just save these 3 lines of code as `tap-hijack.js` and `require` them instead of `tap` directly (this is pretty much what I'm doing right now) but I wonder what would be your choice/recommendation here?

Thank you.

**Comment by isaacs** [comment]
I think this is "working as designed" currently.  I don't see any way to provide the behavior automatically without causing issues.

I'd accept a patch to add a `tap.handleErrors()` method (which would be invoked by default in `TAP.prototype.push` so that it's set if any output is generated and auto-piped to stdout).
