### ISSUE TITLE
support snapshot testing

### ISSUE THREAD

**Issue by phra** [tapjs/tapjs#368]
hi,

it would be nice to have the ability to [test for snapshots changes](https://facebook.github.io/jest/docs/snapshot-testing.html#content) like [jest](https://github.com/facebook/jest).
what do you think about it?

**Comment by isaacs** [comment]
Hm.  I use this pattern a lot, ([eg](https://github.com/tapjs/node-tap/tree/master/test/test)) but I'm not sure it's ideal to have the test framework do it.  I can see how it'd be handy, though, so you don't have to write a generate-fixtures function for each repo.  But if you need to strip out system-specific stuff, or compare objects (like I do with the yaml objects in TAP output), then it's not clear how to go about it and still get line-by-line for the other stuff.  It seems like jest can do this because they assume that they're dealing with JSX/HTML output from react, so it's clear what to optimize for.

**Comment by phra** [comment]
i can describe a common use case for me:
- i have a class that does something, for example calculation on some data
- i usually create unit tests to check the correctness of the implementation so i check that every single result is correct
- when i write the e2e tests i don't want to repeat all the assertions made in the unit tests, so i find very useful the ability to check the result against a snapshot (this because the implementation is already being tested in the unit test, so no need to test it again in the e2e)

btw if you are minding how jest serialize values in order to save them in the snapshot, it's using [pretty-format](https://github.com/facebook/jest/tree/master/packages/pretty-format)

**Comment by isaacs** [comment]
@phra Check out [tapshot](https://www.npmjs.com/package/tapshot), might give you what you need.

**Comment by phra** [comment]
thanks @isaacs ! if it's working well i suggest to cite it in the readme so people can easily discover it!

**Comment by jaydenseric** [comment]
Is this supported now; can the issue be closed? https://www.node-tap.org/snapshots

**Comment by isaacs** [comment]
It is!  Thanks for the nudge.
