### ISSUE TITLE
tap --coverage-report=lcov creates error

### ISSUE THREAD

**Issue by inspiraller** [tapjs/tapjs#369]
This is my package.json file

```javascript
{
  "name": "tape-test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "node_modules/.bin/tape tests/*.js | tap-spec --coverage && npm run testxml && npm run coverage",
    "testxml": "node_modules/.bin/tape tests/*.js | tap-xunit --package=\"MyCompany.MyTool\" > test_results/results.xml",
    "coverage": "tap --coverage-report=lcov && codecov"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "codecov": "^2.1.0",
    "tap": "^10.3.2",
    "tap-spec": "^4.1.1",
    "tap-xunit": "^1.7.0",
    "tape": "^4.6.3"
  }
}
```

When I run:
npm run coverage

I get this error
```
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'c:\baps\cwide\tape-unittesting\.nyc_output'
```

**Comment by isaacs** [comment]
You're running `tap` with a coverage report argument, but no files.  In that case, it assumes that you just want to take a _previous_ coverage run, and produce a new report.

Granted, the error message sucks.  It should tell you this, and doesn't.  I consider that a bug.

But the overall behavior is correct otherwise.

Try this for your script instead:

```
tap --coverage-report=lcov tests/*.js && codecov
```

The tap executable can drive any tests that output TAP format, whether they use tape or anything else.  But it has to have some tests to generate coverage with before it can create a report.

**Comment by isaacs** [comment]
Will be fixed on next v13 release. 66cfec2d710a754f0f19baa10111ecd52aaf31cb
