### ISSUE TITLE
What do you think of the .failing modifier?

### ISSUE THREAD

**Issue by brunoscopelliti** [tapjs/tapjs#404]
From ava's readme.

> You can use the `.failing` modifier to document issues with your code that need to be fixed. Failing tests are run just like normal ones, but they are expected to fail, and will not break your build when they do. If a test marked as failing actually passes, it will be reported as an error and fail the build with a helpful message instructing you to remove the .failing modifier.

What do you think about having something similar in tapjs?

```js
test.failing('demonstrate some bug', t => {
  t.fail() // Test will count as passed
})
```

I've not found anything related; sorry if it was asked before.

**Comment by isaacs** [comment]
I'd be open to adding this in v11.

**Comment by brunoscopelliti** [comment]
Is it something you wish to  (or eventually will) work on personally?

**Comment by isaacs** [comment]
Eventually, probably.  If you want it sooner, you could take a crack at it.

Here's how I'd approach it:

1. Add a boolean option like `skip` or `todo` that can be passed in, called `expectFail` (or something).  So, you could do `t.test('demo a bug', { expectFail: true }, t => { t.fail(); t.end() })`.
2. Run the test as normal.
3. In the `Test` class in `lib/test.js`, when a child test finishes, we call `this.printResult(p.passing(), ...)` in 2 places.  In both of those cases, check if `p.options.expectFail` is set, then we should _fail_ and append "expected test failure" to the name.  So, instead of `this.printResult(p.passing(), p.name, p.options, true)`, we'd do something like `const pok = p.options.expectFail ? !p.passing() : p.passing(); if (p.expectFail && !pok) p.name += ' expect test failure'; this.printResult(pok, p.name, p.options, true);`  (Probably add a new method for this, `this.subTestPoint(p)` or something.)
4. Add `Test.prototype.failing` like `Test.prototype.skip` in `lib/test.js`, which forces `options.expectFail = true`.

**Comment by isaacs** [comment]
Might be better to just call it `options.failing` rather than `expectFail`.  idk.  Probably better to match the sugar API.

**Comment by brunoscopelliti** [comment]
Thank you very much for the detailed explanation... I'll definitely give it a try.

**Comment by brunoscopelliti** [comment]
Hi @isaacs 

I've spent a few time exploring node-tap internals.
I've tryed following your advice; but things didn't work as I expected. In particular in this case:

```js
test('this is going to fail', t => {
    t.fail('boom')
    t.end()
})
```

we still have a not-zero exit code.

```js
if (tap.results && !tap.results.ok && code === 0) {
    process.exitCode = 1
    if (process.version.match(/^v0\.(10|[0-9])\./))
        process.exit(code)
}
```

If I've understood correctly `tap.results` is written by `tap-parser` on the basis of the TAP-formatted output of the test. It appears to me that in order to exit with code 0, we have to extend `TestPoint`, and `tap-parser` as well. I've thought something like:

```
TAP version 13
# Subtest: first
    ok 1 - yeah
    not ok 2 - boom # EXPECTED
    1..2
ok 1 - first

# Subtest: second
    ok 1 - wow
    1..1
ok 2 - second

1..2
```

Any thoughts?

**Comment by isaacs** [comment]
Thinking on this a bit more now that I'm picking up this repo again and triaging issues and ideas...

The problem is that the _parser_ will treat a `not ok` as a failure, even if the enclosing TAP output test block ends with `ok`.

A more clear way to do this would really be a `# FAILING` indicator that `tap-parser` knows how to interpret.  It could interpret the test as a known failure, and if it _isn't_ failing, report that as a failure.  Then all that node-tap has to do is put the indicator on like it does for `# TODO` and `# SKIP`, and keep relying on the parser's report as to the passing-ness of the test as a whole.

**Comment by isaacs** [comment]
There's no reasonable way to implement this in the TAP protocol, and the more I really think about it, the more I think this is just a terrible idea.

Mark the test as `todo` if you'll do it later and want it skipped. But a failing test _should_ break your build, that's the point. If you don't want it to break your build, mark it as `todo` and fix it when you can, so that it won't be run. The last thing you want is to think that you have full coverage of your code, but in fact, you're only covering it with a test that doesn't actually succeed.

No known failures! Fix the test, skip the test, or delete the test.
