### ISSUE TITLE
Promises documentation section

### ISSUE THREAD

**Issue by vitoloper** [tapjs/tapjs#418]
The first example [here](http://www.node-tap.org/promises/) shows how to chain Promises in tests. However, the subtest 'check other promise thing' doesn't seem to pass because in the last `t.equal `the parameter `otherPromiseResult` doesn't hold the resolved value of `makeSomeOtherPromise()` but it holds the t object instead.

```js
'use strict'

var t = require('tap')

// Promises definition

var getSomeThing = function () {
  return new Promise(function (resolve, reject) {
    resolve({foo: 'bar'})
  })
}

var getTwoThings = function () {
  return new Promise(function (resolve, reject) {
    resolve([1, 2])
  })
}

var makeSomeOtherPromise = function () {
  return new Promise(function (resolve, reject) {
    resolve(7)
  })
}

// Tests

var t = require('tap')
t.test('get thing', function (t) {
  return getSomeThing().then(function (result) {
    return t.test('check result', function (t) {
      t.equal(result.foo, 'bar')
      t.end()
    })
  })
}).then(function (t) {
  return getTwoThings().then(function (things) {
    return t.test('the things', function (t) {
      t.equal(things.length, 2)
      return makeSomeOtherPromise()
    })
  }).then(function (otherPromiseResult) {
    return t.test('check other promise thing', function (t) {
      t.equal(otherPromiseResult, 7, 'it should be seven')
      t.end()
    })
  })
}).catch(t.threw)

```
If there's a mistake, what's the correct way to write tests with promise chaining? Thank you.

**Comment by isaacs** [comment]
Oh, yeah, that is a mistake.  The promise flows in this doc were written to be intentionally convoluted.  Either the `otherPromiseResult` function should be chained off of `makeOtherPromise()` call, or tests whose functions return a promise should resolve their promise to that value rather than to themselves.  That'd be a breaking change, but I doubt if too many users are depending on tests returning themselves in the promise result.

**Comment by isaacs** [comment]
d0c56b1
