### ISSUE TITLE
Object snapshots differ between Node.js v8.5 and v10.3

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#450]
For some reason, object snapshots set using Node.js v10.3 can fail when running the tests in Node.js v8.5.

Here is an example: https://travis-ci.org/jaydenseric/graphql-api-koa/jobs/388186876#L2872

<img width="601" alt="screen shot 2018-06-05 at 7 41 54 pm" src="https://user-images.githubusercontent.com/1754873/40968309-99ab228e-68f8-11e8-9743-4fee6d398e46.png">

It appears that longer properties drop onto an indented new line in more recent Node.js versions.

**Comment by isaacs** [comment]
Indeed, it looks like this changed.

Probably the best approach would be to just use a specific object serialization rather than relying on `util.inspect` in node core.  Patch welcome, or I can probably get to it at some point in the next few weeks.

In the meantime, you could work around this by serializing to JSON or something first, I guess.  That's klunky, but it'd maybe be an ok fast temp fix.

**Comment by jaydenseric** [comment]
> The output of `util.inspect` may change at any time and should not be depended upon programmatically.
> — https://nodejs.org/api/util.html#util_util_inspect_object_options

It might be a good idea to stop using it, and perhaps use `JSON.stringify` instead.

Node.js v9.9.0 introduced a new `util.inspect` `compact` option, which defaults to `true`. This puts short properties, `{` and `[` all on one line.

For better diffs, each property should be on a seperate line. I suggest setting the `compact` option with a `false` value [here](https://github.com/tapjs/node-tap/blob/v12.0.1/lib/test.js#L989). This won't prevent old and new Node.js from snapshotting differently, but it is a better format and probably will be more consistent moving forwards. I'm not sure if Node.js < v9.9.0 will error at the unknown option though, or quietly ignore it.

**Comment by focusaurus** [comment]
This is only loosely related but I was in here searching to see where the object diffs come from when `t.match(found, wanted)` fails and I guess it's `util.inspect`, but it seems like it has `depth: Infinity` set. Isaac, would you ever consider a smaller limit there? I often accidentally use `res` instead of `res.body` and the output is enormous, fills my terminal scrollback buffer, and makes the rest of the output unreachable.

**Comment by isaacs** [comment]
@focusaurus That is 100% a different issue, can you please post a new bug for that?  Thanks.

**Comment by isaacs** [comment]
Done in v13.
