### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by davidbonnet** [tapjs/tapjs#457]
`node-tap` performs very badly in this benchmark, even with its latest version (12.0.1), which is astonishing, especially when compared to `tape`:
https://github.com/vitalets/js-testrunners-bench

Is there any issue with how the benchmark is designed?

The latest run:
https://vitalets.github.io/js-testrunners-bench/index.html
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/297345/41767248-6b8e6424-7609-11e8-9276-dbc7bccc6309.png">

**Comment by jsardev** [comment]
Don't know what were the changes in the versions, but the benchmark is based on `tap@10.3.3`, while we had already 2 major version bumps.

Additionally, the tests are being run with `mochaGlobals`, not pure `tap` - also don't know if it provides any performance overhead.

**Comment by isaacs** [comment]
So, there are legit perf issues, but also this benchmark has some problems.

The biggest performance issue, and the reason why mocha and friends crush tap, is that tap uses a child process for each test file, rather than loading them with `require()`.

Tap's approach has a couple of benefits:

1. Tests are 100% isolated from one another via a process boundary at the OS level.
2. The test is the "main script", meaning that running `node test.js` runs your test in the identical way as `tap test.js`.

That's maybe somewhat academic-sounding, but I've run into many cases where a test passes or fails only in the test runner, or only when run in a specific order with other tests, and it's hecka annoying to debug.

The other source of slowdown is using nyc for coverage, which adds another process layer as well as some CPU work with istanbul.

The approach I'm exploring is using node's worker_threads (introduced in v10.5, flag removed in v11) with a bit of fudging to make the script "feel" like it's the main module.  It's going to be experimental for a while, but it should remove the ~100ms for each child process.

In addition to this, I intend to move from nyc to [c8](https://www.github.com/bcoe/c8) fairly shortly.  (Certainly for tap v13.)  That'll move the coverage instrumentation to the v8 internals, making coverage much much faster.  At that time, we can even consider enabling coverage by default, since it won't be doing funky things with code transpiling and child processes.

As mentioned, the benchmark is using mochaGlobals, which is kind of a hack, and not really ideal for prime time.  I don't know if that's causing any perf issues (it shouldn't?) but it probably isn't helping.

The bigger issue is just relying on the "default" bench setup here.  It's loading 250 files _which do nothing_.  For a module loading tests with require(), that means it's 250 read file ops.  For tap, using child processes, it's 250 _full node invocations_.  And since there's no other overhead, that's what it's measuring.  (And 250 test files is... an awful lot.)

If you set the options to use async tests, especially with a delay, then tap still lags behind some others (again, arbitrary process table stakes of 100ms per test file), but the numbers get a lot closer.

So, tap isn't just throwing performance away.  That speed is being _spent_ on something that (I believe at least) is a very good deal.  However, it's about to get a whole lot faster, which I'm excited about, because I do run some rather long test suites from time to time.

**Comment by davidbonnet** [comment]
Thanks @isaacs for providing the insights and future plans to tackle this.
Worker threads are a great idea. Also, I haven't checked, but C8 [might not provide the expected speed bump](https://github.com/bcoe/c8/issues/3).
Perhaps, another way could be to allow `tap` to run on a single process? …for the adventurous?

**Comment by Fishrock123** [comment]
IMO any test framework benchmark that does not also include parallelism is not very useful.

Tests on one of our internal projects take ~35s with Tape and ~5s with Tap (parallelized).

**Comment by isaacs** [comment]
@davidbonnet I'm presuming that we'll still lose out on v8 optimizations (which, for anything other than microbenchmarks of empty functions, is not usually _that_ big a deal), but it will definitely save having to transpile the code in the first place (varies wildly), run a second child proc for `--cov` to restart the suite in nyc (~100-200ms), and does coverage in a way that is going to work for worker threads.

So, yeah, not the nail in the coffin that workers is, but it is a prereq, and a much safer approach than transpiling.  And at least it _can_ be optimized by v8 eventually.

**Comment by isaacs** [comment]
> Perhaps, another way could be to allow tap to run on a single process? …for the adventurous?

That is exactly what workers will do 😄

(But in a way that doesn't sacrifice parallelism or separation.)

**Comment by isaacs** [comment]
Turns out that workers are about as slow as subprocs, since most of the time spent is in spinning up the Node.js environment.  Until that can be somehow shared between isolates, I'm not sure that this is worthwhile.

You can play around with the `require-inject-experimental` branch, which lets you do `t.require('/path/to/foo.js')`, and you can set `TAP_FAST=1` in the environment to load tests that way.  It's... pretty janky if you do anything even remotely off the beaten path.

**Comment by pke** [comment]
I recently used mocha again in my eslint plugin (its required) and its blazingly fast. It runs the tests in under 1ms while tap needs over 4s. Watching is also much faster with mocha, I don't know why tap needs so long to detect changed files. Or does it have an arbitrary delay to catch changes across multiple files?

But at least I know now where the time is spent in tap. However, do you still think about providing an option to run all tests sequential in one node process for the ones who want to run their tests fast?
