### ISSUE TITLE
The spec reporter doesn't print out failure comparisons

### ISSUE THREAD

**Issue by Fishrock123** [tapjs/tapjs#473]
My team prefers the spec reporter (due to familiarity), however, when a failure occurs, we keep needing to switch to the default reporter, since the spec reporter doesn't seem to output any failure comparison.

e.g. when using `t.match()`, no `found:` / `expected:` output is printed.

**Comment by isaacs** [comment]
Interesting.  Yeah, it uses the mocha-style colored diffs (which are not as accessible, what whatever), but `t.match()` doesn't output a diff, since patterns don't exactly match their results anyway.

```js
const t = require('tap')
t.test('a thing', t => {
  t.match({ foo: 'bar' }, { foo: 'baz', bar: 'boz' })
  t.equal('foobar', 'fooblz')
  t.same({ foo: 'bar' }, { foo: 'baz', bar: 'boz' })
  t.end()
})
```

![screenshot 2018-11-08 11 03 35](https://user-images.githubusercontent.com/9287/48221252-6e25ff80-e346-11e8-8483-bb05242db883.png)

vs

![screenshot 2018-11-08 11 04 03](https://user-images.githubusercontent.com/9287/48221261-77af6780-e346-11e8-92f7-a7a792fb6323.png)

Maybe it'd be good to just print out the object and pattern like it does for the Classic reporter?

**Comment by Fishrock123** [comment]
Unless you have a better suggestion, I have been switching to the classic reporter each time this happens. Any output is better than none.

(As an aside, I wish the match diff had color, heh.)

**Comment by isaacs** [comment]
Yeah, if it was presented as a diff, then that'd be misleading, though.  For example, `{foo:/^b[ar]+$/}` is a match to `{foo:'barrrr'}` and `{foo:'brararra'}`, but a diff against `{foo:'barb'}` will not be super helpful.

**Comment by onetom** [comment]
I just thought to give `node-tap` a try after reading https://remysharp.com/2016/02/08/testing-tape-vs-tap and because I was encountering useless async stack traces.
In about 5 minutes I hit this very same issue...

I'm using `jest` and very often I reach for the `.toMatchObject` matcher which is the rough equivalent of `t.match`. I never use regexes in the pattern I would like to match, so I find it extremely useful that the failure is presented as a colored diff.

I'm a bit surprised by the screenshot, because it's not showing any stack trace :/
My output looks like this:
```
⋊> npx tap test/demo-flow.js -Rspec

test/demo-flow.js
  xxx
    1) should match pattern provided


  0 passing (251.311ms)
  1 failing

  1) test/demo-flow.js xxx should match pattern provided:
     Error: should match pattern provided
      at Test.t.test (test/demo-flow.js:18:7)
      at Object.<anonymous> (test/demo-flow.js:16:3)
```

I would like to point out that in this output stack-trace lines are prefixed with an `at` word, which makes JetBrains' IDEs to turn the file reference in parenthesis into hyperlinks, which open those files at the mentioned locations.
The classic output doesn't do this, so switching to it from the `spec` reported has a slight drawback...

```
⋊> npx tap test/demo-flow.js -Rclassic
test/demo-flow.js ..................................... 0/1
  xxx
  not ok should match pattern provided
    found:
      a: 1
      b: 2
      c:
        d: e
    pattern:
      b: 12
    at:
      line: 18
      column: 7
      file: test/demo-flow.js
      type: Test
      function: t.test
    stack: |
      Test.t.test (test/demo-flow.js:18:7)
      Object.<anonymous> (test/demo-flow.js:16:3)
    source: |
      t.match(actual, {b: 12})

total ................................................. 0/1
  

  0 passing (247.415ms)
  1 failing
```

I hacked it around temporarily by transforming the reporter's output in the `test` script in `package.json`, but then I can't easily append extra parameters to the `tap` runner... :(

```
  "scripts": {
    "test": "tap test/*.js -Rclassic | awk '/\\(.+:.+:.+\\)/{print \"at \"$0;next} 1'",
  },
```

(the ouput is a bit ugly, becaus i've just appended the `at` to the very beginning of the line, but at least the script is not too long)

**Comment by onetom** [comment]
Shouldn't this be reported at https://github.com/tapjs/tap-mocha-reporter though?

**Comment by isaacs** [comment]
Landed in v13 using the tcompare module.
