### ISSUE TITLE
Change duration color in "spec" reporter even if > 100ms

### ISSUE THREAD

**Issue by ibc** [tapjs/tapjs#476]
By running `tap --bail --color --reporter=spec TEST_FILE`, the duration of any test taking more than 100ms is displayed in red.

Is it possible to override such a 100ms limit to display them in green? In my case it's just ok as the test itself is supposed to take longer than 100ms.

Couldn't find anything in the command line options to change that.

**Comment by isaacs** [comment]
Yeah, there's no way to do that.  I think this part of the program needs a major overhaul, so I'm adding this issue to the set of concerns.

Thanks!

**Comment by isaacs** [comment]
That reporter is no longer actively supported, though it does still work just fine as a CLI reporter because the TAP protocol is just cool and stable and streamy like that.

```
tap -R tap-mocha-reporter -r spec
```

A proper ink-based spec type reporter would be great, but personally, I usually find spec super noisy and not very useful, so I won't be likely to write it myself any time soon.
