### ISSUE TITLE
[Feature Request] replicate --onlyChanged behavior from jest

### ISSUE THREAD

**Issue by andykais** [tapjs/tapjs#486]
I have done some research, and it should be fairly straightforward to find the list of tests which need to run to test all the new changes in a git repo branch. In its most basic sense, this flag will just filter the test glob. The basic idea is:

- `testFiles = list{files matching test glob}`
- `changedFiles = list{unstaged + files with diff against <branch>}`
- run recursively [find-imports](https://github.com/cheton/find-imports) on each of `testFiles`
- create changed dependencies object `{ [filename]: isChanged }`
- filter `testFiles`, if one of its dependencies has changed or is untracked, include it
- pass that list of files to tap

If there is interest in this, I can start working on a PR but I want to see if it could be accepted first.

**Comment by isaacs** [comment]
It seems like a nice idea.  It's not too far off conceptually from `--save=<file>` to re-run failures (and then run the whole test suite once the known failures are passing, to see if there are new failures).

For the implementation, I'd recommend the following off the top of my head:

1. Put the change-filtering logic in a new standalone file, like `lib/changes-filter.js`.  This should export a function that takes a list of files, and does the filtering to find which ones have a delta from the git HEAD (or a supplied git head).
2. If you run and parse git output, make sure to run it in `--porcelain` mode to avoid personalization, internationalization, and other issues that will confound the output and make it harder to parse.
3. Add a new test in `tests/changes-filter.js` (ie, match the module file name, but `s/lib/test/`).  When that file is run directly, it should provide 100% coverage for the lib module.  To check this, run `node bin/run.js --nyc-arg=--include=lib/changes-filter.js --100 test/changes-filter.js`
4. The arg should be all-lowercase.  Ie, `--only-changes` instead of `--onlyChanges`, or even `--changed` or `--diff`?  The shorthand `-o` is already used for `--output-file=<file>` and `-O` is used for `--only`, so I'm not sure what the best shorthand should be here.  Maybe `-n` or `-d`?
5. If there are no changed files, it should run the whole test suite.  This makes it suitable for the use case where it's the default test script, so you can checkout, test, [change, test, change, test...], commit, test.

If any of that seems off to you, definitely let me know!  I'd be excited to see this.

**Comment by isaacs** [comment]
This is now in the latest v13 release.
