### ISSUE TITLE
console.log writes output in incorrect order when long string with newlines

### ISSUE THREAD

**Issue by baerrach** [tapjs/tapjs#511]

**Comment by baerrach** [comment]
Run `node bin/run.js test/console-log-with-tap.js` and you will see output like

`"steps": [
  {
  },
  {
  },
  {
  },
  {
  },
  {
  },
  {
  }
]
`

Run `node test/console-log-with-node.js` and you will see the output JSON.stringify'ed properly with no incorrect interleaving of console.log.

Sorry I can't actually write a working test, this was the best I could do.

**Comment by isaacs** [comment]
Yeah, I see what's going on here.  You're outputting this to `stdout` using `console.log`, which is where the test output is supposed to go.  The parser does its best to pass non-TAP data through untouched, but it's interpreting the 4-space indented data as a potential child test, and then when that doesn't parse properly, kicking it out as non-TAP data, but by that time, some other unambiguously non-TAP data was already emitted.

It'd probably be good to make it robust against this kind of confusion.  But in the meantime, if you use `console.error()` instead of `console.log()`, it'll work as expected.
