### ISSUE TITLE
Feature req: add a context object for tests

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#513]
https://twitter.com/izs/status/1101143670290472961

Ava supplies a context object to subtests. This aids with reducing shared state amongst subtests. See https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#test-context for a description of their feature.

It would be great if Tap 13 also supported this feature.

**Comment by isaacs** [comment]
So, matching the behavior exactly is a little bit tricky, since `beforeEach` and `afterEach` don't get a Test object, they get a callback (or can return a Promise).  `beforeEach` and `afterEach` functions are called in the this-context of the `t` object that they're coming before or after, but that's considered a bit uncool to rely on these days, since it means you have to use non-arrow functions.

That being said, it wouldn't be hard to put a `context` object on Test objects, and then clone it for all the child tests.  I'll do that.  Then if you look at `t.context` in a child test (or `this.context` in a beforEach/afterEach), it'll be there.

**Comment by isaacs** [comment]
How would you feel about just copying ava's beforeEach/afterEach API surface?

The one that tap has today is inspired more by Mocha (ie, it takes a cb and can return a promise).  That sort of made sense at the time, but I rather like Ava's approach of just passing in a `t` object.

What's unclear is whether you'd do `t.end()` on it?  Since a beforeEach isn't really a "test", this is a bit weird.

Also, it's a pretty significant breaking API change.  Even though v13 _is_ a major, I've tried to make the changes required to actual test files as minimal as possible.  (Ie, you should be able to just re-generate any snapshots, and use pretty much the same exact test files.)

Another way to thread the needle and make it backwards compatible would be to do an API like this:

```js
t.beforeEach((done, t) => {
  // call done() when done (or return a promise)
  // t is the test that we are "before"
  t.context.foo = t.name
  done()
})

t.test('bar', t => {
  t.equal(t.context.foo, 'bar')
  t.end()
})

t.test('baz', t => {
  t.equal(t.context.foo, 'baz')
  t.end()
})
```

**Comment by jsumners** [comment]
I really don't know enough about the feature to make a judgement on that proposal. Hopefully my colleague @Greg-GB will chime in to give his opinion.

I did not envision it being a required change to test files but an optional one. If you do not have a need for a context in your tests then your test files should not have to change when the feature is available. But if you do need a context then you would be able to refactor your tests to use it.

**Comment by Greg-GB** [comment]
The return `done`/`promise` approach sounds like a good option to me. I assume its required for one of those two options to be present in the `beforeEach`/`afterEach`? If one of those two options are not present, could the `beforeEach`/`afterEach` implicitly return a promise so this feature is sort of optional? Might be a little hacky.

**Comment by isaacs** [comment]
Basically, I'd call the beforeEach/afterEach function as `fn.call(testObject, callback, testObject)`.  So, if you were previously relying on `this` being the test, then it'll still work.  And if you were expecting a single `done()` argument, then it'll still work.  And if you return a promise (or, if it's an `async` function), it'll keep doing the same thing.  But the `t` object is there as a second argument so you can assign `t.context` if you like.  (`this.context` would also work, but it means you have to use "real" functions, not `=>`.)

**Comment by jsumners** [comment]
I am not opposed to real functions.

**Comment by isaacs** [comment]
@jsumners that makes 1 of us ;P

**Comment by isaacs** [comment]
Done in v13.

**Comment by jsumners** [comment]
🎉
