### ISSUE TITLE
Question Regarding TAP Stance on backward compatibility constraints imposed by other packages

### ISSUE THREAD

**Issue by infintesimal** [tapjs/tapjs#514]
Hi, wonder workers of tap. I love your package. Thanks for all the hard work on it.
I am dependent on a package (browserify) that insists (for its own understandable reasons) on being back-compatible to node v 0.12 and node v 0.10; so the browserify team points at tap 10.7.2.
This in turns toggles npm audit security warnings.
I, being too smart by half, forked browserify and set out to fix the security warnings. So I pointed by fork at tap 12.4.x and modified some of their testing code and all was good with the world, that is, until I hit their Travis integration, which when exercising node 0.12 and 0.10 dislikes the 'use strict' and subsequent const declarations. Is there any will to support a node 0.12 and node 0.10 compatible version of run.js? If so, what would that look like for you? (btw tap 12.5.3 also doesn't work with node v4 b/c of esm but that's a different matter). I am happy to code any such solution up (if it exists), but also would wholly understand if you have zero appetite for such contortions. Just drop me a comment please to let me know how you think about it. My current issue might be fixable by stepping into the triggers of the audit warnings, which are (in 10.7.2):
```
tap>coveralls>request>hawk>boom>hoek
tap>coveralls>request>hawk>cryptiles>boom>hoek
tap>coveralls>request>hawk>hoek
tap>coveralls>request>hawk>sntp>hoek
tap>coveralls>request>tunnel-agent
tap>nyc>istanbul-lib-instrument>babel-generator>babel-types>lodash
tap>nyc>istanbul-lib-instrument>babel-generator>lodash
tap>nyc>istanbul-lib-instrument>babel-template>babel-traverse>babel-types>lodash
tap>nyc>istanbul-lib-instrument>babel-template>babel-traverse>lodash
tap>nyc>istanbul-lib-instrument>babel-template>babel-types>lodash
tap>nyc>istanbul-lib-instrument>babel-template>lodash
tap>nyc>istanbul-lib-instrument>babel-traverse>babel-types>lodash
tap>nyc>istanbul-lib-instrument>babel-traverse>lodash
tap>nyc>istanbul-lib-instrument>babel-types>lodash
tap>nyc>istanbul-reports>handlebars

```

Thanks for reading and commenting.

**Comment by isaacs** [comment]
Hi, and thanks for the kind words.

Since there aren't many wonder workers on tap (it's mostly just me, actually), I can't really afford to maintain long-term compatibility with versions of Node.js that fall off of [the LTS schedule](https://nodejs.org/en/about/releases/).  (As of this writing, that means, 6 and above.  Tap v13 will drop support for node v6.)

That being said, I'm of course sensitive to the needs to address the security warnings.  I'd be open to adding a v10 branch, and would accept a PR that updates deps so that they work for your needs and address the security issues.

Primarily, this means updating request (pulled in by coveralls), lodash (via istanbul-lib-instrument), and handlebars (via istanbul-reports).  The challenge will be that those packages (request/coveralls, istanbul-reports, and istanbul-lib-instrument) have all _also_ dropped support for v0.x nodes, so there is a bit of work to be done in finding the version that will address the security issues and also provide the compatibility you're after.

Yet another option is to fork node-tap at v12, call it `tap-old-node` or something, and painstakingly fix all the issues that cause problems for earlier nodes.  (No classes, no arrow functions, no const/let, etc.)  This will get even more difficult as time goes on, of course.

Another easier option is just to ignore the security warnings.  If you're using node v0.x, you're already subject to some pretty terrible security issues which will never be fixed without upgrading.  The chances that you're using tap in a production app where any of these issues might matter is pretty slim.

The best option, imo, which is both very safe and very easy, is to drop support for nodes that are no longer covered by LTS.

Without understanding the understandable reasons myself, I can't really comment on which option is best.  It does occur to me, though, if you're relying on browserify, why is their use of tap an issue for your application?  Does browserify depend on tap as a production dep, or a devDependency?

I hope this helps get you unstuck.

**Comment by isaacs** [comment]
> (No classes, no arrow functions, no const/let, etc.)

Oh, another thought, perhaps add a babel transilation build step in node-tap that outputs an ES5 version?  It could be loaded just for nodes that need it maybe?  I don't know if that would work, but it's worth exploring.

**Comment by infintesimal** [comment]
Hi @isaacs ,
What makes sense to me is (and I have initiated) is to fork and provide an updated version of 10.7. That's the happy medium for now. I might go rattle some cages, so to speak at browserify and suggest that they fork themselves to browserify and browserify-modern. Grin.

Just for the sake of context, this is a "enterprisy" scenario. Security teams want all the Is dotted and Ts crossed, such that all best effort has been made to seal off security holes. For things that are dev dependencies, it is, to me, as a developer, more of an absurd thing; for them it's a posture of not if, but when. These strike me as easy enough fixes to keep sec people happy. I'll stick in a PR request to the 10.7 branch if/when ready.

Thanks for your thoughtful commentary and feedback.

**Comment by infintesimal** [comment]
Oh, and ps: I am a (b)leading edge user of node; if I want my PR in browserify accepted, I need to figure out how to support 0.10 and 0.12. Fun.

**Comment by isaacs** [comment]
> Just for the sake of context, this is a "enterprisy" scenario. Security teams want all the Is dotted and Ts crossed, such that all best effort has been made to seal off security holes

Ok, that makes a lot ok sense, and is probably wise, if you're going to pick a simple policy to apply broadly across the organization.

**Comment by infintesimal** [comment]
Okay, I have everything setup. I have a pending pull request in tap-mocha-reporter (see [https://github.com/tapjs/tap-mocha-reporter/pull/53] ). And then I have a branch on my fork named v10.7.4 where the branch was created from tag 10.7.3. Let me know if you are ready to pull that (though to clear all security warnings, the tap-mocha-reporter PR would need to go first).

Thanks for all your time and thought. Feel free to ask questions.

**Comment by infintesimal** [comment]
I am the eager beaver here [https://github.com/tapjs/node-tap/compare/104728e2d...infintesimal:v10.7.4](https://github.com/tapjs/node-tap/compare/104728e2d...infintesimal:v10.7.4) The commit sha is that of the 10.7.3 tag. Not sure how you want to proceed of merging in my branch? rebase it onto v10.7.3 tag? In all cases for an end-to-end success the tap-mocha-reporter request I reference above would need to go first.
Happy Sunday.
