### ISSUE TITLE
problem with react-reconciler when updating to version 13

### ISSUE THREAD

**Issue by Marie000** [tapjs/tapjs#564]
I have been using version 12 without any problem. I tried updating to the newest version and I encounter this error: 

```
TAP version 13
not ok 1 - Cannot read property 'hasOwnProperty' of undefined
  ---
  at:
    line: 149
    column: 27
    file: node_modules/react-reconciler/cjs/react-reconciler.development.js
    function: $$$reconciler
  stack: >
    $$$reconciler
    (node_modules/react-reconciler/cjs/react-reconciler.development.js:149:27)

    Object.<anonymous> (node_modules/ink/build/reconciler.js:124:45)

    Module.replacementCompile (node_modules/append-transform/index.js:58:13)

    Object.<anonymous> (node_modules/append-transform/index.js:62:4)
  type: TypeError
  tapCaught: unhandledRejection
  test: TAP
  source: >
    // but PR #14548 split them out to better support the react-debug-tools
    package.

    if (!ReactSharedInternals.hasOwnProperty('ReactCurrentDispatcher')) {

    --------------------------^
      ReactSharedInternals.ReactCurrentDispatcher = {
        current: null
  ...
```
Same problem with version 14

I do not use react. 
Here is my test script: 
```
cross-env SECRETORKEY=<key> ISSUER=<issuer> DOMAIN=<domain> NODE_ENV=test tap -c tests/integration/index.js
```

**Comment by isaacs** [comment]
@vadimdemedes Any idea?

Tap uses ink as of version 13, which uses react.  Can you run this and tell me what prints?

```
npm ls ink
npm ls react
npm ls react-reconciler
```

Can you share a repo where this is happening so that I can reproduce it?

Thanks!

**Comment by vadimdemedes** [comment]
Could be some version conflict I think. Let's see the output of `npm ls` commands you posted above. Ideally, it would be useful to take a look at a repo where it's reproduced consistently.

**Comment by Marie000** [comment]
```
hobb-api@0.0.1 /home/marie/src/reader-api-1
└─┬ tap@14.2.0
  └─┬ treport@0.4.0
    └── ink@2.2.0

hobb-api@0.0.1 /home/marie/src/reader-api-1
└─┬ flow-coverage-report@0.6.1
  └── react@15.5.4

hobb-api@0.0.1 /home/marie/src/reader-api-1
└─┬ tap@14.2.0
  └─┬ treport@0.4.0
    └─┬ ink@2.2.0
      └── react-reconciler@0.20.4
```

The repo is here: https://github.com/RebusFoundation/reader-api
(If you want to run tests without having to bother with the database, I would suggest reverting to this old commit: a10a4fdbc4b26585386424919913b801f6eb400d which is right before I deleted the unit tests. )

**Comment by isaacs** [comment]
The version conflict is caused by having a requirement on React 15 at the top level, which conflicts with Ink's peerDependency on React 16.8.

`treport` has a regular dependency on React 16.8, but `ink` gets deduped up to the top level, and peer deps are not guaranteed by the npm installer.

@vadimdemedes Would you be open to making ink's dependency on React a regular dependency rather than a peer dep?  npm already deduplicates aggressively, but listing it as a proper dependency will avoid situations where it gets the wrong version.

This is also an opportunity for the npm installer to be a little smarter about how it arranges packages.  In this case, since nothing else uses ink, it would be fine to _not_ deduplicate ink all the way to the top level, meaning that it'd get the react dep that tap and treport share.

So, solutions, ordered from fastest and kludgiest to slowest and most elegant:

1. tap ships treport and ink as bundledDependencies, so that ink gets the right react.
2. ink changes react from peerDep to regular dependency.
3. npm installer gets smarter about peer deps nested in the tree during the deduplication algorithm.
