### ISSUE TITLE
make snapshot file location configurable

### ISSUE THREAD

**Issue by sramam** [tapjs/tapjs#566]
I am trying to switch from ava to node-tap and really enjoying the switch, not least for the fact that the code is much more grok-able.

The only feature from `ava` that I miss, is the location of the snapshot files. node-tap
stores these in a global, [hard-wired path](https://github.com/tapjs/node-tap/blob/master/lib/snapshot.js#L13).

`ava` co-locates these with source files, traced through compilation via source-maps. 

## My use case:
I find this particularly useful when developing complex applications, when the final set of
useful modules for the application is in flux. These can be developed as sub-directories
within the single node-module, without worrying about final form. 

As the code-base stabilizes, it's a simple matter to create a new node-module, copy and paste the appropriate sub-directory to its new resting place, re-build and commit. 

### The issue
Ideally, acceptance criteria should involve a simple re-build. However, since the snapshots
are not co-located and in-fact don't preserve the directory structure, this is not possible without significant effort - because the dir-path in the new repo is different and will have to be hand modified/scripted.

### Ideal solution
Obviously, preserving the directory structure would help some, but ideally, co-locating the snapshot files and preserving the directory structure would be the ideal. 

### Possible solution
Interestingly, it seems this should be as simple as changing the computation of [`this.file` here](https://github.com/tapjs/node-tap/blob/master/lib/snapshot.js#L13) Perhaps this could be a configurable option, or the snapshot location could be a function that is passed in. 

## The ask
Before I go implementing such a change, I wanted to check in to see if there is any appetite for such a modification and what for would be acceptable.

**Comment by isaacs** [comment]
I'm glad to hear you're finding tap enjoyable :)  I can see that it imposes some friction on refactoring though, to be sure.  I'm not opposed in principle to making this configurable (or even changing it entirely), but there are a few things to consider.

One hazard will be that the default file inclusion logic may happen upon snapshot files, which we don't want, and it's nice to be able to just `require()` them as `.js` files.  (Currently, the default include regex walker can avoid even descending into the `tap-snapshots` folder.)

Also, I sometimes do things like `tap test/fixtures/*.js --test-arg=test/run.js` so that the executed command is something like `node test/run.js test/fixtures/foo.js`.  Then `test/run.js` loads the fixture and compares it against a snapshot.  In order for this to work, the filename has to be dependent on not just the main filename, but the entire set of command-line arguments.  (Otherwise `node test/run.js test/fixtures/bar.js` will load/clobber the same snapshot.)

It would help encourage people to check snapshots into source control if they weren't in a separate folder.  However, deleting and re-generating might be trickier.  When I refactor tests, I sometimes do `rm -r tap-snapshots; npm run snap` to regenerate.  If they were scattered throughout my test suite, that might be trickier.  (I guess I could still just do `rm test/**/*.snap.js` or whatever?  Or even add a `--clear-snapshots` option to delete any snapshot files that weren't loaded?)

If you implement it as a configurable function, take a look at how the `--coverage-map` option is implemented.  I'd probably want to follow that same pattern.  In the `Test` class, it should look at an environment variable `TAP_SNAPSHOT_FILE`, which is set in the environment by the test runner.

**Comment by sramam** [comment]
thanks for being so welcoming on this @isaacs. 
I will be working on this, but have limited time. To not clutter up the open issues, will close this one for now and reopen once I have something to share.

**Comment by tryhardest** [comment]
Hi @sramam how is your experience with node-tap nearly a year on from AVA?
