### ISSUE TITLE
Where’s my cursor?

### ISSUE THREAD

**Issue by michaelnisi** [tapjs/tapjs#569]
Aborting an about to timeout test with v14.2.2, leaves me with a shell without cursor, which is hamstringing—it forces me to kill that shell and start over. This is iTerm2 and zsh on macOS. 

![Screenshot 2019-06-11 at 09 54 48](https://user-images.githubusercontent.com/108903/59254097-d2d47000-8c2f-11e9-89dc-76c67f1bfc43.png)

**Comment by michaelnisi** [comment]
Probably my setup. That banner is a bit much. 🌈🤗

![Screenshot 2019-06-11 at 11 33 52](https://user-images.githubusercontent.com/108903/59261016-fa7e0500-8c3c-11e9-8fe5-4649dea67ea4.png)

**Comment by isaacs** [comment]
The missing cursor can happen because of how `ink` puts the terminal in raw mode.  If it is forcibly killed before it has a chance to reset things, it can leave it in that state.  You can always run the bash/zsh built-in function `reset` to bring it back.  You shouldn't have to kill the terminal and start over.

If the banner is too much for you, try using `-R terse` or set `"tap": {"reporter":"terse"}` in your package.json.

Or, avoid both issues by using the old reporter, `-R classic`.  There's a lot to choose from, actually.  But of course, the non-ink reporters don't give you as detailed progress information, since that kind of reporting requires raw mode to keep everything organized properly.

**Comment by isaacs** [comment]
Here are the reporter options: https://www.node-tap.org/reporting/

**Comment by michaelnisi** [comment]
I like the banner, I just don’t like its white background in the dark shell. I guess matching the banner to the shell background is tricky. 

BTW, coming back to Tap after a while (less Node stuff, some time spent with Jest), I’m super impressed by all the new features. Thank you for this great tool. Even a 🆕 [website](https://www.node-tap.org) What!? 🎉

One thing, in watch mode, especially when working on a specific thing, it would be nice if it would be easier to hide the coverage report. In that use case I’m mostly interested in the output of my program, the coverage report takes up space. Now I’m generating html just to hide it, it seems.

```
NODE_DEBUG=thing npx tap test/http.test.js -b -g='aborted' -Rsilent -w --no-browser --coverage-report=html
```

Sorry for derailing this issue.

**Comment by isaacs** [comment]
@michaelnisi You should be able to do `--no-coverage-report` to suppress the output.  It'll still gather coverage information, and you can do `tap --coverage-report=text` (or html or whatever) to print it out.
