### ISSUE TITLE
Timeout per test file

### ISSUE THREAD

**Issue by IlyaSemenov** [tapjs/tapjs#575]
I'm struggling to set a timeout for a certain file.

I know that I can set *global* timeout (with `TAP_TIMEOUT` or cli options), and I also know that I can set individual timeouts for test cases with `tap.test({ timeout: xxx }, ...)`.

However, I don't seem to be able to override timeout for a certain file (when running all tests with `yarn tap '*/**/*.test.ts'`). In particular, `tap.setTimeout(600000)` or setting `tap.options.timeout = 600000` doesn't seem to affect anything.

Also, it seems that individual test timeouts are still capped with `TAP_TIMEOUT` (or default 30 seconds).

My use case is that I have plenty of test files, and I need to allow one of them (or individual tests in it) to work much longer than all others.

**Comment by isaacs** [comment]
There is no way to do what you're asking for presently.  The best advice I have for you is to set the TAP_TIMEOUT (or `-t` argument) to the longest that any test file will need.  Since that's set outside the test file environment (in the runner) it can't be changed from within the test file (though that's an interesting idea that I've thought about before, it's tricky to get right, and would only rarely be useful.)

It's also often a good idea to split up tests into smaller files, if possible.  Sometimes a test taking a long time is a sign that it's testing too much and could be more useful if it was a bit more modular.

**Comment by IlyaSemenov** [comment]
Thank you for the advice. Yes, `tap --timeout 600` is exactly what I've ended up with. However, that now means if my other tests go crazily slow that will go unnoticed. Not a deal breaker, simply not elegant.

I agree that tests should better be small. However, in this case I'm dealing with a legacy system which runs a single behemoth test case with Puppeteer against the web site, which creates lots of interconnected data via the web interface.

I think `tap.setTimeout()` could report to the 'upstream' runner and provide the new timeout. They are talking with some sort of protocol anyway? (Or is it simply the text protocol I'm seeing when running individual test files on their own? If so, then perhaps the child could use `process.send` to deliver that kind of auxiliary info).

**Comment by isaacs** [comment]
Yeah, it's the [TAP protocol](https://www.node-tap.org/tap-protocol).  My thinking was having it output a special comment like `# timeout=600` when you set the timeout, and then update the timeout value whenever it sees that comment in a subprocess's output.

I was just thinking, you could set a high timeout in the runner, and then have all of the other tests set a lower timeout internally so they'll fail if they go too long.  Not ideal, I know, but at least it's something for now.  I'm leaving this ticket open and could maybe revisit some time, now that there's a non-hypothetical use case.

**Comment by isaacs** [comment]
I was taking a look at this because a meeting got canceled, and I think it might be easier than I'd thought.  Can you try `npm i tapjs/node-tap` and see if that makes things better?  With that, you should be able to call `t.setTimeout(600000)` at the top level in that one slow test, and let all the other ones time out at the default 30s.

**Comment by IlyaSemenov** [comment]
Yes, it works perfectly. Will you please publish a npm release?

**Comment by isaacs** [comment]
It's causing some test failures on v8 and v10, looking into that and then I will.

**Comment by isaacs** [comment]
14.3 is out with this feature now.  `npm i tap@latest` to go back to the npm release :)
