### ISSUE TITLE
in watch mode new files are not detected

### ISSUE THREAD

**Issue by pke** [tapjs/tapjs#599]
using `--watch` when adding a new test file like `test/newtest.test.js` is not detected. One has to restart tap or use `r` in the `repl`

**Comment by isaacs** [comment]
This is true.  However, to do this, since tap will run test files found anywhere, wouldn't it have to be watching every directory that could conceivably have a test file in it eventually?  Including new dirs added?

I shied away from that because it imposes a lot of additional complexity in the watch implementation, and just typing `r` (or even `r test/foo.js`) in the repl seemed like an ok compromise.

**Comment by isaacs** [comment]
Maybe we could add a new repl command to scan for new test files, so at least you don't have to re-run the whole suite or type a filename?

**Comment by pke** [comment]
Understood! So that is the reason why I could not temporarily move some of my test files to the `node_modules` folder and tap would still run them.

How about it could at least scan in the folders it already found test in for new files?
But `r` is fine. Will it revert back to changed mode after running this?

**Comment by isaacs** [comment]
Yeah, new files added with `r` should still be watched for changes and run when they change or any files they load change.
