### ISSUE TITLE
Exclude files from coverage

### ISSUE THREAD

**Issue by repinvv** [tapjs/tapjs#604]
Need a way to exclude files from coverage.

Added .nycrc file, did not work.
```
{
  "exclude": [
    "./**/*.spec.js",
    "./**/*.type.js",
    "./**/index.js"
    ]
}
```

**Comment by isaacs** [comment]
I'd expect that that would work.  But, you can definitely add this to your package.json file:

```json
{
  "tap": {
    "nyc-arg": [
      "--exclude=./**/*.spec.js",
      "--exclude=./**/*.type.js",
      "--exclude=./**/index.js"
    ]
}
```

Also note that as of the latest release, tap automatically excludes any files from coverage, so this _might_ not be as much of an issue.

**Comment by repinvv** [comment]
That did not work as well, here is the gist https://gist.github.com/repinvv/9265a57a47010997d7c4e62d056f6431

npm i && npm test

expected result  - one file in coverage report
actual result - three files

**Comment by revelt** [comment]
@repinvv If Isaac's example doesn't work, maybe it's because your root level is different (like it will be in a monorepo scenario)? Try removing the `./` in the front. For example, here's how I exclude all UMD files, it does work for me:

```
{
  "tap": {
    "nyc-arg": [
      "--exclude=**/*.umd.js"
    ]
}
```

Put the above in `package.json`, the `tap` goes as a root level key.
