### ISSUE TITLE
jsonstream reporter doesn't report parallel running test results in "realtime"

### ISSUE THREAD

**Issue by andybee** [tapjs/tapjs#609]
I've written a very basic example of 2x test suits, one with a 2 second timeout, one with an 8 second timeout. When running with the default colour reporter I see the shorter-running test output it's pass once the time is up, before the 8 second test completes.

I would expect the `jsonstream` report to behave similarly, with the first suite result being posted soon after completion, ahead of the second. Instead, it seems to await all suites then output the result.

I'm unsure if I'm perhaps misunderstanding how this should work, or if it's a bug/limitation of the current reporter? If I wish to get a `jsonstream`-style report where each suite reports on completion, would it be best to implement my own reporter?

**Comment by isaacs** [comment]
The jsonstream reporter is using the older tap reporter format, so it always prints the tests in the order that they're defined, even if a later test finishes first.

This means that your faster test will show up first if it's defined first, but otherwise it'll wait until all preceding tests have finished before printing its results.

Here's a gif showing a fast test printing its results ahead of a slow test:
![tap-fast-slow-jsonstream](https://user-images.githubusercontent.com/9287/68320034-1ebb0200-0074-11ea-8c37-446905bf7473.gif)

It wouldn't be a bad idea to implement a jsonstream report in [treport](https://github.com/tapjs/treport), since jsonstream _does_ allow output to be out of order.  That would be the way to ensure that results always show up asap, even if that means that they're out of order.

**Comment by isaacs** [comment]
Now that I think about it, part of the reason this probably hasn't been a priority is that the jsonstream reporter output typically goes to machines, not humans.  In that case, you probably don't care so much about real-time output, as much as getting output that's consistent and _finishes_ as soon as possible.  If a faster later test gets output ahead of a slower earlier test, then that loses consistency without improving overall speed.

**Comment by andybee** [comment]
Thanks for the detailed explainer, it all makes sense.

I have a particularly unusual use case in that I'm wrapping up a tap test suite with a friendly web UI and want to show a simplistic progress indication (tick off tests as they happen, use the plan markers to calculate a crude % progress).

As this is sufficiently in the realms of quirky edge case, I might be best implementing my own reporter for this purpose.

**Comment by isaacs** [comment]
> I have a particularly unusual use case in that I'm wrapping up a tap test suite with a friendly web UI and want to show a simplistic progress indication (tick off tests as they happen, use the plan markers to calculate a crude % progress).

That makes sense, then.  I'd recommend adding a jsonstream reporter to treport, then.  There are a couple of examples in that repo if you look in the `lib/reports/` folder.  The other reports (for now just `speccy` and `terse`) extend the Base reporter class.  For a jsonstream reporter, I'd recommend waiting until the first `testStart` method fires, and then outputting a `['start',{total:${suiteCount}}]` line.  Then each test can output its line in the `testEnd` method.  You'll probably want to override a few of the child classes to make them push an object into the `state.log` array, and then have the `render` method contain only a single `<Static>` block that renders all the `state.log` items by JSON.stringifying them.  Hope that's helpful, and I'll definitely accept the patch when you add it, because I think it'd be a net improvement over the current jsonstream reporter :)

**Comment by andybee** [comment]
Thanks for the initial pointers. I'm relatively comfortable with the basics of React, but I'm feeling a bit out of my depth with Ink and the specific interdependencies between the Base reporter and other layers in the existing reporters. Would it be possible to get a slightly more fleshed out example of how this might be implemented?

**Comment by isaacs** [comment]
The reporter system has been pretty massively updated in tap 18, and the `@tapjs/reporter` module will give you all the components and hooks you need, plus a couple full examples to take a look at.

Check it out with `npm i tap@pre`. https://node-tap.org/changelog/#18.0
