### ISSUE TITLE
"exclude" field in .nycrc.json no longer works

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#612]
The `exclude` field in `.nycrc.json` no longer works. I'm guessing a recent `tap` release started adding some defaults, causing the config file field to be ignored.

Ideally the defaults would augment, and not replace, user config.

**Comment by coreyfarrell** [comment]
nyc doesn't have an `excludes` option, it's `exclude`.

**Comment by jaydenseric** [comment]
@coreyfarrell thanks, I did a typo and meant to say `exclude`; I was in fact using the right one:

https://github.com/jaydenseric/graphql-upload/commit/0f92002a66a6a3088d2b40ffa23fc56ccc5306c2#diff-ef814fc9852f9384bea581fd0673977dL2

**Comment by isaacs** [comment]
Yeah, tap started explicitly excluding all test files from coverage, since that's almost never what you want (and it led to some weird bad behavior in some cases).

I've been chatting with @coreyfarrell about better ways to structure the tap/nyc integration.  It's a bit of weird interface boundary right now, and I think there are a few small improvements we could make on either side to avoid issues like this.

**Comment by goto-bus-stop** [comment]
We ended up using `"tap"."nyc-arg"` instead of `"nyc"` here: https://github.com/nearform/node-clinic-flame/commit/8adf4c4d103905defe78803bd2bc294feab44cf6

**Comment by isaacs** [comment]
Nyc no longer used in tap 18. Check it out with `npm i tap@pre`. https://node-tap.org/changelog/#18.0
