### ISSUE TITLE
Async test succeeds even if done is never called

### ISSUE THREAD

**Issue by TomPradat** [tapjs/tapjs#639]
I'm not sure this is a bug, but it's quite disturbing that an async test that never calls done is considered passing.

```
describe('Test',  () => {
  it('should throw as done is never called', async (done) => {
    let toto = false;

    setTimeout(() => {
      toto = true
    }, 20000)
  })
})
```

**Comment by coreyfarrell** [comment]
This is how the tap API's work, ie `t.test('returns promise that resolves', async () => {});` will pass.  It is also the documented functionality of mocha API's, see https://mochajs.org/#working-with-promises.

So I think this is not a bug, it's the expected result.

**Comment by TomPradat** [comment]
Mocha default behavior is to throw if done is not called. I just tried the exact same code on mocha and the test fails.

**Comment by coreyfarrell** [comment]
It seems that mocha detects `done` argument callback rather than just detecting calls to it.  I've run into an edge case with mocha itself which I've reported at https://github.com/mochajs/mocha/issues/4135.  I'd like to get clarification on what is expected in that case before I try emulating the functionality here.

```js
it('resolution overspecified', async (done) => {
  process.nextTick(() => done());
});

it("doesn't fail but should it?", async (done) => {
  done();
});

it('fails to resolve Promise due to done arg', async (done) => {});

it('async without done argument passes', async () => {});
```

**Comment by isaacs** [comment]
Sorry, no, this is 100% working as intended, and it is a very intentional intent.

I will die on the hill of inspecting function.length to detect if a `done` function is expected by a callback.  It's a bad pattern, and it's one of the areas where tap fundamentally disagrees with mocha, so the "mocha-like" tap api will never be fully mocha-like in this particular regard.

Not a bug.  I recommend using the official tap APIs, where it's less unclear, because it's not mimicking something that has a different design goal.
