### ISSUE TITLE
`afterEach` and `teardown` do not have time to complete if the tests with `--bail` are falling

### ISSUE THREAD

**Issue by psixdev** [tapjs/tapjs#646]
Hi. If I run tests using the tap runner with `--bail` and they are failing, async `afterEach` and `teardown` hooks do not have time to complete.

Test example:

```js
const t = require('tap');
const {promisify} = require('util');

const delay = promisify(setTimeout);

t.afterEach(async () => {
	console.error('afterEach: start');
	await delay(1000);
	console.error('afterEach: finish');
});

t.teardown(async () => {
	console.error('teardown: start');
	await delay(1000);
	console.error('teardown: finish');
});

t.test('test', async (t) => {
	console.error('test: start');
	await delay(1000);

	t.ok(false, 'check');
	console.error('test: finish');
});
```

Output when the runner was used:

```shell
$ tap --jobs 1 --no-coverage --bail test.js > /dev/null

test: start
afterEach: start
teardown: start
test: finish
```

However, if you run the tests using node, the hooks will succeed and the output will be as follows:

```shell
$ TAP_BAIL=1 node test.js > /dev/null

test: start
afterEach: start
teardown: start
test: finish
afterEach: finish
teardown: finish
```

This is strange and inconsistent with the first paragraph from README.md:

> 1. Test files should be "normal" programs that can be run directly.
> …

I found out that the process ends due to this line:
https://github.com/tapjs/node-tap/blob/56fb7b239647bb57cd1f161040c4c5dad9eb1512/lib/spawn.js#L70

If the test is run by node, the process just waits for test completion. Is it possible to use the same approach with a runner?

Another interesting point, `afterEach` and `teardown` hooks are launched in parallel when using `bail`, it seems wrong to me. This does not happen when starting without `bail`:

```shell
$ node test.js > /dev/null

test: start
test: finish
afterEach: start
afterEach: finish
teardown: start
teardown: finish
```

**Comment by jhillacre** [comment]
As reported above, I am encountering `teardown` running before `afterEach` finishes when using the '--bail' option. I am running tap 14.11.0 and node 14.15.5.

**Comment by gsouf** [comment]
There is one more issue here, the code after the failed assertion will keep running, and if there is an async operation then it will be performed after the teardown/afterEach handlers. Causing possible issues because required data have been disposed during the teardown (for example a database connection) resulting in more error log polluting the output with unrelevant errors.

Reproduction code:

```js
test("foo", async (t) => {
  t.before(async () => {
    t.context.checkpoint = "before";
  });

  t.teardown(() => {
    t.context.checkpoint = "teardown";
  });

  t.test("bar", async (t) => {
    console.log("checkpoint value: ", t.context.checkpoint);
    t.same(1, 2);

    await new Promise(() => {
      if (t.context.checkpoint === "teardown") {
        throw `teardown has been triggered too early`;
      }
    });
  });

  t.end();
});
```

Outputs:

```
src/something.test.js 1> checkpoint value:  before
 FAIL  src/something.test.js
 ✖ should be equivalent

  src/something.test.js                                              
  16 |   t.test("bar", async (t) => {                                
  17 |     console.log("checkpoint value: ", t.context.checkpoint);  
> 18 |     t.same(1, 2);                                             
     | ------^                                                       
  19 |                                                               
  20 |     await new Promise(() => {                                 
  21 |       if (t.context.checkpoint === "teardown") {              

  --- expected    
  +++ actual      
  @@ -1,1 +1,1 @@ 
  -2              
  +1              

  test: src/something.test.js foo bar
  stack: |
    Test.t.test (src/something.test.js:18:7)

src/something.test.js 2> { error: 'teardown has been triggered too early',
src/something.test.js 2>   tapCaught: 'returnedPromiseRejection',
src/something.test.js 2>   test: 'bar' }

```

**Comment by isaacs** [comment]
I'm torn on this.

On the one hand, "bailout" should really be "get of this test file asap and shut the entire suite down".  Like, "do not pass go, do not do any additional things, you're done, it's over, there's no way to continue, gtfo". On the other hand, yeah, you sometimes would really expect that a teardown would be part of that "bailing out" process.

The problem in prior versions of tap was that it was trying to sort of have it both ways. Like, a bailed out test wouldn't add any _new_ stuff, but it'd still try to wrap up what it already had scheduled. Which has traditionally led to people reporting the inverse of this issue, oddly enough.

In tap 18, at least currently, when a bailout occurs, the root tap test for that process will exit the process _in that tick_ when it occurs, as soon as the bailout signal gets up to the root TAP object. So no, there's no teardown or afterEach that's going to happen. It's bailed out. That's what bailed out means.  A `--after` module will still be run, so that's a bit of an escape hatch for any system cleanup activities that are required, but having used it a bit with this approach, I have to say, it's _so_ much nicer. Bailout happens, boom, it's over. Fix the thing, run the tests with `-b` again, it gets past it, next thing fails and it stops _right away_. It's so snappy and convenient.

I'm definitely open to considering ways to have something like "ok, but seriously, even if you bail out, _this_ has to be cleaned up, however long it takes", but it's gonna have to be pretty compelling.
