### ISSUE TITLE
Create an option for unlimited parallel execution

### ISSUE THREAD

**Issue by hudovisk** [tapjs/tapjs#661]
Hi!

I would like to know if a PR for allowing unlimited parallel execution would be welcome. In my use case I am running end to end test cases that heavily uses network requests and the current option for running parallel tests has some issues in my opinion, the main one being that jobs set in the parent `tap` is not passed to child tests

Please le me know what you think

**Comment by isaacs** [comment]
That's typically not what you want to do, but you can set `t.jobs = Infinity` in your test to enable this.

Jobs are not inherited because it's almost never a good idea.  Even if you are doing a lot of waiting on networking, you only have so many CPUs.  You can more effectively speed up your tests (and make them more reliable) by mocking the HTTP endpoints and hitting localhost.

**Comment by coreyfarrell** [comment]
I agree, a recursive parallel jobs option would create problems most users.  Personally I would not recommend `t.jobs = Infinity`.  When I need a single test file to run stuff in parallel I generally do `t.jobs = require('os').cpus().length * 2`, this way when my project won't overrun processing power/memory limits of CI systems (which are all lower power than my workstation).
