### ISSUE TITLE
Better t.plan UX

### ISSUE THREAD

**Issue by ruyadorno** [tapjs/tapjs#694]
I just shot myself in the feet using `t.plan()` :joy: so I thought I should stop by and propose an improvement since I would like that to not happen again in the future.

Currently `t.plan()` can be mixed with no-async/callback style `t.end()` and the result is not at all what I expected from an user-pov, e.g:

```
// test.js
'use strict'
const { test } = require('tap')

let count = 0

test('test plan', (t) => {
  t.plan(1)
  setTimeout(() => {
    count++
    t.equal(count, 1, 'should count')
    count++
    t.end()
  }, 100)
})

test('should have ended test', (t) => {
  t.plan(1)
  t.equal(count, 2, 'should have expect value')
})
``` 

As now it's clear to me, anything past the number of expected assertions determined by `t.plan()` is no longer executed until after the test after and so and so...

Given that it's excludent behavior when used together along with `t.end()` it would be nice to:
- Throw an error/warning when using `t.plan()` along with `t.end()` ?
- Throw a warning message whenever using `t.plan()` in a non-async func?
- Some other better solution to avoid this hazard?

**Comment by isaacs** [comment]
This is a bit tricky, because pretty much any change to this will have some weird effects.

You _can_ use .plan(), .end(), and a Promise return all together, and in fact, that can in some cases be a good way to ensure that a test fails fast rather than hanging.  And using .plan() in sync functions is pretty normal, it's just an alternative to calling .end().

I think the solution here is maybe better docs and better error messages for the various "invalid end" and "test unfinished" cases. Tap 18 has much improved error messages, but of course docs can always be better.  Closing this, because I'm not sure what can really be done as far as the API goes.
