### ISSUE TITLE
Running `tap` via `npx` outside project root with coverage enabled garbles stack traces

### ISSUE THREAD

**Issue by hamptonsmith** [tapjs/tapjs#710]
Very specific, but easy to reproduce!  See attached for a more complete bunch of test cases with output (.txt extension appended to satisfy github).

```bash
#!/bin/bash

cd $(mktemp -d)
echo '{"scripts": {"test": "tap foo/test.js"}}' > package.json
NPM_ENV="" npm install --save-dev tap@14.11.0 &> /dev/null

mkdir foo
echo -e 'const tap = require("tap");\n\nthrow new Error()' > foo/test.js

echo -e "\n\n\n### Non-root, npx tap."             # <-- problem here
(set -x; cd foo; npx tap -R=tap test.js >/dev/null)
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "Oops!  Wrong line number!"

# Oops!  Wrong line number:
#     /tmp/tmp.lIDwwsjEn6/foo/test.js:1
#     Error: 
#         at Object.<anonymous> (/tmp/tmp.lIDwwsjEn6/foo/test.js:1)
```

**Comment by hamptonsmith** [comment]
[tapstack.sh.txt](https://github.com/tapjs/node-tap/files/5745935/tapstack.sh.txt)
[tapstack.output.txt](https://github.com/tapjs/node-tap/files/5745936/tapstack.output.txt)

**Comment by jsumners** [comment]
As you said, this is very specific. It seems to me that this would fall under "unsupported". Is there a common use case for running tests in this manner?

**Comment by hamptonsmith** [comment]
I don't think the scenario is particularly crazy.  You often want to run coverage and `npx` is a common way of invoking a non-globally installed npm binary.  If you don't feel like typing the leading path to the test files, you `cd path/to/files` and then try to `npx tap *.test.js`, and boom you've hit the bug, which presents very mysteriously and I only tracked down through trial and error.

That said, no strong opinion on if this is worth fixing, it's certainly not along the primary use path.  It just wasted a couple hours for me as I was setting up some scripts so I figured I'd report it!  (It also seems like it should be an easy fix, since it's working perfectly in all the other cases?  Like certainly some stack depth config is just off somewhere :man_shrugging: ...)

**Comment by coreyfarrell** [comment]
You might try `npm install tap@v15-beta` see if that helps - this uses a newer version of nyc than tap@14 (current release).  Note that nyc has some issues with running outside your project directory and some of these issues are unlikely to ever be fixed.  A main issue is how config files are found - start by looking in `process.cwd()`, keep checking higher directories until the config is found.  Running from a subdirectory inside the project will likely be better supported than running from outside the project.

That said the normal case is to run tests from the project root, doing otherwise is asking for problems.  Maintainers have lots of issues to deal with and must prioritize those which effect the most users.

**Comment by hamptonsmith** [comment]
> You might try npm install tap@v15-beta

Awesome, I'll give that a try this evening and report back

>  Maintainers have lots of issues to deal with and must prioritize...

Yep!  I get this isn't P0 ;)

**Comment by hamptonsmith** [comment]
With `tap@v15-beta` I get nothing on stderr, but on stdout see this test line:

```
not ok 1 - ENOENT: no such file or directory, scandir '/tmp/tmp.IvCJ2sVPxS/foo/.nyc_output/processinfo
```

Which at least points me in the direction of the problem since it's clear something is trying to operate within the CWD instead of the project directory.

**Comment by isaacs** [comment]
I suspect this issue was due to some weirdness with in the combination of istanbul and possibly the source-map-support module.

Both of those are replaced with their node and V8 built-in descendants, and this seems to no longer be a problem, on tap 18.

`npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.
