### ISSUE TITLE
proposal: shareable configurations

### ISSUE THREAD

**Issue by esatterwhite** [tapjs/tapjs#714]
Tap configuration is currently driven by local files (rcfile or package.json). In larger organizations, this makes consistency difficult.
For example, at the day job we have 200+ repositories that use tap. That number is expanding and keeping them consistent is pain as they can't be shared or versioned in any sensible way.

Configuration resolution would be considered at the same level as `package.json` or `.taprc`. The addition would be 
the `extends` key which points to an npm package(s) that exports a single object which is a valid tap configuration object.
If `extends` is an array each configuration is merge with the previous and any top level keys acting as final(local) overrides.
This effect can be recursive as the configuration exposed by a shareable configuration can also extend from a shareable configuration

```json5
// package.json
{
  "tap": {
    "extends": "tap-config-<name>"
  , "output-file": "report.tap"
  }
}
```

```yaml
# .taprc
extends: tap-config-<name>
output-file: report.tap
```

#### Prior Art
* [eslint](https://eslint.org/docs/developer-guide/shareable-configs)
* [semantic-release](https://semantic-release.gitbook.io/semantic-release/usage/shareable-configurations)
* [commit-lint](https://commitlint.js.org/#/concepts-shareable-config)

**Comment by isaacs** [comment]
This is now a thing!

With tap@18, you can put this in your `.taprc`:

```yaml
extends: "@mycompany/tap-config-pkg"
```

Or, in `package.json`

```json
{
  "tap": {
    "extends": "@mycompany/tap-config-pkg"
  }
}
```

Then, it'll look for a package in a `node_modules` somewhere at or above that config file, containing either `@mycompany/tap-config-pkg/.taprc` or failing that, `@mycompany/tap-config-pkg/package.json`, and read the base configs from there.

You can also put `"extends": "./some-file.yaml"` if you just want to have a different filename than `.taprc`.

That thing can extend something else, and so on. Cycles will be detected and skipped, but they're not a great idea, because then the overriding will depend on which one is loaded first, which is probably just going to be confusing.

**Comment by isaacs** [comment]
You can try it out with `npm i tap@pre`. The [changelog](https://node-tap.org/changelog/#18.0) describes the considerable updates that it includes.
