### ISSUE TITLE
Maintain strict order of logs vs tap output (checks)

### ISSUE THREAD

**Issue by bluenote10** [tapjs/tapjs#720]
I'm looking for a test framework that can support full linear testing, i.e., I'd like to keep the order of application logs and test checks exactly as they are (use case: larger integration tests that typically intertwine high level application logs with checks). I like the motivation behind `node-tap` a lot, and it sounded like this would be on the feature list.

However I have a very hard time to make sense of the test output, because logs and checks get seem to get separated. Here is a small example:

```js
const t = require("tap");

const delay = (time) => new Promise((resolve) => setTimeout(resolve, time));

t.test("test 1", async () => {
  console.log("log 11");
  t.ok(true, "check 11");
  console.log("log 12");
  t.ok(true, "check 12");
});

t.test("test 2", async () => {
  await delay(100);
  console.log("log 21");
  t.ok(true, "check 21");
  console.log("log 22");
  t.ok(true, "check 22");
});

t.test("test 3", async () => {
  console.log("log 31");
  await delay(10);
  t.ok(true, "check 31");
  console.log("log 32");
  await delay(10);
  t.ok(true, "check 32");
});
```

The raw TAP output is:

```
TAP version 13
log 11
log 12
# Subtest: test 1
    1..0
ok 1 - test 1 # time=6.004ms

ok 2 - check 11
ok 3 - check 12
log 21
log 22
# Subtest: test 2
    1..0
ok 4 - test 2 # time=102.955ms

log 31
log 32
# Subtest: test 3
    1..0
ok 5 - test 3 # time=22.266ms

ok 6 - check 21
ok 7 - check 22
ok 8 - check 31
ok 9 - check 32
1..9
# time=137.036ms
```

The output looks quite confusing, i.e., it is hard to tell where subtests start/end and see the flow of logs/checks. My expectation/hope was that check output is exactly at the points between the log messages. In practice this means that I cannot easily correlate application logs with test failures. For instance, imagine `check 22` fails. The application log information related to that (`log 22`) is far away from the check output.

Am I doing anything wrong or is there a way to enforce a linear output. In theory it seems possible, because the checks could have synchronous behavior and all promises could be awaited.

**Comment by isaacs** [comment]
You're not capturing the `t` argument that's passed in as an argument for each of those test methods, so you're effectively just calling `t.pass` on the parent test, rather than the children.

Try with this:

```js
const t = require("tap");

const delay = (time) => new Promise((resolve) => setTimeout(resolve, time));

t.test("test 1", async (t) => {
  console.log("log 11");
  t.ok(true, "check 11");
  console.log("log 12");
  t.ok(true, "check 12");
});

t.test("test 2", async (t) => {
  await delay(100);
  console.log("log 21");
  t.ok(true, "check 21");
  console.log("log 22");
  t.ok(true, "check 22");
});

t.test("test 3", async (t) => {
  console.log("log 31");
  await delay(10);
  t.ok(true, "check 31");
  console.log("log 32");
  await delay(10);
  t.ok(true, "check 32");
});
```

(Note the `t` argument accepted by each of the test methods.)

Then the output looks like this:

```
TAP version 13
log 11
# Subtest: test 1
    ok 1 - check 11
log 12
    ok 2 - check 12
    1..2
ok 1 - test 1 # time=7.31ms

log 21
# Subtest: test 2
    ok 1 - check 21
log 22
    ok 2 - check 22
    1..2
ok 2 - test 2 # time=107.095ms

log 31
# Subtest: test 3
    ok 1 - check 31
log 32
    ok 2 - check 32
    1..2
ok 3 - test 3 # time=26.007ms

1..3
# time=145.855ms
```

Note that when a new subtest starts running, it only outputs its `# Subtest: <name>` line when the first TAP output is generated.  This is due to how the parser works, because it can't know if the `# Subtest: ...` line is a valid start of a child test until it sees an indented line.

The issue that you're seeing, where the checks don't happen until well after all the tests are completed, is due to the fact that tap will defer any test point output if it's in the process of running a child test.  A simpler example:

```js
const t = require('tap')
t.pass('this comes before the child test')
t.test('takes a while', async t => {
  await new Promise(resolve => setTimeout(resolve, 1000))
  t.pass('ok, done')
})
t.pass('this comes after the test')
```

This produces the following output: 

```
TAP version 13
ok 1 - this comes before the child test
# Subtest: takes a while
    ok 1 - ok, done
    1..1
ok 2 - takes a while # time=1008.713ms

ok 3 - this comes after the test
1..3
# time=1031.967ms
```

It would be surprising if the `ok 3` test point was printed _before_ the child test, but of course, that `t.pass()` line is encountered after the `t.test()` method has fired, but before the child test has completed.

If you truly want to enforce 100% strictly linear output, tap does support this by design.  The only way to have it be 100% perfectly lined up, however, is to avoid using promises or async anything, and end your tests explicitly with either `t.plan(n)` at the start, or `t.end()` at the end.


```js
const t = require('tap')
console.log('before child 1')
t.test('child 1', t => {
  console.log('before child 1 test point')
  t.pass('test point')
  console.log('after child 1 test point')
  t.end()
  console.log('after child 1 end')
})
console.log('before child 2')
t.test('child 2', t => {
  console.log('before child 2 test point')
  t.pass('test point')
  console.log('after child 2 test point')
  t.end()
  console.log('after child 2 end')
})
console.log('after children')
```

```
before child 1
TAP version 13
before child 1 test point
# Subtest: child 1
    ok 1 - test point
after child 1 test point
    1..1
after child 1 end
ok 1 - child 1 # time=3.59ms

before child 2
before child 2 test point
# Subtest: child 2
    ok 1 - test point
after child 2 test point
    1..1
after child 2 end
ok 2 - child 2 # time=0.807ms

after children
1..2
# time=13.419ms
```

You can get a similar behavior with async tests, but _only_ by awaiting the `t.test()` calls.

```js
const t = require('tap')
;(async () => { // kludge until we get top-level await
console.log('before child 1')
await t.test('child 1', async t => {
  console.log('before child 1 test point')
  t.pass('test point')
  await new Promise(resolve => setTimeout(resolve, 100))
  console.log('after child 1 test point')
})
console.log('before child 2')
await t.test('child 2', async t => {
  console.log('before child 2 test point')
  t.pass('test point')
  await new Promise(resolve => setTimeout(resolve, 100))
  console.log('after child 2 test point')
})
console.log('after children')
})()
```

```
before child 1
TAP version 13
before child 1 test point
# Subtest: child 1
    ok 1 - test point
after child 1 test point
    1..1
ok 1 - child 1 # time=109.072ms

before child 2
before child 2 test point
# Subtest: child 2
    ok 1 - test point
after child 2 test point
    1..1
ok 2 - child 2 # time=104.723ms

after children
1..2
# time=223.731ms
```
