### ISSUE TITLE
--bail does not exit async functions

### ISSUE THREAD

**Issue by andykais** [tapjs/tapjs#778]
a simple example:
```ts
import * as tap from 'tap'

tap.test('async test', async t => {
  t.equal(0, 1)
  await new Promise(resolve => setTimeout(resolve, 5000))
})
```

the test will show `Asserts:  1 failed,...` when the assertion is reached, but will not actually exit the test. It will continue until the promise has resolved. I know this because adjusting the timeout (set for 5 seconds  in the example above) to any number will also shift the amount of time tap takes to complete the test.

I would imagine that --bail should cause `t.equal` to just throw an exception which would short circuit the test. Is this not how it functions?

**Comment by isaacs** [comment]
Yes, it was just printing the `Bail out!` line, but not actually throwing or reliably exiting the process.  Will be changed on the next v18 release.  `npm i tap@pre` to get it, but be sure to read through the [changelog](https://node-tap.org/changelog/#18.0), as there have been a lot of updates.

**Comment by isaacs** [comment]
I suspect this issue was due to some weirdness with in the combination of istanbul and possibly the source-map-support module.

Both of those are replaced with their node and V8 built-in descendants, and this seems to no longer be a problem, on tap 18.

`npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.

**Comment by isaacs** [comment]
Sorry, left comment on the wrong issue 😅
