### ISSUE TITLE
Object diffing omits some differences.

### ISSUE THREAD

**Issue by conartist6** [tapjs/tapjs#779]
I have a test that uses `matches` to do a shallow comparison between two objects. The objects have the right keys, but multiple values are different than they should be. Only one difference is shown. [here](https://runkit.com/conartist6/616c8db3060c230009387635) is a repro.

As you can see the actual diff output is:
```diff
--- expected
+++ actual
@@ -1,4 +1,4 @@
 Object {
   "first": "foobar",
-  "second": "foobar",
+  "second": "bar",
 }
 ```

But I expect to see two differences! In fact `first` is `"foo"`, which is not the expected `"foobar"`. This diff fragment makes it appear that the value of `first` is correct, when it is not.

**Comment by conartist6** [comment]
That the test prints only the expected object and the diff (but never the actual object) makes this particularly tricky if you don't already understand what you're seeing.

**Comment by isaacs** [comment]
That is because `t.match()` does substring checking.  So you can do something like, `t.match(veryLongString, shortBitItMustContain)`.  Since `foo` appears within `foobar`, that's actually passing.  But `foobar` does not appear within `bar`, so that part fails.

You might prefer to use `t.has()` if you want to check for equality of all specified strings, without the fuzzy matching.
