### ISSUE TITLE
Async --before

### ISSUE THREAD

**Issue by 112RG** [tapjs/tapjs#788]
I am trying to setup mongodb-memory-server. In my --before file

```
const { MongoMemoryServer } = require('mongodb-memory-server')

async function run() {
  const mongoServer = await MongoMemoryServer.create()
  process.env.MONGO_URL = mongoServer.getUri()
}

run()
```
But it seems to just get stuck running. The mongodb server is spawning but I guess not continuing properly? I think this is because I have not fully understood async. I am coming from jest where this code worked. So just wondering how I could get it ro work on node-tap. Any help would be great

I did find the issue where you would spawn the process and save its pid. I would like to not do that and use mongodb-memory-server if possible.

**Comment by isaacs** [comment]
This isn't actually about anything being "async" per se.  The issue is that every file in tap's runner is run in a completely new process, _including_ your `--before=<module>` argument.

Think of it like doing `node mongo-memory-server.js && node test.js`.  If the first never exits, the second never runs.

So, it's waiting for that process to exit before continuing to run the rest of your tests.  Since it never exits, the test suite never continues.  Also, setting something in the environment won't do anything, since your tests have a different `process.env` than the `--before` script ;)

Since you actually want this to be running _in the same process_, you need to kick it off in your test itself.  Like this:

```js
// test/fixtures/mongo-memory-server.js
const { MongoMemoryServer } = require('mongodb-memory-server')

let mongoServer
module.exports.run = async () => {
  mongoServer = await MongoMemoryServer.create()
  process.env.MONGO_URL = mongoServer.getUri()
}
module.exports.stop = () => {
  if (!mongoServer) {
    return
  }
  mongoServer.destroy() // or .close(), or whatever, idk this module
  mongoServer = null
  delete process.env.MONGO_URL
}
```

```js
// test/do-something.js
const { run, stop } = require('./fixtures/mongo-memory-server.js')
const t = require('tap')

// run the server before running any tests, this will await the promise
t.before(run)

// kill it when we're done with all our tests so that the test exits gracefully
t.teardown(stop)

t.test('some test', async t => {
  // server is running now...
})
```
