### ISSUE TITLE
doesn't handle custom error when use in mock

### ISSUE THREAD

**Issue by PatrickGonthier** [tapjs/tapjs#794]
Hi,

I'm trying to mock a function and i want it to throw my custom error. But when i check the instance in my code, it doesn't have the good instance

```
class CustomError extends Error {
      constructor() {
          super();
          Object.setPrototypeOf(this, CustomError.prototype);
      }
  }

    const error = new CustomError();

    console.log(error instanceof CustomError); // Will log 'true'

    const myController = t.mock('.,/src/Controller', {
      '../src/Service.js': {
        getId: () => {throw error; }
      },
    });
    const response = await myController.getProduct();
```

if i console log the error in the getProduct part  i get that the instance is Error and not CustomError

**Comment by isaacs** [comment]
Are you sure it's not an instance of CustomError?  You're not setting the `name` field, so it may just be logging as `Error`, even though it is in fact a CustomError object.  (That is how Error classes identify themselves.)

```js
// bar.js
module.exports = {
  doSomething: () => console.log('bar doing something')
}
```

```js
// foo.js
const bar = require('./bar.js')
exports.callBar = () => bar.doSomething()
```

```js
const t = require('tap')

t.test('throw custom error', async t => {
  class CustomError extends Error {}
  const error = new CustomError('ok')
  t.comment(error instanceof CustomError); // Will log 'true'
  t.type(error, CustomError); // passes
  const foo = t.mock('./foo.js', {
    './bar.js': {
      doSomething: () => { throw error },
    },
  })
  t.throws(() => foo.callBar(), error) // passes
  try {
    foo.callBar()
  } catch (er) {
    t.comment(er instanceof CustomError)
    t.equal(er, error) // passes
  }
})

/*
TAP version 13
# Subtest: throw custom error
    # true
    ok 1 - type is CustomError
    ok 2 - expected to throw: Error ok
    # true
    ok 3 - should be equal
    1..3
ok 1 - throw custom error # time=3.989ms

1..1
# time=5.812ms
*/
```

Maybe try defining your custom error like this:

```js
class CustomError extends Error {
  constructor (message) {
    super(message)
    this.name = 'CustomError'
    // Object.setPrototypeOf is unnecessary, that is already
    // how classes work, and will trigger de-opts in V8
  }
}
```

**Comment by filmaj** [comment]
Hello @isaacs , I stumbled upon an issue in the same vein here. I had to expand your example a little bit, but I put together a repro here: https://github.com/filmaj/tap-mock-instanceof

I think the issue is some interaction between how mocking works in tap, and how node does `instanceof` comparisons. In the repro, the code-under-test has a reference to the `CustomError` and does things conditionally if it encounters the custom error vs. a generic one - a pretty standard pattern in node code, I think. However, once you introduce mocking, I think the actual instances of `CustomError` as `import`ed in the test vs. the one that exists within the source-under-test are different. I noticed that tap uses some kind of querystring import-cache-busting thingo to enable mocking (inferring this based on stack traces)? maybe that somehow comes into play.

**Comment by isaacs** [comment]
Yes, the mock module and the unmocked module are _different code_, running in different module scopes, so the two objects are different.

If you're using `obj instanceof SomeClass`, and the obj comes from a mocked module, but the function doing the testing _isn't_ using the mocked module, then it's going to (correctly) report `false`. Because it's not an instance of that thing, it's an instance of the one from the module stack that's using the mocks. That's a different function, with different deps, different scopes, etc.

So in the example cited, the _second_ time you load `foo.js`, it loads a _brand new copy_ of `customerror.js`, which uses all of the mocks you provided.

Think about it, and you will see that not only is this working as intended, this is logically the _only_ way it possibly _could_ work.

Let's say that `customerror.js` had something like this:

```js
import { homedir } from 'node:os'

class CustomError extends Error {
  home: homedir()
}
```

And then the behavior in `foo.js` was:

```js
import { CustomError } from './customerror.js'
export const foo = () => {
  try {
    throw new CustomError('wee!')
  } catch (er) {
    if (er.home === '/Users/isaacs') {
      // it is ok if we are on isaacs machine
    } else {
      throw er
    }
  }
}
```

Now let's say you want to test this. Clearly, you'll need to see what happens when `homedir()` reports `'/Users/isaacs'`.  So you do this:

```js
const isaacs = await t.mockImport('./foo.js', {
  'node:os': t.createMock(await import('node:os'), {
    homedir: () => '/Users/isaacs'
  }),
})
const filmaj =  await t.mockImport('./foo.js', {
  'node:os': t.createMock(await import('node:os'), {
    homedir: () => '/home/filmaj'
  }),
})
t.thows(() => filmaj.foo())
t.doesNotThrow(() => isaacs.foo())
```

The only way that this could possibly work if the `foo.js` module got a `customerror.js` module that got the specified `node:os` mock. _They cannot be the same thing._ Each `t.mockImport` call provides a module with a completely unique and isolated module dependency graph.

This isn't just about busting the import cache to reload the module fresh. It is actually required for the feature to behave according to its intended design, in even the most basic case.

**Comment by filmaj** [comment]
I ended up `import * as errors from './mycustomerrors.js'` at the top of the test file and feeding the errors in as a "mock" for the source-under-test. Then the test can build error instances up to capture/inject as needed to exercise various code paths.

This all still feels weird. FWIW the native node test runner's mocking affordances are a little different (you don't mock module imports as you do in tap, but rather mock a module's exports) but the following works (requires node v24 with the `--experimental-test-module-mocks` flag):

```javascript
import { test } from 'node:test'
import {CustomError} from './customerror.js'

test('hi', async (t) => {
  const error = new CustomError('ok')
  const barMock = t.mock.module('./bar.js', {
    defaultExport: { doSomething: () => {
      throw error
    } }
  })
  const foo = await import('./foo.js')
  t.assert.throws(() => foo.callBar(), error) // passes
  try {
    foo.callBar()
  } catch (er) {
    t.assert.equal(er, error) // passes
  }
})
```

**Comment by isaacs** [comment]
Yeah, that's functionally equivalent to:

```js
import { CustomError } from './customerror.js'
const error = new CustomError('ok')
const foo = await t.mockImport('./foo.js', {
  // use the same module in the mocked world so instanceof works
  './customerror.js': { CustomError },
  './bar.js': {
    doSomething: () => { throw error },
  },
})
t.throws(() => foo.callBar(), error) // passes
try {
  foo.callBar()
} catch (er) {
  t.equal(er, error) // passes
}
```

Note that node's mocking _doesn't_ handle cases as cleanly where you need to mock transitive deps and see the results further up the stack.
