### ISSUE TITLE
Why is coveralls not a dev dependency?

### ISSUE THREAD

**Issue by drazisil** [tapjs/tapjs#795]
Apologies if this has been discussed prior, I was unableto find an issue regarding it.

Is there a reason that the `coveralls` module is not a dev dependency? I understand that @isaacs likes and uses it, but I am unclear why it is required for the usage of `tap`, coverage generation is covered by `nyc`, correct?

_questions and comments on this account are not related to my work and are personal only_

**Comment by bcomnes** [comment]
Tap includes a coveralls reporter built in.

**Comment by isaacs** [comment]
I don't actually use coveralls, myself.  We've been planning on removing the coveralls reporter at some point, since it seems to not be very well maintained, brings in a bunch of deprecated modules, etc.  But it is properly a "dependency" (as in, "used for some actual real features") and not a "devDependency" (as in, "used in the development of tap itself".)  I guess we could move it to an optional peerdep in the next major?

**Comment by bcomnes** [comment]
+1 on removing/making optional for all the reasons you mentioned. Looks like coveralls is maintaining a [GitHub action](https://github.com/marketplace/actions/coveralls-github-action) now in favor of their travis stuff (from a maintenance perspective).
