### ISSUE TITLE
Support Mutation Testing use case

### ISSUE THREAD

**Issue by nicojs** [tapjs/tapjs#801]
We want to support node-tap for mutation testing with StrykerJS, see the issue on our side: https://github.com/stryker-mutator/stryker-js/issues/325. 

During mutation testing, the test suite is executed 1000s of times. I know we can simply import any test file and let the tests be executed, but that is bad for performance. In fact, this would already be supported with the [command test runner](https://stryker-mutator.io/docs/stryker-js/configuration#testrunner-string). 

In order to improve performance, we need a programmable API that looks something like this:

```ts
// Code below is pseudo-code to illustrate our needed API. 
const { Tap } = require('node-tap');

const tap = new Tap();

// runInBand in order to share global variables with the test environment
await tap.readConfig({ overrides: 'here', runInBand: true, concurrency: 1 });

// register global hook: beforeEach, needed to determine coverage per test. We can also say a test file is a test instead (and use the filename as test name).
tap.beforeEach((test) => {
  global.__stryker__.currentTest = test.name; 
});

// Load the test files without running the tests. Or run the test once, but be able to rerun them without reloading the files
await tap.loadFiles();
const results = await tap.run();
// Results include the test names or test filenames including the test results (passed or failed).

// Grab coverage from a global variable 
const { mutationCoverage } = global.__stryker__;
// Determine test coverage per mutation.

// Test mutant 1:
global.__stryker__.activeMutation = 1;
const resultMutantOne = await tap.run({ testFilter: ['..array of test names to run for mutant 1'] });

// Test mutant 2:
global.__stryker__.activeMutation = 2;
const resultMutantOne = await tap.run({ testFilter: ['..array of test names to run for mutant 2'] });
```

Is there something that exists for this? Or is it something you guys would like to support? Thanks in advance.

**Comment by nicojs** [comment]
I did some more research. This is what I came up with. Please let me know if I am mistaken.

* Tests can only be identified by filename.
* There is no way to run "in-band" other than importing the files yourself, 
* When we would import all test files in a single process ourselves, it is impossible to know exactly which tests executed which code (code coverage per test wouldn't be possible), since tests can run `async` and start running as soon as a file is imported.
* When we would import all test files ourselves, we would also need to take care of stuff the `tap` cli takes care of. Like handling `--before` and `--after`, transpiling with ts-node or babel, selecting test files, etc.
* It seems to be impossible to rerun tests after they've been executed since the process that ran the tests is already closed.

**Comment by isaacs** [comment]
Yeah, I think "import tests instead of running in subprocs" is sort of a non-starter, tbh.  You also run into the issue that parallelizing tests gets tricky.  I've looked into this, somehow mocking out the process object and running in a Worker thread, but it would be a tremendous amount of work, especially to get all the stuff right with istanbul/nyc.

> When we would import all test files in a single process ourselves, it is impossible to know exactly which tests executed which code (code coverage per test wouldn't be possible), since tests can run async and start running as soon as a file is imported.

You can get coverage per-test by digging into the `.nyc_info/processinfo.json` data, that's how tap does `tap --changed` and such.  But yeah, if from NYC's pov it's all one big process, then... idk.  Seems like a lot of stuff to refactor there.

> When we would import all test files ourselves, we would also need to take care of stuff the tap cli takes care of. Like handling --before and --after, transpiling with ts-node or babel, selecting test files, etc.

What's worse, all those things assume that they're running in separate processes, can make changes to the filesystem, globals will be cleaned up, etc.

> It seems to be impossible to rerun tests after they've been executed since the process that ran the tests is already closed.

It's even worse than that.  Consider this perfectly valid tap test:

```js
const t = require('./')
t.plan(1)
const fs = require('fs')
fs.statSync('file-that-must-be-present')
t.pass('the file is there')
```

```
$ node f.js
TAP version 13
1..1
not ok 1 - ENOENT: no such file or directory, stat 'file-that-must-be-present'
  ---
  at:
    line: 1538
    column: 3
    file: node:fs
    function: Object.statSync
  stack: |
    Object.<anonymous> (f.js:4:4)
  errno: -2
  syscall: stat
  code: ENOENT
  path: file-that-must-be-present
  tapCaught: uncaughtException
  test: TAP
  ...

# failed 1 test
# time=14.29ms

$ touch file-that-must-be-present

$ node f.js
TAP version 13
1..1
ok 1 - the file is there
# time=1.427ms
```

Even knowing what to "re-run" is nontrivial.

Assuming you leave aside any concept of coverage, which tests ran which code, etc., I think maybe you _could_ do this by:

1. Emulating `process` in a Worker thread.  (Wildly nontrivial.)
2. Using these emulated "worker as subprocess" environments to run each test.
3. Wrap the test code in something like
    ```js
    t.test(filename, t => {
      global.__stryker__.childTap = t
      t = undefined
      /* mock require here so require('tap') returns stryker's childTap */
      /* also define exports, module, global, process, ... so those work */
      ${testFileContents}
    })
    ```

To get to "which test ran which code", you'd also need to make NYC aware of these fake subprocess things.  Which means that in your worker-mocked subprocs, you'll _also_ need to patch child_process.ChildProcess so that any `spawn(node, ...)` calls get opened in one of these memory sandboxed worker-mock subprocs.

You begin to see why I have backed away from this every time I considered it.  It would be a performance improvement even if you aren't running tests 1000s of times, but just... oof.  So complicated.  And child processes give you all of this for free, any of which we'd be bound to screw up at some point: completely clean slate memory, exactly the same runtime env as running `node test.js`, a `process.pid` and `process.env` that match the actual environment, optimized crash isolation and memory protection via the kernel, and because "run a child process" is the first-class way to do things, that means you can run _other_ tests or programs in child processes and coverage and everything will keep being tracked, making tap nearly ideal for testing cli applications end to end.

It's kind of tap's killer feature, tbh.  People run into these footguns with other "faster" test platforms and then come to tap because it's safer and easier to reason about.

I'd recommend looking into the way that NYC is integrated with tap.  See if you can get by with just a `-r` argument to node, and dumping out some data into a folder.  Then just go ahead and run the test processes 1000s of times, see how bad it is.  This is the "shallow integration" approach that might work.

But, you really don't have to mutate _the tests_, right?  Just the code that they're loading.  So another alternative, is that we integrate it _deeper_, and instead of just `$ stryker npm test`, we do something like this:

```js
// age-check.js
module.exports = (age, minAge) => {
  if (age < minAge) {
    return false
  }
  if (age > minAge) {
    return true
  }
  // untracked mutant bug at age === minAge
}
```

```js
const t = require('tap')

// if you set some config, then we do the mutation stuff, running
// up to the configured number of times.
// the first run, we go straight through as normal, test failure stops the mutant hunt
// on subsequent runs, we apply mutations to any files loaded via t.mock()
// and ensure that running the test file _fails_ (if it passes, that's a live mutant)
t.test('sentinel', { mutationIterations: 1000 }, async t => {
  const ageCheck = t.mock('./age-check.js')
  t.equal(ageCheck(16, 21), false)
  t.equal(ageCheck(25, 21), true)
})
```

The downside is that mutation tracking would depend on using `t.mock()` to load modules, and making other edits to the tests themselves, instead of just running the process with the stryker cli.  But on the upside, we're _already_ loading the mocked modules by reading the code and executing it, and then throwing it away when we're done, so all you have to add is the mutating transpiler.

**Comment by isaacs** [comment]
Oh! Also, if we did the deep integration, you could maybe set defaults for these configs via environment vars, and then `$ stryker tap test.js` could just set those envs and run as normal.

One question remains though, since the root TAP object is also a TAP.Test, you can do this:

```js
const t = require('tap')
const foo = t.mock('../foo.js')
t.equal(foo.bar(), 'true')
```

I'd probably say that if the root tap object tries to do a mutating mock() load, we just throw, say "sorry, that's not allowed, put it in a child test", or something.

Maybe print a warning or something if we _are_ doing mutation testing and you _don't_ call t.mock ever?  Because what are we even mutating?  Idk, could be noisy, if you have some tests that do and some that don't need to?

Also a question:

```js
t.beforeEach(cleanup)
t.test('foo', { strykerBlahBlah }, t => {
  makeItDirty()
})
```

Do we run the cleanup before each stryker iteration?  I think we do.

**Comment by nicojs** [comment]
Thanks a lot, @isaacs . This is all very useful. Really appreciate you taking the time to answer my questions.

All in all, I think I want to step away from the idea of running tests in the same process and take the performance hit of multiple processes. But I think we can still use the "coverage per test" idea on a test file level. I will outline my plan, but first, let me explain how Stryker works on a high level.

## High level Stryker workings

### Step 1: code instrumentation

When you run Stryker on your project, Stryker will first load the files to be mutated. It will mutate those files, placing _all mutations_ into the code at once. But Stryker is smart about it.

This:
```js
function add(a, b) {
  return a + b;
}
```

Becomes (simplified):
```js
function cover(id) {
  if (global.__stryker__.activeTest) {
    global.__stryker__.mutantCoverage.perTest[global.__stryker__.activeTest][id]++;
  }
  else {
    global.__stryker__.mutantCoverage.static.[id]++;
  }
}

function add(a, b) {
  if (global.__stryker__.activeMutant === 0) {
    // 👾
  } else {
    cover(0);
    return global.__stryker__.activeMutant === 1
      ? a - b // 👽
      : (cover(1), a + b);
  }
}
```

This is called mutant schemata (or mutation switching). All mutants are in the code, but only one can be active at once. This allows performance optimization like compiling only once and running tests in the same process (for other test runners).

As you can see, we don't rely on Istanbul code coverage. Instead, we instrument the mutant coverage directly into the source file.

### Step 2: dry run

During this step, Stryker tries to run the code without mutations active. Tests should pass here. It validates that we didn't break anything, as well as allows us to determine the code coverage per test (also some other things, but that's not important here).

Normally, we would want to hook into the test framework's `beforeEach` hook, so that we can switch the `global.__stryker__.activeTest`, to record mutant coverage per test. But that won't work for node-tap as you've clearly outlined.

### Step 3: mutation testing

During this step, we want to run the tests that cover a particular mutant while it is active. This is done in parallel for speed (also using worker processes, indeed, worker threads are a hassle). 

After that, it generates a nice mutation test report you can open in a browser.

## My plan

One of the biggest performance benefits Stryker brings is its mutant coverage per test. A mutant that isn't covered at all is directly reported as `Survived` (via `NoCoverage`). If a mutant is covered by 1 test, only that test is run for that mutant. Etc. 

I think we can do that for node-tap as well, at least on the test-file level.

### dry run plan

During the dry run, I'm thinking to run the tests with `tap --node-arg "--require" --node-arg "./record-coverage.js" --no-cov --bail -r ./stryker-reporter.js` . The record-coverage magic looks a bit like this:

```js
// record-coverage.js
const fs = require('fs');
global.__stryker__ = global.__stryker__  || {};
const currentFile = process.argv.slice(-1)[0]; // current file seems to be passed last by node-tap
global.__stryker__.activeTest = currentFile;
process.on('exit', () => {
  const covFile = `${currentFile}.json`;
  fs.writeFileSync(covFile, JSON.stringify(global.__stryker__.mutantCoverage));
});
```

As you can see, when the child process exits, it neatly writes the coverage info to a json file (we could also try `process.send` instead, TBD). From the test runner plugin, we can then scrape up those files and report the full-coverage back to Stryker, together with the test results we can find using our own using our custom `stryker-reporter.js` 

### mutation testing plan

During mutation testing, I'm thinking to run the tests with `__STRYKER_ACTIVE_MUTATION__=1 tap --jobs 1 --no-cov --bail -r ./stryker-reporter.js test-that-covers-mutant-1.js other-file-that-covers-mutant-1.js` . The active mutant is switched on using the `__STRYKER_ACTIVE_MUTATION__` env variable, which is an alternative for the `global.__stryker__.activeMutant`. We use `--jobs 1` here, because StrykerJS already uses parallel workers during mutation testing.

All in all, I think this is pretty simple to implement. How it will perform remains to be seen. Not very well I think, but then again, how many big node-tap projects are there?

@isaacs do you see any problems with this approach?

Another question: would you be open to opening up the node-tap CLI for programmatic use? That would save us the hassle of calling `tap` in a child process, instead we could do something like this:

```ts
const { runCli } = require('tap/cli');
await runCli(['--jobs', '1', '--no-cov', '--bail', '-r', './stryker-reporter.js', 'test-that-covers-mutant-1.js', 'other-file-that-covers-mutant-1.js'])
```

It would also make it easier to communicate with the Stryker reporter instance since it is run in the host process.

**Comment by isaacs** [comment]
> `const currentFile = process.argv.slice(-1)[0]; // current file seems to be passed last by node-tap`

You can run into trouble if you provide `test-arg` options.

```
$ cat args.js
console.error(process.argv)

$ cat require.js
console.error('i got required')

$ tap --test-arg=foo args.js --node-arg=--require --node-arg="./require.js" -C --no-cov
TAP version 13
i got required
[ '/usr/local/bin/node', '/Users/isaacs/dev/tapjs/tap/args.js', 'foo' ]
ok 1 - args.js # SKIP no tests found {
    1..0 # no tests found
}

1..1
# skip: 1
# time=41.206ms
```

I think what you really want is just `process.argv[1]`.

> Not very well I think, but then again, how many big node-tap projects are there?

I can think of [a few](https://github.com/npm/cli) 😝

> @isaacs do you see any problems with this approach?

Mostly just performance.  Losing parallel testing will be a pretty big hit.

> would you be open to opening up the node-tap CLI for programmatic use?

Not opposed in principle, but it's not really designed to be used that way.  I would expect to have to refactor out some assumptions where we expect that it owns the process.

It might be worth exploring taking over the runner entirely, and interfacing with [libtap](https://github.com/tapjs/libtap)?

**Comment by nicojs** [comment]
Thanks for your reaction @isaacs 

> I think what you really want is just `process.argv[1]`

Great! Didn't know the main file is always the first argument. Thanks for pointing that out to me.

> Mostly just performance. Losing parallel testing will be a pretty big hit.

I don't think so. Say we need to test 100 mutants and thus run the tests 100 times. It doesn't matter if StrykerJS spins up 1 tap test runner with `--jobs 8` or 8 test runners with `--jobs 1`, right? The gross time should be about the same.

> Not opposed in principle, but it's not really designed to be used that way. I would expect to have to refactor out some assumptions where we expect that it owns the process.

Yes. I tried creating a `runCli` function, but it is very hard. The bin/run.js file is pretty big, with a lot of `process.env` and `process.on` magic. I don't know where to begin honestly.

> It might be worth exploring taking over the runner entirely, and interfacing with `libtap`?

How would that look exactly? End users import directly from `tap` right? How could i interface with `libtap`?

> I can think of [a few](https://github.com/npm/cli) 😝

Yeah... I see your point 😊

I'm now thinking to maybe make a bare bones runner that simply runs the test files in isolated child processes without the use of `node-tap`. One of the design goals of `node-tap` is to be able to simply to run the test file directly, right? It feels like a waste to not use that to our advantage. If users want to JIT transpile files with `ts-node` or something, we can still allow to do that by let you configure a `--require` for it, basically mimic a bare bones `node-tap`, but without a lot of the bells and whistles. We could educate users to transpile their code only once by using a [`--buildCommand`](https://stryker-mutator.io/docs/stryker-js/configuration/#buildcommand-string) to improve performance.

@isaacs do you see problems with this approach?

**Comment by nicojs** [comment]
🎉 We've implemented tap runner support using the design I outlined in my previous comment.

You can review the docs here: https://stryker-mutator.io/docs/stryker-js/tap-runner/. A blog article about this release will be published next Monday.

@isaacs thanks again for all the help! 

As proof it works, here is a report of `rimraf`: [rimraf-report.zip](https://github.com/tapjs/node-tap/files/11644291/rimraf-report.zip)
I'm pretty happy with the performance, taking ~3 minutes on `--concurrency 8`. If you want I could add a PR to run mutation testing on rimraf in a CI pipeline.
