### ISSUE TITLE
Is it possible to connect and disconnect to a service inside Before and After

### ISSUE THREAD

**Issue by agjs** [tapjs/tapjs#815]
Hey guys. Before everything, thanks for an amazing library, highly appreciated.

I'm building an API with Fastify and mongoDB. After writing some unit tests, I've noticed that in every single test for a different resource, I'm connecting and disconnecting mongoDB in beforeEach and afterEach. 

 I wonder, is there a way to open a connection in --before file, share the instance somehow with the tests and disconnect in --after? This would remove a lot of repetition and possibly, help with some other third party services. If this isn't possible, is there any other way to reuse a connection, without repeating this logic nearly in all the tests.

Thanks in advance.

**Comment by isaacs** [comment]
Since the `--before` and `--after` methods run in separate processes, not really any way to share the js connection object itself. 

You can set it in a t.before() instead of t.beforeEach(), so at least it's only once per test file, instead of per each test method. 

If the server is far away, you can have a before file that starts a proxy on local host or something, in a background process, and saves the pid to a file. Then an after module that kills the child process with that pid. But that's kind of complicated and maybe not worth it. And anyway, if you want `node test.js` to work, your tests may have to handle the case where before.js hasn't been run. This usually isn't so bad, since you can just run the before.js before running tests directly. 

Last suggestion, you could mock the upstream server, and have a mode where your mock is actually a proxy that saves responses. So, eg, when you do `TEST_PROXY=1 node test.js`, the proxy on local host saves upstream responses. When you run `node test.js`, it returns results from cache. A connection to local host is pretty fast, and then it's deterministic on ci.

**Comment by agjs** [comment]
> Since the `--before` and `--after` methods run in separate processes, not really any way to share the js connection object itself.
> 
> You can set it in a t.before() instead of t.beforeEach(), so at least it's only once per test file, instead of per each test method.
> 
> If the server is far away, you can have a before file that starts a proxy on local host or something, in a background process, and saves the pid to a file. Then an after module that kills the child process with that pid. But that's kind of complicated and maybe not worth it. And anyway, if you want `node test.js` to work, your tests may have to handle the case where before.js hasn't been run. This usually isn't so bad, since you can just run the before.js before running tests directly.
> 
> Last suggestion, you could mock the upstream server, and have a mode where your mock is actually a proxy that saves responses. So, eg, when you do `TEST_PROXY=1 node test.js`, the proxy on local host saves upstream responses. When you run `node test.js`, it returns results from cache. A connection to local host is pretty fast, and then it's deterministic on ci.

Thanks a lot for taking the time to respond, @isaacs. Based on what you wrote, it seems it would take maybe a bit too much effort and time getting around this. Due to that, I'll just continue with the repetitive, but a simple way.

Cheers and thanks again.

**Comment by isaacs** [comment]
Much good to be said for repetitive and simple, in tests at least 👍
