### ISSUE TITLE
How to augment TypeScript definitions for custom assertions?

### ISSUE THREAD

**Issue by paambaati** [tapjs/tapjs#833]
When adding a new custom assertion with the `tap.Test.prototype.addAssert()` method, how does one augment the TS definitions to support this new assertion?

```typescript
// modules.d.ts -> added to tsconfig.json -> compilerOptions -> types

import 'tap'

declare module 'tap' {
    export namespace Tap {
        export class Test {
            shouldDoThisNewThing(name: string, cb?: (t: Test) => Promise<void> | void): Promise<void>;
        }
    }
}
```

This doesn't seem to work.

**Comment by isaacs** [comment]
I'm honestly not sure how to do this in tap 16.

The answer (as you know) for the next version will be "Make it a plugin, and it Just Works".

**Comment by paambaati** [comment]
@isaacs Yeah, I think we can close this one out once tap 18 lands.

**Comment by isaacs** [comment]
`npm i tap@pre` to get it. Check out the [changelog](https://node-tap.org/changelog/#18.0) first, though, a bunch of stuff has been updated.

**Comment by shfrmn** [comment]
@paambaati If it's still relevant, [here's how I made it work](https://github.com/shfrmn/tap-fast-check/blob/master/src/index.ts) for a custom `fast-check` assert.

Minimal example:
```typescript
export {}

declare global {
  export namespace Tap {
    export interface Test {
      customAssert(this: Tap.Test, customArg: any, message: string): boolean
    }
  }
}
```

------

Detailed explanation to save you time:

### `export {}`
Augmenting global scope requires a module, meaning the minimal working type declaration **must have at least one export statement** even if you don't have anything to export. 

### `this: Tap.Test`
If your custom assert needs any of built-in `tap` methods, `this` is bound to the relevant `Tap.Test` context - see example in Tap docs on [this page](https://node-tap.org/docs/api/advanced/). However, when you attempt to access `this`, TypeScript will complain about `this` having implicit `any` type (in strict mode). Adding a fake `this` parameter to the function type signature is the official way to explicitly type it, [as documented here.](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#this-parameters-in-callbacks)

Also it goes without saying, you can't use an arrow function if you need `this`.

### tsconfig
As mentioned by @isaacs [here](https://github.com/tapjs/tapjs/issues/697), providing tsconfig path to `ts-node` will only be possible in the next major version (18). This means, for example, you will not be able to turn off `noImplicitThis` (especially if your tsconfig has a custom name or not located in the project root).

### File extension
Put your type declaration in a `.ts` file and import it straight to tests with a normal `import` statement. Don't waste time on setting `typeRoots` or `paths` in tsconfig, because whatever you do in tsconfig will not affect `ts-node` used by `tap`.
