### ISSUE TITLE
Use mock in fastify

### ISSUE THREAD

**Issue by thomcom** [tapjs/tapjs#846]
Hiya! I'm using `tap` with `fastify` and having a problem with mocking a module within the fastify execution environment.
I need to mock the default `public` directory filepath, which is just a property of `gpu_cache` as I'm working on a refactoring that works with mock.

```
test('read_json file good', {only: true}, async (t) => {
  const dir   = t.testdir(json_good);
  const rpath = '../../test/routes/' + dir.substring(dir.lastIndexOf('/')) + '/json_good.txt';
  const build = t.mock('../../routes/graphology/index.js',
                       {'../../util/gpu_cache.js': {publicPath: () => rpath}});
  const app   = await build(t);
  const res   = await app.inject({method: 'POST', url: '/graphology/read_json?filename=' + rpath});
  const release = await app.inject({method: 'POST', url: '/graphology/release'});
  const payload = JSON.parse(res.payload);
  console.log(payload);
  t.equal(payload.message, 'File read onto GPU.');
  t.equal(payload.success, true);
});
```

The module typically looks in the `public` folder for resources that can be loaded, but in order to use file fixtures with `t.testdir` I need to mock the `publicPath` function to point to the fixture url instead of the `public` folder. Previously to make the test pass I required that the caller specify the full relative path to the resource, but now that I'm using the `public` folder I need to mock the directory.

The problem is that the rest of the `fastify` environment doesn't appear to get created if I use `t.mock` - only the module that is being mocked. Is there a workaround for this other than creating a private method to set the resources path so I can use the test directory?

Thanks!

**Comment by isaacs** [comment]
so, if I understand it correctly, `build(t)` is loading fastify, but the modules within fastify aren't being loaded at all?  Or they're loading, but not getting the mocked version of `gpu_cache.js`?  What error are you seeing?

Any modules required by the mocked module should be loaded such that they will pull in the mocks rather than the "real" files on disk that they mock.  So it may be that either there's a bug, or fastify is loading things in a way tap doesn't yet support.  (In particular, I'm thinking this might be the case becase anything loaded with `import()` will escape from the mocked environment, because it only mocks `require`.)

**Comment by shyd0w** [comment]
> so, if I understand it correctly, `build(t)` is loading fastify, but the modules within fastify aren't being loaded at all? Or they're loading, but not getting the mocked version of `gpu_cache.js`? What error are you seeing?
> 
> Any modules required by the mocked module should be loaded such that they will pull in the mocks rather than the "real" files on disk that they mock. So it may be that either there's a bug, or fastify is loading things in a way tap doesn't yet support. (In particular, I'm thinking this might be the case becase anything loaded with `import()` will escape from the mocked environment, because it only mocks `require`.)

Hello, i just started a fastify project and I am using imports currently and not require. That being said, I wanted to follow up and see if there was a timeline around getting mocks to work with import as, I currently cannot mock anything with tap. Do you think using [require-inject](https://www.npmjs.com/package/require-inject) will solve this issue?

**Comment by isaacs** [comment]
`require-inject` uses the same technique as `t.mock` (in fact, `t.mock` is largely based on require-inject).

But I believe something like [quibble](https://stackoverflow.com/questions/71310032/how-to-mock-esm-modules-functions-with-quibble) would work.

Follow along at #821 to watch the progress of the next tap semver major that will include this.

**Comment by shyd0w** [comment]
> `require-inject` uses the same technique as `t.mock` (in fact, `t.mock` is largely based on require-inject).
> 
> But I believe something like [quibble](https://stackoverflow.com/questions/71310032/how-to-mock-esm-modules-functions-with-quibble) would work.
> 
> Follow along at #821 to watch the progress of the next tap semver major that will include this.

Thank you so much! I will try this out! 

just FYI for reporting perspectives and also wanting to help as much as possible, I found out coverage also does not work due to this being a esm and not cjs. 

Aside from this, I also built a crazy script to basically convert it from esm (as a .js) to cjs (literally babel as well as renaming the extension to cjs) and that did work but, i would hate to upkeep this locally haha

**Comment by shyd0w** [comment]
also @isaacs please let me know if i can be any assistance! would love to help as much as possible 👍

**Comment by isaacs** [comment]
@shyd0w yeah, the best way to do coverage with tap for the time being if you're using esm and/or typescript, is to run your tests with `c8`, and turn off tap's built-in nyc coverage by putting `"tap": { "coverage": false }` in package.json   http://npm.im/c8

Of course, this means not having coverage checking, `--changed`, `--watch`, etc, which is a bummer.

**Comment by isaacs** [comment]
tap v18 is now available in prerelease!  (It'll be bumped to the `latest` dist tag once some ts-node stuff lands, in the meantime, it's installing from git which is hella slow to install, but otherwise works fine.)

`npm i tap@pre` to get it, definitely review the [changelog](https://node-tap.org/changelog/#18.0) as a lot of things have been updated.

To mock esm, you can use [`t.mockImport()`](https://tapjs.github.io/tapjs/classes/_tapjs_test.index.Test.html#mockImport).
