### ISSUE TITLE
How to mock fastify-plugin?

### ISSUE THREAD

**Issue by A2K12** [tapjs/tapjs#855]
Sorry, if anyone has posted this previously.
I am facing an issue while mocking plugins used for fastify server.

```
fastify.register(AutoLoad, {
dir: path.join(__dirname, 'routes'))
})
```
Without the routes plugin, I am able to mock routes but when a plugin is registered, I am not able to mock
If anyone has a solution please post it.
Thanks

**Comment by ShaxxKh** [comment]
**+** 1

**Comment by WhereJuly** [comment]
@A2K12

#### Do not mock routes

Basically you should not mock routes as they are the main moving part in your API i.e. exactly what you have to test.

Assuming your routes use a database you have to configure an SQLite in-memory database to be provided in unit-tesing environment instead of a normal on-disk database for isolation's sake and perfomance purposes. As well prepare and use a test case specific DB seeders to imitate a data for test cases.

If you have the routes calling the external services (API, email) you have to mock their respective adapters (e.g. with Sinon, injecting those directly into a route constructor or using DI container to manage dependency injection).

The business logic you may want to use must be completely isolated from the API controllers by encapsulated it in the respective obects. This would give you a possibility to unit test / TDD it with no depending on your routes' controllers.

#### Mock routes' controllers

In case you stilll would like to mock the routes' controllers you have to replace the hardcoded `routes` folder name in the code above with the dynamically defined folder name based on the `NODE_ENV` environment variable value. For this you have to create and engage some configuration intermediary between you initialzation code and your routes code that would detect the environments and assign the desired path for routes. Something like:

``` javascript
// Somewhere in server intialization module.
import config from 'Config'

fastify.register(AutoLoad, {dir: config.routesFolder});

// In Config.ts, shortened for brevity
export default class Config {
  constructor() {
    const isTestingEnvironment = process.env.NODE_ENV === 'test';

    this.routesFolder = isTestingEnvironment ? `construct the respective path here` : `and here`;
  }
}
```

**Comment by isaacs** [comment]
I don't know much about fastify plug-ins or the routes plugin specifically. But my take in general is: export, factor, monkey patch, and mock whatever you want, to test the units you care to test. Integration tests are often the best, but they're not always enough. There are very few hard and fast rules. 

Tap v16 has a `t.mock()` method which can be used to `require()` any module and provide stand-ins for anything it loads. That's usually the most powerful tool for deliberate unit testing and hitting otherwise hard to reach code paths. 

In tap v18 (currently: `npm install tap@pre`), this is replaced with `t.mockRequire` and async `t.mockImport`, which work the same way, but the second one uses `import()` instead of require.
