### ISSUE TITLE
test fails without any useful info

### ISSUE THREAD

**Issue by KhafraDev** [tapjs/tapjs#864]
In undici, we frequently get tests failing in the ci that don't provide any info on how to fix or why the test was failed. For example https://github.com/KhafraDev/undici/actions/runs/4814119852/jobs/8571456976#step:14:13217

![image](https://user-images.githubusercontent.com/42794878/234721989-8ca1def1-1f91-492f-a08c-f557bbef6c74.png)

My best guess is *something* is being ref'd somewhere or some handle isn't getting closed, but since this only happens in the ci it's hard to debug. Is there an easy way to debug these issues or get more useful info about what's causing it to fail?

**Comment by isaacs** [comment]
Hm, the problem seems to be that it's happening on Windows, where `SIGTERM` is fatal and uncatchable.

What it's supposed to be doing is, whenever the test process receives a `SIGTERM`, dump information about any outstanding handles and refs: https://github.com/tapjs/libtap/blob/main/lib/tap.js#L178-L255

But on Windows, `SIGTERM` is effectively the same as `SIGKILL`, so nothing gets printed.  We need to use a different signal as the "timeout, dump handle info and fail asap" signal.

**Comment by isaacs** [comment]
Hm, looking into this, `SIGALRM` is the one we probably _should_ be using, since it literally means "A real-time timer has expired", and the default behavior is to terminate the process.

But alas, not supported on Windows.

**Comment by isaacs** [comment]
Ok, so it turns out that _all_ signal handling on Windows is just simulated and effectively an uncatchable shutdown with status code 1 for the three cases that it does support (SIGINT, SIGTERM, and SIGKILL).

So I think the only way to get the same kind of "report handles and forcefully exit" on Windows would be to spawn with an IPC channel and `process.send()` a termination signal.  Of course, that can be rather tricky to get right, especially if the test is using IPC for some other purpose.

Since the next version of node-tap is taking up more and more of my attention, I'm not particularly eager to dive into adding brand new semantic elements to work around shortcomings in the soon-to-be-old version of tap.  But I'm down to review a PR if you feel like digging into it.

The timeout signal handling logic is in libtap here: https://github.com/tapjs/libtap/blob/main/lib/tap.js#L178-L255

The signal gets sent in the `timeout` method of the `Spawn` class, here: https://github.com/tapjs/libtap/blob/main/lib/spawn.js#L143-L155

I am not sure why I used `SIGTERM` rather than the more semantically appropriate `SIGALRM`.  If the goal was to catch a user getting impatient and hitting `^C` then it should've been `SIGINT`. Probably just assuming that because it "worked" on Windows, it meant that it was supported the same way on both platforms.

So, I'd recommend the following:

- On Windows, always spawn() with an IPC channel.  When in Spawn.timeout, send a shutdown signal.
- On Windows, listen to `process.on('message')` rather than `process.on('SIGTERM')` for the timeout signal.

I'd suggest using `SIGALRM` rather than `SIGTERM`, but probably better to reduce the impact on the stable codebase. I'll update it to use `SIGALRM` on the new tap.

And, actually, moving forward in the new version, it'd probably be good for _any_ spawned child process to open an IPC channel with the parent process. That would be a nice way to send timeout information back _up_ to the parent, so that `t.timeout(60000)` can tell the parent, as it's always confusing that that doesn't let a test go for longer than the max set in the config or cli.

**Comment by KhafraDev** [comment]
FWIW it also seems to be happening on ubuntu - https://github.com/nodejs/undici/actions/runs/4877562393/jobs/8702312810?pr=2108#step:14:10571

I'll take a look at some point to implement your suggestions, but no promises 😄

**Comment by isaacs** [comment]
Yeah, using process IPC channels in this way has a bunch of gotchas.  Seems to be working on nextgen tapjs, but I obviously haven't really put that through its paces yet.

**Comment by isaacs** [comment]
Yeah, that is weird, but at least it's noting that it exited with SIGTERM now, instead of just `code: 1`.

This could be a clue?  Doesn't fix the tap issue, but might be a hint as to why it's timing out in the first place: 

> FakeTimers: clearTimeout was invoked to clear a native timer instead of one created by this library.
> To automatically clean-up native timers, use `shouldClearNativeTimers`.

Idk if that's expected, though.  But maybe a native timer is left dangling, in a way that tap doesn't know how to report?  (Or possibly something changed in `process._getActiveHandles()` and/or `_getActiveRefs()`, which wouldn't be too surprising, since those are not really officially supported APIs anyway.)

**Comment by isaacs** [comment]
Update on this:

Next major of tap will signal timeouts using IPC messages (and then if that fails, SIGALRM on Posix rather than SIGINT, which was always the semantically correct signal for such a thing, but still SIGKILL on Windows, because what can ya do? 🤷 Unix signals are a unix thing, after all.)

Also, if a test subprocess exits with a signal, it's properly treated as a failure, and reported with a red `❌ SIGALRM` in the top level output which is pretty nice. But again, not on Windows, because signal exits are just normal exits there.

**Comment by isaacs** [comment]
`npm i tap@pre` to get it. Check out the [changelog](https://node-tap.org/changelog/#18.0) first, though, a bunch of stuff has been updated.
