### ISSUE TITLE
Coverage report includes coverage of test files when their filenames do not match default include pattern

### ISSUE THREAD

**Issue by jordanbtucker** [tapjs/tapjs#881]
Take the files `main.js` and `main_test.js`.

```
tap run --coverage-report=html main_test.js
```

The outputted HTML will show an entry for `main.js` _and_ `main_test.js`.

![image](https://github.com/tapjs/tapjs/assets/468153/50f13dca-d2ff-4965-8b93-7540b2d7027c)

The same behavior occurs when using the `--include` argument with filenames that not match the default include pattern.

Compare that with the files `main.js` and `main.test.js`.

```
tap run --coverage-report=html
# The test filename is not required since it matches the default include pattern.
```

The outputted HTML will, correctly, only show an entry for `main.js`.

- tap@18.0.0-24
- Node.js@18.17.1
- Ubuntu 22.04.3 LTS on WSL2

**Comment by jordanbtucker** [comment]
After investigating, it looks like this might be an issue with c8 since I'm seeing the same behavior when using it directly.

**Comment by jordanbtucker** [comment]
Okay, so I figured out that c8 uses the same default excludes as istanbul (in fact it imports them), which excludes `.test.js` files but not `_test.js` files. c8 doesn't specify includes by default, so it looks like tap will need to feed an includes or excludes argument to c8 to fix this issue.

Presumably, all test files that tap finds should be added to c8's exclude argument.

**Comment by isaacs** [comment]
Slightly pedantic point, tap isn't using C8 to collect coverage, only to report on it (and that's only until I can pull out the Report class to use without the rest of C8's machinery, since it's kind of inflexible in how it streams the report out, see #877).

But you're right, it should definitely add any test file args to the exclusions handled by @tapjs/processinfo, though, in the same sort of way that it excludes `**/tap-testdir-*` and `tap-snapshots/**`.
