### ISSUE TITLE
Nest test dirs under a root

### ISSUE THREAD

**Issue by rotu** [tapjs/tapjs#883]
Test fixture directories are named `tap-testdir-something` but snapshots are under a `tap-snapshots/path/to/test`. It may make more sense to move the test fixtures to some `tap-testdir/` root and maybe to allow it to be outside the repository root.

This would allow easier manual cleanup (especially after running with `--save-fixture`) and make it easier to configure tools that have file system watchers.

originally mentioned here https://github.com/npm/template-oss/issues/348#issuecomment-1712019305

**Comment by isaacs** [comment]
Hm, that's a pretty good idea.

Snapshots were always kept in a single root location, because the expectation is that they'll stick around and get checked into git. Fixture dirs are usually transient, so it doesn't usually much matter where they are, but putting them _outside_ the test root (like in `/tmp` or something) often fails in CI environments that don't have write access to any other paths.

In any event, it's just a change to the `#getTestdir` method here: https://github.com/tapjs/tapjs/blob/main/src/fixture/src/index.ts#L130-L155 and you would still be able to override it with a config option if you wanted.

**Comment by rotu** [comment]
WOOHOO! I'll get off your lawn now :-)
