### ISSUE TITLE
turn of coverage

### ISSUE THREAD

**Issue by JamesKyburz** [tapjs/tapjs#906]
I can't find out how to turn off coverage since updating to v18.

Is there a way in v18?

```sh
/tmp/tapy ᐅ bat no-coverage.mjs
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: no-coverage.mjs
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ export default function noCoverage() {
   2   │   return null
   3   │ }
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/tmp/tapy ᐅ cat package.json | jq '.tap'
{
  "coverage-map": "no-coverage.mjs",
  "test-env": [
    "IS_TEST=true"
  ]
}
/tmp/tapy ᐅ npx tap
 PASS  test/double.js 2 OK 339ms


  🌈 TEST COMPLETE 🌈


Asserts:  2 pass  0 fail  2 of 2 complete
Suites:   1 pass  0 fail  1 of 1 complete

# No coverage generated
# { total: 2, pass: 2 }
# time=373.135ms

/tmp/tapy ᐅ echo $?
1
```

**Comment by isaacs** [comment]
If no coverage is generated, then nothing was tested. Tap is exiting with a `1` status code to indicate that it was not a successful test run. It's ok for _some_ suites in your test run to not produce coverage. But the run as a whole must cover something.

Do you have a use case for a test run that doesn't produce any coverage, but needs nonetheless to exit with a `0` status code?

**Comment by ert78gb** [comment]
I also would like to switch off the coverage, because in my cases I use tap and other e2e tester tool. Both tool together cover the huge part of the code.

**Comment by JamesKyburz** [comment]
I noticed that the documentation for v18 was published today with a [coverage](https://node-tap.org/coverage/) section.

Closing this issue as according to the docs "There is no way to disable this behavior."

**Comment by ert78gb** [comment]
Maybe it could be a feature request?

**Comment by isaacs** [comment]
It is a reasonable feature request, and I certainly don't mind having the discussion and considering cases where it might be worthwhile to not have coverage enabled.

(Technically, you CAN "disable coverage", albeit somewhat inconveniently with a null-returning coverage map, but the FR would be to have maybe a more convenient way to do that, and to make the runner not exit in error when no coverage is generated.)

**Comment by isaacs** [comment]
@ert78gb What are you using to verify that the code is fully covered?

**Comment by ert78gb** [comment]
We don't use anything.

We like the high test coverage, but most important the business process works or returns with proper error message, so we measure it instead of code coverage. This is why we mostly write e2e ui and service test and use unit test to check complex business calculation.

We use tap and es6 modules, by default tap 16 does not support coverage for es6 modules so currently we don't have 100% coverage on all project. For the easier upgrade would be better to switch off the coverage instead of add `c8 ignore` lines to the code. Or would be nice to change the coverage percent.

We have the use the latest tools and node version policy, but now we are in t(r)ap :) because we can't upgrade because the test fails.

Honestly, instead of write the missing test to reach the 100% coverage I migrated to node built in test runner some of our simple services or libs because it was more simple than write very tricky test of very special edge cases.
We still have to put tremendous effort to migrate everything to tap 18 or node test, so would be good if the tool would be less strict.

**Comment by isaacs** [comment]
How about a boolean option that would downgrade the `status=1` error exit with a big scary red warning?

Then your CI would pass, but it would still be unlikely that someone would miss the fact that their code isn't actually testing what they might think it is.

**Comment by ert78gb** [comment]
Just for the clarity, if this flag is "ON" then the coverage report will be visible and the status code will 0 on CI and local env too.

It is a good solution.

**Comment by isaacs** [comment]
Going to add two flags, actually.

* `--allow-incomplete-coverage` Don't fail if the coverage is incomplete, but still fail if there is _no_ coverage, since this likely indicates that something went Very Wrong in the test run.
* `--allow-empty-coverage` Don't fail if the coverage is completely missing, but if coverage is generated, still enforce that it is 100%, since this likely indicates that a coverage-generating test is incomplete.

If used together, effectively coverage results are completely ignored. In both cases, if the missing/incomplete coverage is allowed, it will still print the message about it, it just won't exit with `status=1`.

**Comment by ert78gb** [comment]
The coverage is missing if the custom coverage mapper function returns with `null`, am I right? Is there any other way to not create coverage?
By default every file that "touched" / involved in the test has coverage.

I am just looking for the use case of the `--allow-empty-coverage`. I just would like to learn.

**Comment by isaacs** [comment]
Also a third option: `--disable-coverage`, which will prevent _collecting_ coverage information, but will still fail if `--allow-empty-coverage` isn't set.

**Comment by isaacs** [comment]
Will go out on the 18.1 release in a few hours.

**Comment by jasonk** [comment]
@isaacs - I just wanted to give you some props..  I've opened a couple of tickets over the last week or so and they all got fixed within a few hours. Just came here with plans to open a ticket requesting some kind of "don't fail for incomplete coverage" flag and find that this time you've managed to fix my problem 7 minutes before I reported it..   👍🏻

**Comment by isaacs** [comment]
Thanks, @jasonk. I appreciate you kicking the tires of the plugin system, too.

One note just to close the loop on this issue: there's no "scary red" warning (unless you count the red lines you'll see if you leave the `--coverage-reporter=text` default, and allow incomplete coverage). It still prints `# No coverage generated` as dim text in the default reporter, but (a) it would've been more work to add the warning, and (b) presumably since this is opt-in, and the docs are pretty clear that it's usually a Bad Idea, if you do it, you know what you're doing and the warning would be more annoying than helpful.

**Comment by ert78gb** [comment]
sorry for the late reaction. @isaacs  Thank you so much the feature.
