### ISSUE TITLE
Tests timeout becase t.end() does not work

### ISSUE THREAD

**Issue by Andriy-Kulak** [tapjs/tapjs#923]
Hi everyone! I am having some trouble with a timeout issue & hoping to get a tip. 

Below is an example of a simple test. I am trying to use `t.pass` or `t.end` to make sure a suite finishes, yet after getting to that part of the test, the test passes but the "suite" fails. 

I am getting this message from terminal: `possible timeout: SIGTERM received after tap end`

And this is my npm script: `"ENV_PATH=.env.test tap --before=./test/setup.ts --reporter=terse --files=./test/auth3.test.ts"`

I am using  `"tap": "^18.1.5"`. t.end or t.pass should just work, no?

```ts
import t from "tap";
import { build } from "../src/app";

const ORG_ID = "xxx";
const USER_TOKEN = "xxx";

t.test("Test Attempt", async () => {
  t.plan(4);
  const app = build();

  t.teardown(() => app.close());

  const testResp2 = await app.inject({
    method: "GET",
    url: `/${ORG_ID}/test`,
    headers: {
      authorization: `Bearer ${USER_TOKEN}`,
    },
  });
  t.equal(testResp2.statusCode, 200);
  t.pass("we passed");
  console.log("WE ARE MAKING IT TO THE END. WHY IS The suite not complete");
  t.end();
});
```

Here is also the screenshot of the errror:
<img width="692" alt="Screenshot 2023-09-26 at 15 42 53" src="https://github.com/tapjs/tapjs/assets/12179976/afde6ae9-ec4e-434d-954f-e735c0ca006e">

**Comment by Andriy-Kulak** [comment]
I tried a more basis script command & getting the same issue `ENV_PATH=.env.test tap`

I also tried the guide from fastify but no luck: https://fastify.dev/docs/v4.3.x/Guides/Testing/#how-to-inspect-tap-tests

At this point I am scrambling a bit & not sure what to do. any tips would be appreciated! :-)

**Comment by isaacs** [comment]
So you're doing `t.plan(4)`, and then only making 2 assertions. So it's not registering that it's over.

Really, it should raise an error about that when you call `t.end()`, because you told it to expect 4 assertions, but then ended after 2. There's also a promise being returned by the test function, because it's `async`, so that might be confusing things as well, not sure. (It shouldn't, but might be anyway, because computers.)

So there's definitely a bug here, I'll try to repro soon. In the meantime, you can probably get around the problem by just removing the `t.plan(4)` line.

**Comment by Andriy-Kulak** [comment]
> So you're doing `t.plan(4)`, and then only making 2 assertions. So it's not registering that it's over.
> 
> Really, it should raise an error about that when you call `t.end()`, because you told it to expect 4 assertions, but then ended after 2. There's also a promise being returned by the test function, because it's `async`, so that might be confusing things as well, not sure. (It shouldn't, but might be anyway, because computers.)
> 
> So there's definitely a bug here, I'll try to repro soon. In the meantime, you can probably get around the problem by just removing the `t.plan(4)` line.

thanks for response! when I removed `t.plan(4)`, the error is the same. also tried `t.plan(1)`. so still not sure what to do. I also tried below with no luck:
-  both `yarn` and `npm`. 
- tap v16 and v18 have the same timeout issue. 
- deleted `node_modules`  and reinstalled

The part that I am trying to understand, is that I simplified below into one simple assertion test. Why is in the image it's stating there are 2 assertions. any ideas?
- my command is: `ENV_PATH=.env.test tap ./test/auth3.test.ts`. If I do `ENV_PATH=.env.test tap`, it also times out.


what else can i try? 


```ts
import tap from "tap";
import { build } from "../src/app";

const ORG_ID = "xxx";
const USER_TOKEN = "yyy";

tap.test("auth test", async (t) => {
  const app = build();
  t.teardown(() => app.close()); // tried with and without this

  const testResp2 = await app.inject({
    method: "GET",
    url: `/${ORG_ID}/test`,
    headers: {
      authorization: `Bearer ${USER_TOKEN}`,
    },
  });
  // ONLY one assertion here
  t.equal(testResp2.statusCode, 200);

  console.log("we getting here");
  t.end();
});
```


<img width="436" alt="Screenshot 2023-09-26 at 19 44 17" src="https://github.com/tapjs/tapjs/assets/12179976/1423cc0c-60b7-4e45-86c5-edb5f7233528">

**Comment by isaacs** [comment]
Ok, at a full keyboard, taking a look at this.

Simplified version, taking fastify out of the equation:

```ts
// t.ts
import t from 'tap'

t.test('auth test', async t => {
  t.plan(4)
  // simplified version, just a timer that'll keep running until canceled
  const app = setInterval(() => {}, 10000)
  t.teardown(() => clearInterval(app))

  // simplified version, just a Promise that resolves
  const testResp2 = await new Promise<number>(res =>
    setTimeout(() => res(200))
  )

  t.equal(testResp2, 200)
  t.end()
})
```

Running with `tap -Rtap t.ts` to get the raw tap data:

```tap
TAP version 14
1..1
# Subtest: t.ts
    # Subtest: auth test
        1..4
        ok 1 - should be equal
        # test count(1) != plan(4)
    not ok 1 - auth test # time=2.484ms
      ---
      at:
        fileName: t.ts
        lineNumber: 3
        columnNumber: 3
        isToplevel: true
      source: |
        import t from 'tap'
      
        t.test('auth test', async t => {
        --^
          t.plan(4)
          // simplified version, just a timer that'll keep running until canceled
      ...
    
    1..1
not ok 1 - t.ts # time=463.686ms
  ---
  stdio: inherit
  cwd: /Users/isaacs/dev/tapjs/tapjs/src/reporter
  externalID: t.ts
  command: /usr/local/bin/node
  args:
    - --import=file:///Users/isaacs/dev/tapjs/tapjs/node_modules/@tapjs/mock/dist/esm/import.mjs
    - --loader=file:///Users/isaacs/dev/tapjs/tapjs/node_modules/ts-node/esm.mjs
    - --no-warnings
    - --enable-source-maps
    - --import=file:///Users/isaacs/dev/tapjs/tapjs/node_modules/@tapjs/processinfo/dist/mjs/import.mjs
    - /Users/isaacs/dev/tapjs/tapjs/src/reporter/t.ts
  context: !symbol/shared tap.isRunner
  exitCode: 1
  signal: null
  ...

# { total: 1, pass: 1 }
# time=488.435ms
```

This is not as bad as I'd thought, but it really should be emitting an actual failing test point for the `test count(1) != plan(4)` error, not just a comment.

Removing the `t.plan(4)`, I see this:

```tap
TAP version 14
1..1
# Subtest: t.ts
    # Subtest: auth test
        ok 1 - should be equal
        1..1
    ok 1 - auth test # time=3.605ms
    
    1..1
ok 1 - t.ts # time=461.761ms

# { total: 1, pass: 1 }
# time=481.368ms
```

which is exactly what I'd expect.

The fact that it's timing out means that something is keeping the process open. You're getting to the end of the test, so it's calling the teardown function, which means that `app.close()` is probably not doing what you think it should do.

Next debugging step, take tap out of the equation. Create a file with only this:

```js
// file.mjs
import { build } from '../src/app'

const ORG_ID = 'xxx'
const USER_TOKEN = 'yyy'
const app = build()
const testResp2 = await app.inject({
  method: 'GET',
  url: `/${ORG_ID}/test`,
  headers: {
    authorization: `Bearer ${USER_TOKEN}`,
  },
})
console.log(testResp2.statusCode)
app.close()
```

If you run that with `node file.mjs`, does it exit gracefully, or hang?  If it hangs, there's your issue. Go figure out why it's doing that, and you'll have your answer. And, keep the test, because the next time it hangs, you'll have a test that fails as a result.

My guess, completely uninformed by your particular app but having done a few of these in my day so maybe worth checking, is that it's connection pooling. Try making your server send a `connection: close` header when you're running your tests, so that it doesn't try to keep connections hanging around for reuse. (In normal cases, you _want_ those connections to be reused, but they'll keep the process from closing, which is a pita for testing.)

**Comment by isaacs** [comment]
Created https://github.com/tapjs/tapjs/issues/924 for the actual bug here, but closing because this otherwise appears to be a problem outside of tap.

**Comment by Andriy-Kulak** [comment]
hmmm. i abstracted this into an  example without tap and node.js terminates properly & doesn't hang. @isaacs what is the purpose of `t.end()` if it doesn't end the test?

**Comment by isaacs** [comment]
`t.end()` does end the test. But it doesn't forcibly exit the process. That would be a problem for example if you had multiple test blocks in one file, nested test suites, etc. 

If a handle or request is currently active, like an open connection or socket or something, then that will prevent the test from exiting normally, and eventually the runner will nuke it with a timeout signal. Can you share the script you're running that takes tap out of the equation? Maybe I can help spot the difference.
