### ISSUE TITLE
[BUG] Error messages (in diff output) should have ANSI escape sequences stripped

### ISSUE THREAD

**Issue by towerofnix** [tapjs/tapjs#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

As the title describes! I apply custom ANSI escape codes to particular thrown error messages, which is useful for output - and not an issue for actually *processing* the error, because in my code, parsing a designed-for-humans error message (even for a test case) is a malpractice. [That's to say that stripping ANSI for *comparing* the message, while possibly a good idea, isn't the issue I'm talking about here.]

Tap generally supports matching these errors fine (since I'm comparing constructor / properties besides the message), but when the error gets stringified for diffing purposes, it isn't so pretty:

<img width="515" alt="Screenshot of a failing test case, with a green background behind the 'actual' part; but the background is suddenly cut off midway through one line!" src="https://github.com/tapjs/tapjs/assets/9948030/0fcceafc-d037-48ab-818b-9868dcd75001">

What's going on is I'm using `\x1b[0m` (or `\ESC[0m` if you prefer) to clear the green foreground attribute that I set a few characters earlier. (It's really hard to see that green text, since it's on tap's green background).

Because tap's utilizing CLI colors for its own purposes - which the error-producing code certainly isn't aware of - I think it would make sense to just strip ANSI escape sequences from error messages. I haven't tried it but [Chalk's strip-ansi](https://github.com/chalk/strip-ansi) module seems suitable, with only one dependency and being developed by the same folk who make [the Chalk terminal colors library itself](https://github.com/chalk/chalk).

### Reproduction

Construct an error with an ANSI escape sequence in its name and `t.match` it against some non-matching value, so that it gets outputted to the diff. Here's a simple repro:

```js
t.match(
    /*                 ↓ bright     ↓ dim        ↓ reset                */
    new Error(`Oh \x1b[1mdeary \x1b[2mdeary \x1b[0mdear.`, {cause: 'foo'}),
    new Error(`Sure.`, {cause: 'bar'}));
```

<img width="224" alt="Error output as expected. The text after the second 'deary' is on a blank background instead of green." src="https://github.com/tapjs/tapjs/assets/9948030/f81c7b44-0b18-4449-8093-38e3b54c5813">

### Environment

```
# npx tap versions
tap: 18.5.2
"@tapjs/config": 2.4.9
"@tapjs/core": 1.4.2
"@tapjs/run": 1.4.9
"@tapjs/stack": 1.2.6
"@tapjs/test": 1.3.13
tap-parser: 15.3.0
tap-yaml: 2.2.0
tcompare: 6.4.3
plugins:
  "@tapjs/after": 1.1.13
  "@tapjs/after-each": 1.1.13
  "@tapjs/asserts": 1.1.13
  "@tapjs/before": 1.1.13
  "@tapjs/before-each": 1.1.13
  "@tapjs/filter": 1.2.13
  "@tapjs/fixture": 1.2.13
  "@tapjs/intercept": 1.2.13
  "@tapjs/mock": 1.2.11
  "@tapjs/node-serialize": 1.2.2
  "@tapjs/snapshot": 1.2.13
  "@tapjs/spawn": 1.1.13
  "@tapjs/stdin": 1.1.13
  "@tapjs/typescript": 1.3.2
  "@tapjs/worker": 1.1.13
```

**Comment by isaacs** [comment]
Indeed, that's not optimal.

Though, if it's _stripped_, that could lead to the confusing situation where diff lines are highlighted, but visually the same. (For example, you might have a test that expects colored output, but due to a mistake in your program, unstyled output is produced, and the diff says "expected `xyz` but got `xyz`", which isn't so helpful.)

Maybe a better way would be to `s/\x1b/\\x1b/g` in the diff lines, so that ANSI escapes are clear?

**Comment by towerofnix** [comment]
Yeah, I think that's pretty fair. I do agree with printing `\x1b` expressly so that it can be easily diffed!

That said, my current issue is that I *do* want colors in my *tap* error output, but *not* in the errors thrown from my own code (except if I were specifically testing that). It does make sense for my code to take responsibility for that (specifically my test file) rather than tap, as tap shouldn't *unexpectedly* change something about the execution envirnoment, but I'm not totally sure how.

I'm currently using a somewhat bulky `if` clause to check a number of environment variables before enabling or disabling color logging altogether.

```js
export const ENABLE_COLOR =
  process &&
  ((process.env.CLICOLOR_FORCE && process.env.CLICOLOR_FORCE === '1') ??
    (process.env.CLICOLOR &&
      process.env.CLICOLOR === '1' &&
      process.stdout.hasColors &&
      process.stdout.hasColors()) ??
    (process.stdout.hasColors ? process.stdout.hasColors() : true));
```

It looks like I can just set `process.env.CLICOLOR_FORCE = 0;` at the top of my test file (and selectively enable it when specifically testing color output). This apparently doesn't get in the way of tap's own color reporting(!), and does disable colors in my own code, as desired.

That said, I want to make sure that setting a value on `process.env` directly like that is "fine" as far as tap's concerned. I'm not sure whether or notf a new process is created for each test file or not under the hood - I *think* that's true because they're simultaneously evaluated, but is that right? Is it safe to assume that the literal value of `process.env` itself isn't shared between tests, i.e. setting `process.env.CLICOLOR_FORCE = 0` in one test file isn't going to cause side effects in another test? Or does tap have a dedicated interface for mutating `process.env` for the current test only?

**Comment by isaacs** [comment]
> That said, I want to make sure that setting a value on process.env directly like that is "fine" as far as tap's concerned.

Yep, each test file is its own separate node process, so that's totally ok. That's why it's so slow if `--typecheck` is enabled and your tests are in TS, because it has to do that separately for each test file, even though most of the work is repeated each time. (I have a project in process that's still in the "research and finger-painting" stage to write a new ts importer that will address this to allow type checking and not take such a huge perf hit for it.)

The test files are run with `stdout` and `stderr` set to `pipe` (because that's how it process the generated TAP stream), so most color-support-detecting tools will default into non-color mode, because `process.stdout.isTTY` will be false when run with the tap cli. But even if you set `process.env.FORCE_COLOR='0'` in your tests or run with `--test-env=FORCE_COLOR=0`, _tap itself_ will still run in colored mode, because the runner process won't be affected by that.

The most common pattern I've seen, which node itself uses, is for `FORCE_COLOR` being set to a number between 0 and 3, and `NO_COLOR` being either set to `'1'` or not set at all.  Tap responds to these, and sets them for itself based on whether its `--color` config is set along with setting `env.TAP_COLOR='1' | '0'` based on the `--color` flag.

Not sure if any of this answers your question or not, but it seems like you can `tap config set test-env=CLICOLOR_FORCE=0`, and then explicitly set it with `process.env.CLICOLOR_FORCE = <whatever>` in the tests where that matters.

Another trick I use a lot, when testing things that do stuff with the environment, is to also use `t.intercept` to provide a clean env to every test, and verify the change made by any given function.  For example:

```ts
import t from 'tap'

// create an object that has the initial env values
const env = { ...process.env }

// hijack the process.env value and reset it to its previous state after each test ends
t.beforeEach(t => t.intercept(process, 'env', { value: { ...env }})

// run a test that sets env stuff
t.test('blah', t => {
  t.equal(process.env.BLAH, undefined, 'not set initially')
  functionThatChangesEnvSomehow()
  t.equal(process.env.BLAH, 'expected value')
  t.end()
})

t.test('not blah', t => {
  // process.env.BLAH is not set here
  t.end()
})
```

**Comment by towerofnix** [comment]
Thank you so much for the detailed summary! I appreciate the example of that `intercept` technique a lot - it's along very similar lines as how I was thinking initially. I'm glad that's supported in a quite succinct way.

Thanks for the information about color environment variables that you're most familiar with and have implemented into tap. That's all great to know! And - right - configuring with `test-env` sounds like the perfect solution here.

I don't use TypeScript in my own projects, but that unfortunate performance hit does make sense - good luck with the project addressing that. Sounds involved!
